Repository ibexa/admin-ui, pull requests merged in 2021-11, with the labels that each got.

#49 Merge IBX-1356
  src/bundle/Resources/translations/content_type.en.xliff
  src/bundle/Resources/views/themes/admin/content_type/tab/view.html.twig
  src/lib/Tab/Dashboard/PagerContentToDataMapper.php
Labels: Ready for MERGE

#51 Cross org merge
  src/lib/Behat/BrowserContext/ContentTypeContext.php
  src/lib/Behat/Component/IbexaDropdown.php
  src/lib/Behat/Page/ContentTypeUpdatePage.php
Labels: Ready for review

#50 IBX-538: Replaced EzPublishCore Twig namespace references with IbexaCore
  src/bundle/Resources/views/themes/admin/ui/field_type/preview/content_fields.html.twig
Labels: Feature

#58 [Behat] Adjusted suite paths to rebranding
  behat_suites.yml
  features/standard/SystemInfo.feature
Labels: Ready for review

#61 IBX-1015: Added support for subitems grouping in admin-ui menu
  src/bundle/Resources/public/scss/_main-menu.scss
  src/bundle/Resources/public/scss/_popup-menu.scss
  src/bundle/Resources/translations/menu.en.xliff
  src/bundle/Resources/views/themes/admin/ui/menu/main_2nd_level.html.twig
  src/bundle/Resources/views/themes/admin/ui/menu/main_base.html.twig
  src/contracts/Menu/AbstractBuilder.php
  src/lib/Menu/MainMenuBuilder.php
  src/lib/Menu/MenuItemFactory.php
  tests/lib/Menu/MainMenuBuilerTest.php
Labels: Doc needed, QA approved

#66 Updated translation messages
  src/bundle/Resources/translations/content.en.xliff
  src/bundle/Resources/translations/content_preview.en.xliff
  src/bundle/Resources/translations/menu.en.xliff
  src/bundle/Resources/translations/messages.en.xliff
Labels: Bug, Ready for review

#65 IBX-1453: Redesigned notification bars
  src/bundle/Resources/public/js/scripts/admin.notifications.js
  src/bundle/Resources/public/js/scripts/helpers/notification.helper.js
  src/bundle/Resources/public/scss/_alerts.scss
  src/bundle/Resources/public/scss/_notifications.scss
  src/bundle/Resources/views/themes/admin/ui/component/alert/alert.html.twig
  src/bundle/Resources/views/themes/admin/ui/layout.html.twig
  src/bundle/Resources/views/themes/admin/ui/notification.html.twig
  src/bundle/ui-dev/src/modules/common/services/notification.service.js
Labels: Doc needed

#73 Cross org merge: Move browser tests to GitHub actions
  .github/workflows/browser-tests.yaml
  .travis.yml
  behat_suites.yml
  src/lib/Behat/Component/Notification.php
Labels: Ready for review
