Repository ibexa/admin-ui, pull requests merged in 2021-12, with the labels that each got.

#82 [Behat] Adapted tests to user menu changes
  src/lib/Behat/Component/UpperMenu.php
Labels: Ready for review

#78 EZEE-3213: Added verification if the user has section/view permission
  src/bundle/Resources/views/themes/admin/trash/list.html.twig
Labels: Bug, Ready for review

#87 [CI] Updated configuration for main branch
  .github/workflows/browser-tests.yaml
  .github/workflows/ci.yaml
Labels: Ready for review

#85 Fixed return type declaration for AbstractBuilder::createMenuItem
  src/contracts/Menu/AbstractBuilder.php
Labels: Doc needed

#98 Merge IBX-1514: Refactored 'read' UDW config resolvers
  src/bundle/Resources/views/themes/admin/ui/search/filters.html.twig
  src/lib/UniversalDiscovery/Event/ConfigResolveEvent.php
  src/lib/UniversalDiscovery/Event/Subscriber/ContentCreate.php
  src/lib/UniversalDiscovery/Event/Subscriber/ReadAllowedContentTypes.php
  tests/lib/UniversalDiscovery/Event/Subscriber/ContentCreateTest.php
  tests/lib/UniversalDiscovery/Event/Subscriber/ReadAllowedContentTypesTest.php
Labels: Ready for review

#101 Cross org merge
  features/standard/ContentType.feature
Labels: Ready for review

#71 IBX-1386: Model edit redesign
  src/bundle/Resources/public/scss/_edit-header.scss
  src/bundle/Resources/views/themes/admin/ui/anchor_navigation_menu.html.twig
  src/bundle/Resources/views/themes/admin/ui/edit_header.html.twig
  src/bundle/Resources/views/themes/admin/ui/layout.html.twig
Labels: Improvement, Ready for review

#118 [Behat] Fixed System info tests
  features/standard/SystemInfo.feature
  src/lib/Behat/Page/SystemInfoPage.php
Labels: Ready for review

#122 IBX-1742: Dropdown not working in Shipping Management - dynamic dropdowns
  src/bundle/Resources/public/js/scripts/core/dropdown.js
  src/bundle/Resources/views/themes/admin/ui/component/dropdown/dropdown.html.twig
Labels: Bug, Improvement

#130 IBX-1733: UDW - Resized window - text on buttons
  src/bundle/Resources/public/scss/ui/modules/universal-discovery/_tab.scss
Labels: Bug, Ready for review

#135 IBX-1719: Content tree - helper text
  src/bundle/Resources/public/scss/ui/modules/content-tree/_list.scss
Labels: Bug, Ready for review

#136 IBX-1675: Notifications text wrapping
  src/bundle/Resources/public/scss/_alerts.scss
Labels: Bug, Ready for review

#134 IBX-1605: Content tree hide button
  src/bundle/Resources/public/scss/_content-tree.scss
  src/bundle/Resources/public/scss/ui/modules/content-tree/_header.scss
  src/bundle/ui-dev/src/modules/content-tree/components/content-tree/content.tree.js
  src/bundle/ui-dev/src/modules/content-tree/components/header/header.js
Labels: Bug, Ready for review

#139 IBX-1785: Fix ibexa-tabs styling
  src/bundle/Resources/public/scss/_tabs.scss
Labels: Bug, Ready for review

#142 IBX-1685: content tree headline - resize
  src/bundle/Resources/public/scss/ui/modules/content-tree/_header.scss
  src/bundle/ui-dev/src/modules/content-tree/components/header/header.js
Labels: Bug, Ready for review

#145 IBX-1350: autosave icon color
  src/bundle/Resources/public/scss/_autosave.scss
Labels: Bug, Ready for review

#144 IBX-1537: Cutted dashboard
  src/bundle/Resources/public/scss/_dashboard.scss
  src/bundle/Resources/views/themes/admin/ui/dashboard/dashboard.html.twig
  src/lib/Behat/Page/DashboardPage.php
Labels: Bug, Ready for review

#146 IBX-1802: Update design for location swap and table locations
  src/bundle/Resources/public/js/scripts/admin.location.visibility.js
  src/bundle/Resources/public/js/scripts/core/toggle.button.js
  src/bundle/Resources/public/scss/_content-locations.scss
  src/bundle/Resources/public/scss/_general.scss
  src/bundle/Resources/public/scss/_location-swap-form.scss
  src/bundle/Resources/public/scss/_mixins.scss
  src/bundle/Resources/public/scss/ibexa.scss
  src/bundle/Resources/views/themes/admin/content/tab/locations/panel_swap.html.twig
  src/bundle/Resources/views/themes/admin/content/tab/locations/tab.html.twig
Labels: Bug, Ready for review
