Repository ibexa/admin-ui, pull requests merged in 2022-11, with the labels that each got.

#604 IBX-4012: Moving to a form section does not show chosen section as active
  src/bundle/Resources/public/js/scripts/admin.anchor.navigation.js
  src/bundle/Resources/public/scss/_content-edit.scss
  src/bundle/Resources/public/scss/_content-type-edit.scss
  src/bundle/Resources/views/themes/admin/content/edit_base.html.twig
  src/lib/Menu/ContentEditAnchorMenuBuilder.php
Labels: Bug, QA approved

#622 IBX-3524: Removed icon and added default none to dropdown placeholder
  src/bundle/Resources/translations/messages.en.xliff
  src/bundle/Resources/views/themes/admin/ui/component/dropdown/dropdown.html.twig
Labels: Bug, QA approved, Ready for MERGE

#628 IBX-4120: fixed margin and padding for UDW list view
  src/bundle/Resources/public/scss/ui/modules/universal-discovery/_finder.branch.scss
  src/bundle/Resources/public/scss/ui/modules/universal-discovery/_finder.leaf.scss
Labels: Bug, QA approved, Ready for MERGE

#627 IBX-3667: Added icon for embed inline
  src/bundle/Resources/public/img/ibexa-icons.svg
  src/bundle/Resources/public/img/icons/embed-inline.svg
  src/bundle/Resources/public/img/icons/embed.svg
Labels: Bug

#629 IBX-3301: Product type - disable button Add when there is no option to add more elements
  src/bundle/Resources/public/js/scripts/admin.contenttype.edit.js
  src/bundle/Resources/public/scss/_buttons.scss
Labels: Bug, QA approved, Ready for MERGE

#617 IBX-3901: Add empty field after bulk delete all authors
  src/bundle/Resources/public/js/scripts/fieldType/ezauthor.js
Labels: QA approved

#634 [Behat] Added missing element name to Content Update selectors
  src/lib/Behat/Page/ContentUpdateItemPage.php
Labels: Ready for review

#435 IBX-2925: [D&D] Functionality and design improvements
  src/bundle/Resources/public/js/scripts/admin.contenttype.edit.js
  src/bundle/Resources/public/js/scripts/core/draggable.js
  src/bundle/Resources/public/scss/_content-type-edit.scss
  src/bundle/Resources/public/scss/mixins/_drag-and-drop.scss
  src/bundle/Resources/views/themes/admin/content_type/available_field_types.html.twig
  src/bundle/Resources/views/themes/admin/content_type/field_definition.html.twig
  src/bundle/Resources/views/themes/admin/content_type/field_definitions.html.twig
  src/bundle/Resources/views/themes/admin/content_type/field_definitions_placeholder.html.twig
  src/bundle/Resources/views/themes/admin/content_type/part/field_definition_form.html.twig
  src/bundle/Resources/views/themes/admin/ui/component/collapse.html.twig
  src/lib/Behat/BrowserContext/ContentTypeContext.php
  src/lib/Behat/Page/ContentTypeUpdatePage.php
Labels: QA approved

#613 IBX-4044: Option to use HTML in tooltips
  src/bundle/Resources/public/js/scripts/helpers/tooltips.helper.js
  src/bundle/Resources/views/themes/admin/content/edit/content_header.html.twig
  src/bundle/Resources/views/themes/admin/ui/edit_header.html.twig
Labels: QA approved

#632 IBX-4183: Added more precise selector for hover efect of subitems view select
  src/bundle/Resources/public/scss/ui/modules/sub-items-list/_main.scss
Labels: Bug, QA approved, Ready for MERGE

#624 [Behat] IBX-3729: Updated CommerceUserCreation scenario
  src/lib/Behat/BrowserContext/ContentViewContext.php
  src/lib/Behat/Page/ContentViewPage.php
Labels: Ready for review

#630 IBX-4164: Fixed fill color for notifications icons
  src/bundle/Resources/public/scss/_alerts.scss
Labels: Bug, QA approved

#636 IBX-3177: Fixed margin left in location details view
  src/bundle/Resources/public/scss/_details.scss
  src/bundle/Resources/public/scss/_tables.scss
Labels: Bug

#631 IBX-3552: updated focus for dropdown button
  src/bundle/Resources/public/scss/_adaptive-filters.scss
  src/bundle/Resources/public/scss/_dropdown.scss
Labels: QA approved

#643 IBX-4278: Missing hover on input text while hovering over icons inside
  src/bundle/Resources/public/scss/_inputs.scss
Labels: QA approved

#646 IBX-3562: calendar day arrows
  src/bundle/Resources/public/scss/_dropdown.scss
  src/bundle/ui-dev/src/modules/common/dropdown/dropdown.js
Labels: Bug, QA approved

#616 IBX-3973: Nontranslatable and disabled fields are not greyed out in content editing UI
  src/bundle/Resources/public/js/scripts/fieldType/ezauthor.js
  src/bundle/Resources/public/js/scripts/fieldType/ezgmaplocation.js
  src/bundle/Resources/public/js/scripts/fieldType/ezobjectrelationlist.js
  src/bundle/Resources/public/scss/_date-time-picker.scss
  src/bundle/Resources/public/scss/_dropdown.scss
  src/bundle/Resources/public/scss/_forms.scss
  src/bundle/Resources/public/scss/fieldType/edit/_base-field.scss
  src/bundle/Resources/public/scss/fieldType/edit/_base-preview.scss
  src/bundle/Resources/public/scss/fieldType/edit/_ezgmaplocation.scss
  src/bundle/Resources/public/scss/fieldType/edit/_ezimageasset.scss
  src/bundle/Resources/public/scss/fieldType/edit/_ezkeyword.scss
  src/bundle/Resources/public/scss/fieldType/edit/_ezobjectrelationlist.scss
  src/bundle/Resources/views/themes/admin/content/form_fields.html.twig
  src/bundle/Resources/views/themes/admin/ui/component/dropdown/dropdown.html.twig
  src/bundle/Resources/views/themes/admin/ui/field_type/edit/binary_base.html.twig
  src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezauthor.html.twig
  src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezbinaryfile.html.twig
  src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezdate.html.twig
  src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezdatetime.html.twig
  src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezgmaplocation.html.twig
  src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezimage.html.twig
  src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezimageasset.html.twig
  src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezmedia.html.twig
  src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezselection.html.twig
  src/bundle/Resources/views/themes/admin/ui/field_type/edit/eztime.html.twig
  src/bundle/Resources/views/themes/admin/ui/field_type/edit/relation_base.html.twig
  src/bundle/Resources/views/themes/admin/ui/form_fields/toggle_widget.html.twig
Labels: Ready for QA

#649 [Behat] Added wait in userCreation.feature during user enabling
  src/lib/Behat/Component/Fields/User.php
Labels: Ready for review

#639 IBX-4213: Missing hovers on icons
  src/bundle/Resources/public/scss/_buttons.scss
  src/bundle/Resources/public/scss/_content-type-selector.scss
  src/bundle/Resources/public/scss/_header-user-menu.scss
  src/bundle/Resources/public/scss/_inputs.scss
  src/bundle/Resources/public/scss/_main-header.scss
  src/bundle/Resources/views/themes/admin/ui/component/input_text.html.twig
  src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
Labels: Ready for QA

#587 [Behat] IBX-3842: Extend test scenarios for Products
  src/lib/Behat/Page/ContentUpdateItemPage.php
  src/lib/Behat/Page/ContentViewPage.php
Labels: Ready for review

#626 IBX-4061: Added new modifiers to ibexa-link
  src/bundle/Resources/public/scss/_links.scss
Labels: QA approved, Ready for MERGE

#653 [Behat] Increased timeout for transition condition
  src/lib/Behat/Page/ContentTypeUpdatePage.php
Labels: Ready for review

#644 IBX-4214: Fixed hover style
  src/bundle/Resources/public/scss/_dropdown.scss
  src/bundle/Resources/public/scss/ui/modules/common/_simple.dropdown.scss
  src/bundle/ui-dev/src/modules/common/simple-dropdown/simple.dropdown.js
  src/bundle/ui-dev/src/modules/sub-items/components/view-switcher/view.switcher.component.js
  src/bundle/ui-dev/src/modules/universal-discovery/components/sort-switcher/sort.switcher.js
  src/bundle/ui-dev/src/modules/universal-discovery/components/view-switcher/view.switcher.js
Labels: Bug, QA approved

#648 IBX-4324: fixed overflow in selected items sidebar
  src/bundle/Resources/public/img/ibexa-icons.svg
  src/bundle/Resources/public/img/icons/caret-double-back.svg
  src/bundle/Resources/public/img/icons/caret-double-next.svg
  src/bundle/Resources/public/scss/ui/modules/universal-discovery/_content.edit.button.scss
  src/bundle/Resources/public/scss/ui/modules/universal-discovery/_selected.locations.item.scss
  src/bundle/Resources/public/scss/ui/modules/universal-discovery/_selected.locations.scss
  src/bundle/Resources/translations/universal_discovery_widget.en.xliff
  src/bundle/ui-dev/src/modules/universal-discovery/components/selected-locations/selected.locations.item.js
  src/bundle/ui-dev/src/modules/universal-discovery/components/selected-locations/selected.locations.js
Labels: QA approved, Ready for MERGE
