Repository ibexa/admin-ui, pull requests merged in 2022-05, with the labels that each got.

#391 IBX-2655: create/edit layout fixes
  src/bundle/Resources/public/scss/_anchor-navigation.scss
  src/bundle/Resources/public/scss/_content-edit.scss
  src/bundle/Resources/public/scss/_content-type-edit.scss
  src/bundle/Resources/public/scss/_edit-header.scss
  src/bundle/Resources/public/scss/_main-container.scss
  src/bundle/Resources/public/scss/mixins/_containers.scss
  src/bundle/Resources/views/themes/admin/account/change_password/index.html.twig
  src/bundle/Resources/views/themes/admin/account/settings/update.html.twig
  src/bundle/Resources/views/themes/admin/content/edit/edit.html.twig
  src/bundle/Resources/views/themes/admin/content/edit_base.html.twig
  src/bundle/Resources/views/themes/admin/content_type/content_type_group/base.html.twig
  src/bundle/Resources/views/themes/admin/content_type/create.html.twig
  src/bundle/Resources/views/themes/admin/content_type/edit.html.twig
  src/bundle/Resources/views/themes/admin/content_type/edit_base.html.twig
  src/bundle/Resources/views/themes/admin/content_type/edit_section.html.twig
  src/bundle/Resources/views/themes/admin/language/base.html.twig
  src/bundle/Resources/views/themes/admin/link_manager/edit.html.twig
  src/bundle/Resources/views/themes/admin/object_state/base.html.twig
  src/bundle/Resources/views/themes/admin/object_state/object_state_group/base.html.twig
  src/bundle/Resources/views/themes/admin/section/base.html.twig
  src/bundle/Resources/views/themes/admin/section/create.html.twig
  src/bundle/Resources/views/themes/admin/ui/anchor_navigation_menu.html.twig
  src/bundle/Resources/views/themes/admin/ui/anchor_navigation_section.html.twig
  src/bundle/Resources/views/themes/admin/ui/edit_base.html.twig
  src/bundle/Resources/views/themes/admin/ui/edit_header.html.twig
  src/bundle/Resources/views/themes/admin/ui/edit_section.html.twig
  src/bundle/Resources/views/themes/admin/user/policy/base.html.twig
  src/bundle/Resources/views/themes/admin/user/role/base.html.twig
  src/bundle/Resources/views/themes/admin/user/role_assignment/base.html.twig
  src/lib/Behat/Page/RoleUpdatePage.php
Labels: Improvement, QA approved

#419 [Behat] Fixed selector in workflowLimitation.feature
  src/lib/Behat/Page/ContentUpdateItemPage.php
Labels: Ready for review

#412 IBX-2673: Unable to scroll grid view in UDW
  src/bundle/Resources/public/scss/ui/modules/universal-discovery/_main.scss
Labels: QA approved, Ready for MERGE

#414 IBX-2417: Size of avatar in header
  src/bundle/Resources/public/scss/_header-user-menu.scss
  src/bundle/Resources/views/themes/admin/ui/menu/user.html.twig
Labels: QA approved

#411 IBX-2775: Fixed main menu selection
  src/bundle/Resources/public/js/scripts/sidebar/main.menu.js
  src/bundle/Resources/public/scss/_main-menu.scss
  src/bundle/Resources/public/scss/_popup-menu.scss
  src/bundle/Resources/views/themes/admin/ui/menu/main.html.twig
Labels: Bug, QA approved

#418 IBX-2777: Personalization - model edit fixes
  src/bundle/Resources/public/scss/_content-type-edit.scss
  src/bundle/Resources/public/scss/mixins/_drag-and-drop.scss
  src/bundle/Resources/views/themes/admin/content_type/field_definitions_empty_group.html.twig
Labels: QA approved, Ready for MERGE

#420 IBX-2837: Missing spinner when content is loaded in meta data in search
  src/bundle/ui-dev/src/modules/universal-discovery/components/content-table/content.table.item.js
  src/bundle/ui-dev/src/modules/universal-discovery/hooks/useSearchByQueryFetch.js
Labels: QA approved

#421 IBX-2871: Wrong spacing on some admin pages
  src/bundle/Resources/public/scss/_header.scss
  src/bundle/Resources/public/scss/_tabs.scss
  src/bundle/Resources/public/scss/ui/modules/sub-items-list/_main.scss
  src/bundle/Resources/views/themes/admin/account/bookmarks/list.html.twig
  src/bundle/Resources/views/themes/admin/account/settings/list.html.twig
  src/bundle/Resources/views/themes/admin/content/draft/draft_list.html.twig
  src/bundle/Resources/views/themes/admin/content/edit/content_header.html.twig
  src/bundle/Resources/views/themes/admin/content/location_view.html.twig
  src/bundle/Resources/views/themes/admin/content_type/tab/view.html.twig
  src/bundle/Resources/views/themes/admin/link_manager/list.html.twig
  src/bundle/Resources/views/themes/admin/trash/list.html.twig
  src/bundle/Resources/views/themes/admin/ui/component/tab/tabs_header.html.twig
  src/bundle/Resources/views/themes/admin/ui/tab/content_type.html.twig
  src/bundle/Resources/views/themes/admin/url_management/url_management.html.twig
  src/bundle/Resources/views/themes/admin/url_wildcard/list.html.twig
  src/bundle/Resources/views/themes/admin/url_wildcard/update.html.twig
  src/bundle/Resources/views/themes/admin/user/policy/list.html.twig
  src/bundle/Resources/views/themes/admin/user/role_assignment/list.html.twig
Labels: QA approved, Ready for MERGE

#424 IBX-2760: Number input - clear X button overlaps with the number
  src/bundle/Resources/public/scss/fieldType/edit/_ezinteger.scss
Labels: QA approved, Ready for MERGE

#426 IBX-2414: Button "create" - wrong priority
  src/lib/Menu/Admin/ContentType/ContentTypeCreateRightSidebarBuilder.php
  src/lib/Menu/Admin/ContentType/ContentTypeEditRightSidebarBuilder.php
  src/lib/Menu/Admin/ContentType/ContentTypeGroupCreateRightSidebarBuilder.php
  src/lib/Menu/Admin/ContentType/ContentTypeGroupEditRightSidebarBuilder.php
  src/lib/Menu/Admin/Language/LanguageCreateRightSidebarBuilder.php
  src/lib/Menu/Admin/Language/LanguageEditRightSidebarBuilder.php
  src/lib/Menu/Admin/ObjectState/ObjectStateCreateRightSidebarBuilder.php
  src/lib/Menu/Admin/ObjectState/ObjectStateEditRightSidebarBuilder.php
  src/lib/Menu/Admin/ObjectState/ObjectStateGroupCreateRightSidebarBuilder.php
  src/lib/Menu/Admin/ObjectState/ObjectStateGroupEditRightSidebarBuilder.php
  src/lib/Menu/Admin/Role/PolicyCreateRightSidebarBuilder.php
  src/lib/Menu/Admin/Role/RoleCreateRightSidebarBuilder.php
  src/lib/Menu/Admin/Role/RoleEditRightSidebarBuilder.php
  src/lib/Menu/SectionCreateRightSidebarBuilder.php
  src/lib/Menu/SectionEditRightSidebarBuilder.php
  src/lib/Menu/URLEditRightSidebarBuilder.php
  src/lib/Menu/URLWildcardEditRightSidebarBuilder.php
  src/lib/Menu/UserSetting/UserSettingUpdateRightSidebarBuilder.php
Labels: QA approved, Ready for MERGE

#425 IBX-2869: [Navigation menu] Field groups navigation menu cannot unselect 2nd choice
  src/bundle/Resources/public/js/scripts/admin.anchor.navigation.js
Labels: QA approved, Ready for MERGE

#417 IBX-1129: As a developer I want to get rid of deprecated React lifecycle methods
  src/bundle/ui-dev/src/modules/common/popup/popup.component.js
Labels: QA approved

#392 IBX-2658: Introduce adaptive filters
  src/bundle/Resources/encore/ibexa.js.config.js
  src/bundle/Resources/public/js/scripts/adaptive.filters.js
  src/bundle/Resources/public/js/scripts/core/adaptive.items.js
  src/bundle/Resources/public/scss/_adaptive-filters.scss
  src/bundle/Resources/public/scss/ibexa.scss
  src/bundle/Resources/translations/adaptive_filters.en.xliff
  src/bundle/Resources/views/themes/admin/ui/component/adaptive_filters/adaptive_filters.html.twig
  src/bundle/Resources/views/themes/admin/ui/component/adaptive_filters/adaptive_filters_item.html.twig
Labels: QA approved, Ready for MERGE

#429 IBX-2918: Improvement collapse panel
  src/bundle/Resources/public/scss/_field-group.scss
  src/bundle/Resources/translations/messages.en.xliff
  src/bundle/Resources/views/themes/admin/content/content_view_fields.html.twig
Labels: Improvement, QA approved

#430 IBX-2920: Fixed rolled-up styles
  src/bundle/Resources/public/js/scripts/admin.location.adaptive.tabs.js
  src/bundle/Resources/public/scss/_tabs.scss
Labels: Bug, QA approved

#431 IBX-2898: Added icon for upload image
  src/bundle/Resources/public/img/ibexa-icons.svg
  src/bundle/Resources/public/img/icons/upload-image.svg
Labels: QA approved

#441 IBX-2939: Field order in CT edit is incorrectly saved on refresh
  src/bundle/Controller/FieldDefinitionController.php
Labels: QA approved
