Repository ibexa/admin-ui, pull requests merged in 2022-02, with the labels that each got.

#283 [Behat] Added switching into specific tabs in Roles feature
  src/lib/Behat/Component/UniversalDiscoveryWidget.php
  src/lib/Behat/Page/AdminUpdateItemPage.php
  src/lib/Behat/Page/RoleUpdatePage.php
Labels: Ready for review

#284 IBX-1696: Rebranded Container parameters and Config Resolver namespaces
  src/bundle/DependencyInjection/Compiler/SecurityLoginPass.php
  src/bundle/Resources/config/default_parameters.yaml
  src/bundle/Resources/config/ezplatform_default_settings.yaml
  src/bundle/Resources/config/role.yaml
  src/bundle/Resources/config/services.yaml
  src/bundle/Resources/config/services/events.yaml
  src/bundle/Resources/config/services/form_processors.yaml
  src/bundle/Resources/config/services/forms.yaml
  src/bundle/Resources/config/services/rest.yaml
  src/bundle/Resources/config/services/role_form_mappers.yaml
  src/bundle/Resources/config/services/siteaccess.yaml
  src/bundle/Resources/config/services/translation.yaml
  src/bundle/Resources/config/services/ui_config/common.yaml
  src/bundle/Resources/config/services/user_settings.yaml
  src/bundle/Resources/config/services/views.yaml
Labels: Feature

#286 IBX-2172: Added options to disable fields in FieldDefinitionType
  src/bundle/Resources/public/scss/_content-type-edit.scss
  src/bundle/Resources/views/themes/admin/content_type/field_definition.html.twig
  src/lib/Form/Type/FieldDefinition/FieldDefinitionType.php
Labels: Improvement, Ready for review

#301 IBX-1853: Used rebranded Ibexa name in codebase
  bootstrap.php
  features/standard/ContentType.feature
  features/standard/ContentTypeFields.feature
  features/standard/Roles.feature
  src/bundle/Controller/ContentViewController.php
  src/bundle/DependencyInjection/IbexaAdminUiExtension.php
  src/bundle/Resources/config/services/pagination.yaml
  src/bundle/Resources/views/themes/admin/content/tab/locations/tab.html.twig
  src/bundle/Resources/views/themes/admin/link_manager/view.html.twig
  src/bundle/Resources/views/themes/admin/ui/pagination.html.twig
  src/bundle/View/EzPagerfantaView.php
  src/contracts/Form/Data/FormMapper/FormDataMapperInterface.php
  src/lib/Form/Data/FormMapper/ContentCreateMapper.php
  src/lib/Form/Data/FormMapper/ContentTranslationMapper.php
  src/lib/Form/Data/FormMapper/ContentTypeDraftMapper.php
  src/lib/Form/Data/FormMapper/ContentUpdateMapper.php
  src/lib/Form/Data/FormMapper/UserUpdateMapper.php
  src/lib/Pagination/Pagerfanta/NotificationAdapter.php
  src/lib/Pagination/Pagerfanta/TrashItemAdapter.php
  src/lib/QueryType/ContentSubtreeQueryType.php
  src/lib/QueryType/LocationPathQueryType.php
  src/lib/QueryType/MediaSubtreeQueryType.php
  src/lib/QueryType/TrashSearchQueryType.php
  src/lib/Strategy/NotificationTwigStrategy.php
  tests/lib/QueryType/SearchQueryTypeTest.php
  tests/lib/Translation/Extractor/LimitationTranslationExtractorTest.php
  tests/lib/Validator/Constraint/UniqueURLValidatorTest.php
Labels: Ready for MERGE

#318 As a developer, I would like to be able to automatically generate an id based on a given field
  src/bundle/Resources/encore/ibexa.js.config.js
  src/bundle/Resources/public/js/scripts/autogenerate.identifier.js
Labels: QA approved

#321 IBX-2283: Noto Sans fonts
  src/bundle/Resources/public/font/NotoSans-Bold.ttf
  src/bundle/Resources/public/font/NotoSans-BoldItalic.ttf
  src/bundle/Resources/public/font/NotoSans-Italic.ttf
  src/bundle/Resources/public/font/NotoSans-Regular.ttf
  src/bundle/Resources/public/font/NotoSans-SemiBold.ttf
  src/bundle/Resources/public/font/NotoSans-SemiBoldItalic.ttf
  src/bundle/Resources/public/scss/_fonts.scss
  src/bundle/Resources/public/scss/ibexa-bootstrap.scss
Labels: QA approved, Ready for QA

#326 IBX-2299: Added `config-name` option to ibexa:encore:compile command
  src/bundle/Command/CompileAssetsCommand.php
Labels: Bug, Ready for review

#322 IBX-2285: If content is hidden, user can still click Hide button and nothing happens
  src/bundle/Resources/public/js/scripts/admin.context.menu.js
Labels: QA approved, Ready for MERGE

#323 IBX-2287: Context menu in location view doesn't respect it's max available width
  src/bundle/Resources/views/themes/admin/content/location_view.html.twig
Labels: QA approved, Ready for MERGE

#325 IBX-2288: Use ResizeObserver for adaptive items and subitems
  src/bundle/Resources/public/js/scripts/admin.context.menu.js
  src/bundle/Resources/public/js/scripts/admin.location.adaptive.tabs.js
  src/bundle/Resources/public/js/scripts/core/adaptive.items.js
  src/bundle/ui-dev/src/modules/sub-items/sub.items.module.js
Labels: QA approved, Ready for MERGE

#332 IBX-2178 drag&drop sidebar does not hide elements properly when searching
  src/bundle/Resources/public/scss/mixins/_drag-and-drop.scss
Labels: Bug, QA approved

#330 IBX-1045: Author field type margins
  src/bundle/Resources/public/scss/fieldType/edit/_ezauthor.scss
Labels: Bug, QA approved

#320 IBX-2278: Added spinner to loading location meta data
  src/bundle/Resources/public/scss/ui/modules/universal-discovery/_content.meta.preview.scss
  src/bundle/ui-dev/src/modules/universal-discovery/content.meta.preview.module.js
Labels: Improvement, QA approved

#331 IBX-1376: Delete unnecessary letter-spacing 0.12px in CSS
  src/bundle/Resources/public/scss/_dropdown.scss
  src/bundle/Resources/public/scss/_grid-view-item.scss
  src/bundle/Resources/public/scss/_icon-tag.scss
  src/bundle/Resources/public/scss/_tag-view-select.scss
  src/bundle/Resources/public/scss/mixins/_tags.scss
  src/bundle/Resources/public/scss/ui/modules/content-tree/_popup.actions.scss
  src/bundle/Resources/public/scss/ui/modules/universal-discovery/_content.meta.preview.scss
  src/bundle/Resources/public/scss/ui/modules/universal-discovery/_finder.branch.scss
Labels: Bug, QA approved

#339 IBX-2406: Fix main menu buttons text vertical alignemnt
  src/bundle/Resources/public/scss/_main-menu.scss
Labels: QA approved, Ready for MERGE

#338 IBX-2405: Fix ibexa-toggle disabled state - needless grey horizontal line (checkbox input)
  src/bundle/Resources/public/scss/_inputs.scss
Labels: QA approved, Ready for MERGE

#329 IBX-1496: When configuring a Content Type - the Category dropdown should removed
  src/lib/Form/Type/FieldDefinition/FieldDefinitionType.php
Labels: Bug, QA approved

#337 IBX-2403: Fix SCSS calculateRem to return proper rem
  src/bundle/Resources/public/scss/_custom.scss
  src/bundle/Resources/public/scss/functions/_calculate.rem.scss
  src/bundle/Resources/public/scss/mixins/_modals.scss
Labels: QA approved, Ready for MERGE

#342 IBX-2422: Cannot Select from library in ImageAsset field
  src/bundle/ui-dev/src/modules/universal-discovery/content.meta.preview.module.js
Labels: Bug, QA approved
