Repository ibexa/admin-ui, pull requests merged in 2022-08, with the labels that each got.

#526 IBX-3523: Introduced tabs to left sidebar in Content Edit interface
  src/bundle/DependencyInjection/Configuration/Parser/AdminUiForms.php
  src/bundle/Resources/config/admin_ui_forms.yaml
  src/bundle/Resources/config/services/components/content/edit.yaml
  src/bundle/Resources/config/services/events.yaml
  src/bundle/Resources/config/services/forms.yaml
  src/bundle/Resources/config/services/menu.yaml
  src/bundle/Resources/encore/ibexa.js.config.js
  src/bundle/Resources/public/js/scripts/admin.anchor.navigation.js
  src/bundle/Resources/public/js/scripts/admin.anchor.sections.navigation.js
  src/bundle/Resources/public/js/scripts/admin.content.edit.js
  src/bundle/Resources/public/scss/_content-edit.scss
  src/bundle/Resources/public/scss/_main-container.scss
  src/bundle/Resources/public/scss/_navigation-menu.scss
  src/bundle/Resources/public/scss/ibexa.scss
  src/bundle/Resources/translations/menu.en.xliff
  src/bundle/Resources/views/themes/admin/content/components/meta_fields.html.twig
  src/bundle/Resources/views/themes/admin/content/edit/edit.html.twig
  src/bundle/Resources/views/themes/admin/content/edit_base.html.twig
  src/bundle/Resources/views/themes/admin/ui/anchor_navigation_menu.html.twig
  src/bundle/Resources/views/themes/admin/ui/anchor_navigation_section.html.twig
  src/bundle/Resources/views/themes/admin/ui/component/anchor_navigation/primary_section.html.twig
  src/bundle/Resources/views/themes/admin/ui/component/anchor_navigation/secondary_section.html.twig
  src/bundle/Resources/views/themes/admin/ui/menu/anchor_menu.html.twig
  src/lib/Component/Content/ContentEditMetaFieldsComponent.php
  src/lib/EventListener/SetViewParametersListener.php
  src/lib/Form/Provider/GroupedNonMetaFormFieldsProvider.php
  src/lib/Menu/ContentEditAnchorMenuBuilder.php
  src/lib/Menu/Event/ConfigureMenuEvent.php
  tests/bundle/DependencyInjection/Configuration/Parser/AdminUiFormsTest.php
  tests/lib/EventListener/SetViewParametersListenerTest.php
Labels: Doc needed, Feature, QA approved

#522 IBX-3364: Increased right padding for --ghost dropdown
  src/bundle/Resources/public/scss/_dropdown.scss
Labels: Bug, Ready for QA

#535 IBX-3530: Added border color for toolbox item on hover
  src/bundle/Resources/public/scss/mixins/_drag-and-drop.scss
Labels: Bug, Ready for review

#523 IBX-3459: js error when trying create content type without defined fields
  src/bundle/Resources/config/bazinga_js_translation.yaml
  src/bundle/Resources/public/js/scripts/admin.contenttype.edit.js
Labels: Bug, QA approved

#536 IBX-3471: Updated trash view
  src/bundle/Resources/public/scss/_trash-search-form.scss
  src/bundle/Resources/views/themes/admin/trash/list.html.twig
  src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
Labels: Bug, QA approved

#539 IBX-3532: Improved autosave messages
  src/bundle/Resources/public/js/scripts/admin.content.edit.js
  src/bundle/Resources/public/scss/_autosave.scss
  src/bundle/Resources/translations/content.en.xliff
Labels: Bug, QA approved

#541 IBX-3643: Fix ibexa-toggle width, cursors, nonselect
  src/bundle/Resources/public/scss/_inputs.scss
Labels: QA approved, Ready for MERGE

#543 IBX-3640: Cannot search by partial name in catalog filters
  src/bundle/Resources/public/js/scripts/core/dropdown.js
Labels: Bug, QA approved

#544 IBX-3493: Fixed hover state in button info
  src/bundle/Resources/public/scss/_buttons.scss
Labels: Bug, QA approved, Ready for MERGE

#551 IBX-2559: Added new style to ez-extra-actions__content class to allow scrolling language list
  src/bundle/Resources/public/scss/_extra-actions.scss
Labels: Bug, QA approved, Ready for MERGE

#540 IBX-3022: Improved language selector
  src/bundle/Resources/public/scss/_field-group.scss
  src/bundle/Resources/views/themes/admin/content/tab/content.html.twig
Labels: Improvement, QA approved, Ready for MERGE

#555 IBX-3725: Removed colon from Content View labels
  src/bundle/Resources/views/themes/admin/content/content_view_fields.html.twig
  src/lib/Behat/Component/ContentItemAdminPreview.php
Labels: QA approved

#552 IBX-3707: Tag view select items are incorrectly ellipsized
  src/bundle/Resources/public/scss/_tag-view-select.scss
  src/bundle/Resources/views/themes/admin/ui/component/tag_view_select/tag_view_select_selected_item_tag.html.twig
Labels: QA approved, Ready for MERGE

#547 IBX-3409: Dropped whole form_widget form rendering for user registration
  src/bundle/Resources/views/themes/admin/account/register/index.html.twig
Labels: QA approved
