Repository ibexa/admin-ui, pull requests merged in 2022-07, with the labels that each got.

#478 IBX-3085: As a Developer, I want to have thumbnail twig component
  src/bundle/Resources/public/scss/_header-user-menu.scss
  src/bundle/Resources/public/scss/_user-thumbnail.scss
  src/bundle/Resources/public/scss/ibexa.scss
  src/bundle/Resources/views/themes/admin/ui/component/adaptive_filters/adaptive_filters.html.twig
  src/bundle/Resources/views/themes/admin/ui/component/user_thumbnail/user_thumbnail.html.twig
  src/bundle/Resources/views/themes/admin/ui/menu/user.html.twig
Labels: Doc needed, QA approved

#447 IBX-2954: Added option to invite users into groups
  .gitignore
  src/bundle/Controller/ContentViewController.php
  src/bundle/Controller/User/InvitationController.php
  src/bundle/Resources/config/routing.yaml
  src/bundle/Resources/config/services/controllers.yaml
  src/bundle/Resources/encore/ibexa.js.config.js
  src/bundle/Resources/public/js/scripts/user.group.invitation.js
  src/bundle/Resources/public/js/scripts/user.invitation.modal.js
  src/bundle/Resources/public/scss/_user-group-invitation.scss
  src/bundle/Resources/public/scss/_user-invitation-modal.scss
  src/bundle/Resources/public/scss/ibexa.scss
  src/bundle/Resources/translations/forms.en.xliff
  src/bundle/Resources/translations/locationview.en.xliff
  src/bundle/Resources/translations/menu.en.xliff
  src/bundle/Resources/translations/user_invitation.en.xliff
  src/bundle/Resources/views/themes/admin/content/location_view.html.twig
  src/bundle/Resources/views/themes/admin/content/modal/user_group_invitation_modal.html.twig
  src/bundle/Resources/views/themes/admin/content/modal/user_group_invitation_modal_form_fields.html.twig
  src/bundle/Resources/views/themes/admin/user/invitation/modal.html.twig
  src/lib/Form/Type/User/UserInvitationType.php
  src/lib/Menu/ContentRightSidebarBuilder.php
Labels: QA approved

#443 Changed name of configuration for translation extraction
  src/bundle/DependencyInjection/IbexaAdminUiExtension.php
Labels: Improvement

#472 IBX-2381: The distance between items and label (Settings) in the menu is incorrect
  src/bundle/Resources/public/scss/_main-menu.scss
Labels: QA approved, Ready for MERGE

#432 IBX-2937: Added new relation starting location options
  src/bundle/Controller/ContentOnTheFlyController.php
  src/bundle/Controller/UniversalDiscoveryController.php
  src/bundle/Controller/UserOnTheFlyController.php
  src/bundle/Resources/public/js/scripts/admin.contenttype.relation.default.location.js
  src/bundle/Resources/public/scss/_default-location.scss
  src/bundle/Resources/public/scss/ibexa.scss
  src/bundle/Resources/translations/content_type.en.xliff
  src/bundle/Resources/views/themes/admin/content_type/field_types.html.twig
  src/bundle/Resources/views/themes/admin/content_type/relation_form_fields.html.twig
  src/bundle/Resources/views/themes/admin/content_type/relation_list_form_fields.html.twig
  src/bundle/Resources/views/themes/admin/ui/field_type/edit/relation_base.html.twig
  src/bundle/Resources/views/themes/admin/ui/tag.html.twig
  src/bundle/ui-dev/src/modules/universal-discovery/universal.discovery.module.js
  src/lib/FieldType/Mapper/RelationFormMapper.php
  src/lib/FieldType/Mapper/RelationListFormMapper.php
  src/lib/UniversalDiscovery/Event/Subscriber/ObjectRelationStartingLocationId.php
  src/lib/UniversalDiscovery/UniversalDiscoveryProvider.php
Labels: Doc needed, QA approved

#484 IBX-3132: Added possibility to change clear button type in inputs
  src/bundle/Resources/public/js/scripts/admin.input.text.js
  src/bundle/Resources/views/themes/admin/ui/component/input_text.html.twig
  src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
Labels: QA approved

#483 [Behat] Improved stability of selecting Richtext style
  src/lib/Behat/Component/Fields/RichText.php
Labels: Ready for review

#489 IBX-3243: don't trigger change on same option select; trigger change on clearCurrentSelection
  src/bundle/Resources/public/js/scripts/core/dropdown.js
Labels: QA approved, Ready for MERGE

#490 IBX-3251: Changed textarea to search type in url wildcards
  src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
  src/lib/Form/Type/URLWildcard/URLWildcardListType.php
Labels: Bug, QA approved, Ready for MERGE

#469 IBX-2779: Unify ghost dropdown caret icon
  src/bundle/Resources/public/scss/_dropdown.scss
Labels: QA approved

#494 IBX-3090: Added possibility to add extra classes to tag in page title
  src/bundle/Resources/public/scss/_page-title.scss
  src/bundle/Resources/views/themes/admin/ui/page_title.html.twig
Labels: Improvement, Ready for review

#499 IBX-3358: Set font white color for :focus primary button
  src/bundle/Resources/public/scss/_buttons.scss
Labels: Bug, QA approved

#497 IBX-3324: Fixed font size and color of description in header
  src/bundle/Resources/public/scss/_icon-tag.scss
  src/bundle/Resources/views/themes/admin/content/location_view.html.twig
Labels: Bug, QA approved

#512 IBX-3393: Remove checkmark icon form multiple dropdown
  src/bundle/Resources/views/themes/admin/ui/component/dropdown/dropdown_item.html.twig
Labels: Bug, QA approved, Ready for MERGE

#510 IBX-3375: Fixed margin and padding for section header
  src/bundle/Resources/public/scss/_field-group.scss
Labels: Bug, QA approved, Ready for MERGE

#493 IBX-3305: Add register page
  src/bundle/Resources/config/ezplatform_default_settings.yaml
  src/bundle/Resources/public/js/scripts/admin.input.text.js
  src/bundle/Resources/public/js/scripts/login.js
  src/bundle/Resources/public/scss/_forms.scss
  src/bundle/Resources/public/scss/_inputs.scss
  src/bundle/Resources/public/scss/_login.scss
  src/bundle/Resources/translations/messages.en.xliff
  src/bundle/Resources/views/themes/admin/account/change_password/form_fields.html.twig
  src/bundle/Resources/views/themes/admin/account/form_fields.html.twig
  src/bundle/Resources/views/themes/admin/account/login/index.html.twig
  src/bundle/Resources/views/themes/admin/account/register/index.html.twig
  src/bundle/Resources/views/themes/admin/account/register/register_confirmation.html.twig
  src/bundle/Resources/views/themes/admin/content/form_fields.html.twig
  src/bundle/Resources/views/themes/admin/ui/component/input_text.html.twig
  src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
Labels: Doc needed

#509 IBX-3388: Updated language details according to invsion project
  src/bundle/Resources/views/themes/admin/language/index.html.twig
  src/lib/Behat/Page/LanguagePage.php
Labels: Bug, Ready for QA

#517 [Behat] IBX-3048 Added tests for catalogs
  src/lib/Behat/Component/Dialog.php
  src/lib/Behat/Component/Table/TableRow.php
Labels: Ready for MERGE

#508 IBX-3386: Fixed styles for schedule hiding menu
  src/bundle/Resources/public/scss/_date-time-picker.scss
  src/bundle/Resources/views/themes/admin/ui/component/inputs/input_date_time_picker.html.twig
Labels: Bug, QA approved, Ready for MERGE

#518 IBX-3424: Added disabled state if only default group is added in cont…
  src/bundle/Resources/views/themes/admin/content_type/field_definitions.html.twig
Labels: QA approved, Ready for MERGE

#507 IBX-3381: languages list screen update
  features/standard/Languages.feature
  src/bundle/Resources/public/scss/_tables.scss
  src/bundle/Resources/translations/language.en.xliff
  src/bundle/Resources/views/themes/admin/language/list.html.twig
  src/bundle/Resources/views/themes/admin/ui/component/table/table_body_cell.html.twig
  src/bundle/Resources/views/themes/admin/ui/component/table/table_body_row.html.twig
  src/bundle/Resources/views/themes/admin/ui/component/table/table_head_cell.html.twig
  src/bundle/Resources/views/themes/admin/ui/component/table/table_head_row.html.twig
  src/lib/Behat/BrowserContext/LanguageContext.php
  src/lib/Behat/Page/LanguagesPage.php
Labels: Bug, Ready for QA

#495 IBX-3218: Fix user password validation, small css fixes etc
  src/bundle/Resources/public/js/scripts/button.trigger.js
  src/bundle/Resources/public/js/scripts/user_password.change.js
  src/bundle/Resources/public/scss/fieldType/edit/_base-field.scss
Labels: QA approved, Ready for MERGE

#521 IBX-3344: Improvement of mark icon for dropdown
  src/bundle/Resources/public/scss/_dropdown.scss
  src/bundle/Resources/public/scss/ui/modules/common/_simple.dropdown.scss
  src/bundle/Resources/views/themes/admin/ui/component/dropdown/dropdown_item.html.twig
  src/bundle/ui-dev/src/modules/common/simple-dropdown/simple.dropdown.js
Labels: Improvement, Ready for QA
