Repository ibexa/admin-ui, pull requests merged in 2022-04, with the labels that each got.

#380 IBX-2020: Fixed error message
  src/bundle/Resources/public/js/scripts/fieldType/ezbinaryfile.js
  src/bundle/Resources/public/js/scripts/fieldType/ezimage.js
  src/bundle/Resources/public/js/scripts/fieldType/ezimageasset.js
  src/bundle/Resources/public/js/scripts/fieldType/ezmedia.js
Labels: Bug, QA approved

#400 IBX-2735: cannot add tag
  src/bundle/Resources/views/themes/admin/ui/component/tag_view_select/tag_view_select_selected_item_tag.html.twig
Labels: Bug, QA approved, Ready for review

#398 IBX-2746: Page builder - double scroll in block settings panel
  src/bundle/Resources/views/themes/admin/ui/layout.html.twig
Labels: Bug, QA approved, Ready for review

#399 [Behat] Narrowed down ContentTypePicker selector
  src/lib/Behat/Component/ContentTypePicker.php
Labels: Ready for review

#403 Merge IBX-2275: Refactor UDW configuration subscribers
  src/lib/UniversalDiscovery/Event/ConfigResolveEvent.php
  src/lib/UniversalDiscovery/Event/Subscriber/ContentCreate.php
  src/lib/UniversalDiscovery/Event/Subscriber/ReadAllowedContentTypes.php
  tests/lib/UniversalDiscovery/Event/Subscriber/ContentCreateTest.php
  tests/lib/UniversalDiscovery/Event/Subscriber/ReadAllowedContentTypesTest.php
Labels: Ready for MERGE

#382 IBX-2627: dropdown small styling issues
  src/bundle/Resources/public/js/scripts/core/dropdown.js
  src/bundle/Resources/public/scss/_dropdown.scss
Labels: Improvement, QA approved, Ready for MERGE

#367 IBX-2557: Fix badge
  src/bundle/Resources/public/scss/_badges.scss
Labels: QA approved, Ready for MERGE

#405 IBX-2796: reference correct property
  src/bundle/Resources/public/js/scripts/fieldType/ezdate.js
  src/bundle/Resources/public/js/scripts/fieldType/ezdatetime.js
  src/bundle/Resources/public/js/scripts/fieldType/eztime.js
Labels: Bug, QA approved

#383 IBX-2628: Introduce colorful tag-like dropdown
  src/bundle/Resources/public/scss/_dropdown.scss
  src/bundle/Resources/views/themes/admin/ui/component/dropdown/dropdown.html.twig
  src/bundle/Resources/views/themes/admin/ui/form_fields/dropdown_widget.html.twig
Labels: Improvement, QA approved, Ready for review

#404 IBX-2603: Content Tree actions: followup for code standards
  src/bundle/Resources/public/js/scripts/sidebar/btn/location.create.js
  src/bundle/Resources/public/js/scripts/sidebar/extra.actions.js
Labels: QA approved, Ready for MERGE

#410 IBX-2826: Search input should be hidden when less than 5 items are in dropdown
  src/bundle/ui-dev/src/modules/common/dropdown/dropdown.js
Labels: QA approved, Ready for MERGE
