Repository ibexa/admin-ui, pull requests merged in 2022-10, with the labels that each got.

#558 IBX-2667: Added Content Type Meta anchor menu
  src/bundle/Controller/ContentTypeController.php
  src/bundle/DependencyInjection/Configuration/Parser/AdminUiForms.php
  src/bundle/Resources/config/services.yaml
  src/bundle/Resources/config/services/components.yaml
  src/bundle/Resources/config/services/components/content_type/edit.yaml
  src/bundle/Resources/config/services/config.yaml
  src/bundle/Resources/config/services/menu.yaml
  src/bundle/Resources/config/services/modules/field_type_toolbar.yaml
  src/bundle/Resources/config/services/services.yaml
  src/bundle/Resources/public/scss/_anchor-navigation.scss
  src/bundle/Resources/public/scss/_content-type-edit.scss
  src/bundle/Resources/public/scss/_main-container.scss
  src/bundle/Resources/translations/content_type.en.xliff
  src/bundle/Resources/translations/menu.en.xliff
  src/bundle/Resources/translations/messages.en.xliff
  src/bundle/Resources/views/themes/admin/content_type/components/meta_fields.html.twig
  src/bundle/Resources/views/themes/admin/content_type/create.html.twig
  src/bundle/Resources/views/themes/admin/content_type/edit.html.twig
  src/bundle/Resources/views/themes/admin/content_type/edit_base.html.twig
  src/bundle/Resources/views/themes/admin/content_type/field_definition.html.twig
  src/bundle/Resources/views/themes/admin/ui/anchor_navigation_menu.html.twig
  src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
  src/lib/Component/ContentType/ContentTypeEditMetaFieldsComponent.php
  src/lib/Config/AdminUiForms/ContentTypeFieldTypesResolver.php
  src/lib/Config/AdminUiForms/ContentTypeFieldTypesResolverInterface.php
  src/lib/Form/Data/ContentTypeData.php
  src/lib/Form/Data/FieldDefinitionData.php
  src/lib/Form/Data/FormMapper/ContentTypeDraftMapper.php
  src/lib/Form/Processor/ContentType/ContentTypeFormProcessor.php
  src/lib/Form/Type/ContentType/ContentTypeUpdateType.php
  src/lib/Form/Type/ContentType/FieldDefinitionsCollectionType.php
  src/lib/Form/Type/FieldDefinition/FieldDefinitionType.php
  src/lib/Menu/ContentTypeEditAnchorMenuBuilder.php
  src/lib/Menu/Event/ConfigureMenuEvent.php
  src/lib/Service/MetaFieldType/MetaFieldDefinitionService.php
  src/lib/Service/MetaFieldType/MetaFieldDefinitionServiceInterface.php
  src/lib/UI/Module/FieldTypeToolbar/FieldTypeToolbarFactory.php
  tests/lib/Config/AdminUiForms/ContentTypeFieldTypesResolverTest.php
  tests/lib/Form/Data/FormMapper/ContentTypeDraftMapperTest.php
  tests/lib/Form/Processor/ContentTypeFormProcessorTest.php
Labels: Doc needed, Improvement, QA approved

#566 IBX-3799: Change default value for headline_title in table
  src/bundle/Resources/views/themes/admin/ui/component/table/table.html.twig
  src/bundle/Resources/views/themes/admin/ui/component/table/table_header.html.twig
Labels: Bug, QA approved

#562 [Behat] IBX-3479: Added tests for catalog filters
  src/lib/Behat/Page/ContentUpdateItemPage.php
Labels: Ready for review

#593 [Behat] Scrolled to the bottom to avoid "Go to the top" button
  src/lib/Behat/Page/ContentTypeGroupPage.php
Labels: Ready for review

#595 IBX-3981: information on how many selected elements hide some functionalities
  src/bundle/Resources/public/scss/ui/modules/universal-discovery/_selected.locations.scss
  src/bundle/Resources/public/scss/ui/modules/universal-discovery/_tab.scss
Labels: QA approved

#600 IBX-3800: Z-index for inputs actions button
  src/bundle/Resources/public/scss/_inputs.scss
Labels: Bug

#597 IBX-3987: Go to top button overlaps with pagination in subitems list when using grid view
  src/bundle/Resources/public/js/scripts/admin.back.to.top.js
Labels: QA approved

#585 IBX-3937: First button primary- creating/editing/updating forms
  src/bundle/Resources/public/scss/_buttons.scss
  src/bundle/Resources/public/scss/ui/modules/sub-items-list/_main.scss
  src/bundle/Resources/public/scss/ui/modules/sub-items-list/_table.view.item.scss
  src/bundle/Resources/views/themes/admin/object_state/object_state_group/view.html.twig
  src/bundle/Resources/views/themes/admin/object_state/view.html.twig
  src/bundle/Resources/views/themes/admin/ui/menu/context_menu.html.twig
  src/lib/Menu/Admin/ContentType/ContentTypeCreateRightSidebarBuilder.php
  src/lib/Menu/Admin/ContentType/ContentTypeEditRightSidebarBuilder.php
  src/lib/Menu/Admin/ContentType/ContentTypeGroupCreateRightSidebarBuilder.php
  src/lib/Menu/Admin/ContentType/ContentTypeGroupEditRightSidebarBuilder.php
  src/lib/Menu/Admin/Language/LanguageCreateRightSidebarBuilder.php
  src/lib/Menu/Admin/Language/LanguageEditRightSidebarBuilder.php
  src/lib/Menu/Admin/ObjectState/ObjectStateCreateRightSidebarBuilder.php
  src/lib/Menu/Admin/ObjectState/ObjectStateEditRightSidebarBuilder.php
  src/lib/Menu/Admin/ObjectState/ObjectStateGroupCreateRightSidebarBuilder.php
  src/lib/Menu/Admin/ObjectState/ObjectStateGroupEditRightSidebarBuilder.php
  src/lib/Menu/Admin/Role/PolicyCreateRightSidebarBuilder.php
  src/lib/Menu/Admin/Role/RoleAssignmentCreateRightSidebarBuilder.php
  src/lib/Menu/Admin/Role/RoleCreateRightSidebarBuilder.php
  src/lib/Menu/Admin/Role/RoleEditRightSidebarBuilder.php
  src/lib/Menu/ContentRightSidebarBuilder.php
  src/lib/Menu/SectionCreateRightSidebarBuilder.php
  src/lib/Menu/SectionEditRightSidebarBuilder.php
  src/lib/Menu/URLEditRightSidebarBuilder.php
  src/lib/Menu/URLWildcardEditRightSidebarBuilder.php
  src/lib/Menu/UserCreateRightSidebarBuilder.php
  src/lib/Menu/UserEditRightSidebarBuilder.php
  src/lib/Menu/UserSetting/UserSettingUpdateRightSidebarBuilder.php
Labels: QA approved

#588 IBX-3966: Moved UserIdentifier configuration into core
  src/bundle/DependencyInjection/Configuration/Parser/UserIdentifier.php
  src/bundle/IbexaAdminUiBundle.php
Labels: QA approved

#602 IBX-2624: Disabled validation for discard changes
  src/bundle/Resources/public/js/scripts/admin.contenttype.edit.js
  src/bundle/Resources/views/themes/admin/content_type/edit.html.twig
Labels: Bug, QA approved, Ready for MERGE

#605 IBX-4017: Fix meta_fields rendering
  src/bundle/Resources/views/themes/admin/content/components/meta_fields.html.twig
Labels: Bug, QA approved, Ready for MERGE

#594 IBX-3962: Introduced ModifyFieldDefinitionFieldsSubscriber
  src/lib/Form/Type/Extension/EventSubscriber/ModifyFieldDefinitionFieldsSubscriber.php
  src/lib/Form/Type/Extension/ModifyFieldDefinitionsCollectionTypeExtension.php
  tests/lib/Form/Type/Extension/EventSubscriber/ModifyFieldDefinitionFieldsSubscriberTest.php
Labels: Doc needed, Improvement, QA approved

#609 IBX-4048: Restore clear button and calendar icon in date time input
  src/bundle/Resources/public/js/scripts/admin.input.text.js
  src/bundle/Resources/public/js/scripts/core/date.time.picker.js
  src/bundle/Resources/public/scss/_inputs.scss
  src/bundle/Resources/views/themes/admin/ui/component/inputs/input_date_time_picker.html.twig
Labels: Bug

#614 IBX-4060: Added nowrap to badges to avoid breaking line
  src/bundle/Resources/public/scss/_badges.scss
Labels: Bug, QA approved, Ready for MERGE

#610 IBX-2817: Input timeout string casted to float for ibexa:encore:compile command
  src/bundle/Command/CompileAssetsCommand.php
Labels: QA approved, Ready for MERGE

#611 IBX-3884: Missing hovers in Dropdowns - Top Bar UDW
  src/bundle/Resources/public/scss/ui/modules/common/_simple.dropdown.scss
  src/bundle/Resources/public/scss/ui/modules/universal-discovery/_tab.selector.scss
  src/bundle/Resources/public/scss/ui/modules/universal-discovery/_top.menu.search.input.scss
  src/bundle/ui-dev/src/modules/common/simple-dropdown/simple.dropdown.js
Labels: QA approved, Ready for MERGE

#623 IBX-4002: Changed styles to show scroll on the correct element
  src/bundle/Resources/public/scss/_grid-view.scss
  src/bundle/Resources/public/scss/ui/modules/universal-discovery/_grid.scss
  src/bundle/Resources/public/scss/ui/modules/universal-discovery/_main.scss
Labels: Bug, QA approved

#615 IBX-4032: Added limitation to prevent changing content ownership
  src/bundle/Resources/config/services/role_form_mappers.yaml
  src/bundle/Resources/translations/ezplatform_content_forms_policies.en.xliff
  src/bundle/Resources/translations/ibexa_content_forms_policies.en.xliff
  src/bundle/Resources/translations/ibexa_content_forms_role.en.xliff
  src/bundle/Resources/views/themes/admin/limitation/limitation_values.html.twig
  src/lib/Limitation/Mapper/ChangeOwnerLimitationMapper.php
  src/lib/Translation/Extractor/LimitationTranslationExtractor.php
Labels: Doc needed, Ready for QA
