Repository ibexa/admin-ui, pull requests merged in 2022-12, with the labels that each got.

#642 IBX-4277: [UDW] Tooltips from left menu aren't visible
  src/bundle/Resources/public/js/scripts/core/custom.tooltip.js
  src/bundle/Resources/public/js/scripts/helpers/tooltips.helper.js
  src/bundle/ui-dev/src/modules/universal-discovery/components/tab-selector/tab.selector.js
  src/lib/Behat/Component/UniversalDiscoveryWidget.php
Labels: QA approved

#633 IBX-3619: Tag update helper
  src/bundle/Resources/public/js/scripts/helpers/middle.ellipsis.js
  src/bundle/Resources/public/scss/_tag.scss
  src/bundle/Resources/views/themes/admin/ui/tag.html.twig
Labels: QA approved

#655 [Behat] Stability fixes
  src/lib/Behat/Component/Fields/User.php
  src/lib/Behat/Component/UniversalDiscoveryWidget.php
Labels: Ready for review

#660 IBX-4439: fixed tooltip title change after expand & collapse
  src/bundle/ui-dev/src/modules/universal-discovery/components/selected-locations/selected.locations.js
Labels: QA approved, Ready for MERGE

#663 Fix tests
  src/lib/Behat/Component/Fields/User.php
  src/lib/Behat/Component/UniversalDiscoveryWidget.php
Labels: Ready for review

#661 IBX-3792: Fixed display meta tab
  src/bundle/Resources/public/js/scripts/admin.anchor.navigation.js
  src/bundle/Resources/views/themes/admin/ui/on_the_fly/create_on_the_fly.html.twig
  src/bundle/Resources/views/themes/admin/ui/on_the_fly/edit_on_the_fly.html.twig
Labels: Bug, QA approved

#664 [Behat] IBX-4409: Implemented test scenarios for Currencies
  src/lib/Behat/Component/Table/TableRow.php
Labels: Ready for review

#662 IBX-4452: Deprecated Policy and Limitation TranslationExtractors
  composer.json
  src/bundle/Resources/config/services/translation.yaml
  src/bundle/Resources/translations/forms.en.xliff
  src/lib/Form/Type/Policy/PolicyChoiceType.php
  src/lib/Limitation/Mapper/ChangeOwnerLimitationMapper.php
  src/lib/Limitation/Mapper/MultipleSelectionBasedMapper.php
  src/lib/Limitation/Mapper/UDWBasedMapper.php
  src/lib/Limitation/Mapper/UserPermissionsLimitationMapper.php
  src/lib/Translation/Extractor/LimitationTranslationExtractor.php
  src/lib/Translation/Extractor/PolicyTranslationExtractor.php
Labels: Improvement, Ready for review
