Repository ibexa/admin-ui, pull requests merged in 2022-03, with the labels that each got.

#319 IBX-2277: [Taxonomy] As a user, I want to change language context in Taxonomy Tree
  src/bundle/Resources/encore/ibexa.js.config.js
  src/bundle/Resources/public/js/scripts/core/dropdown.js
  src/bundle/Resources/public/js/scripts/helpers/object.instances.js
  src/bundle/Resources/public/scss/_modals.scss
  src/bundle/ui-dev/src/modules/common/dropdown/dropdown.js
Labels: QA approved, Ready for MERGE

#344 Rebrand behatbundle
  behat_suites.yml
  composer.json
  features/standard/ContentTypeFields.feature
  src/bundle/DependencyInjection/IbexaAdminUiExtension.php
  src/lib/Behat/BrowserContext/ContentViewContext.php
  src/lib/Behat/BrowserContext/NavigationContext.php
  src/lib/Behat/BrowserContext/NotificationContext.php
  src/lib/Behat/BrowserContext/UDWContext.php
  src/lib/Behat/Page/ContentViewPage.php
Labels: Ready for review

#343 IBX-2380: Layout of Section page need to be updated
  src/bundle/Resources/public/scss/_admin.section-view.scss
  src/bundle/Resources/views/themes/admin/section/assigned_content.html.twig
  src/bundle/Resources/views/themes/admin/section/view.html.twig
  src/lib/Behat/Page/SectionPage.php
Labels: Bug, QA approved

#345 IBX-2064: Rename label Back to Close in editing and creating
  src/bundle/Resources/public/scss/_anchor-navigation.scss
  src/bundle/Resources/translations/messages.en.xliff
  src/bundle/Resources/translations/universal_discovery_widget.en.xliff
  src/bundle/Resources/views/themes/admin/ui/anchor_navigation_menu.html.twig
  src/bundle/ui-dev/src/modules/universal-discovery/components/top-menu/top.menu.js
  src/bundle/ui-dev/src/modules/universal-discovery/content.create.tab.module.js
  src/bundle/ui-dev/src/modules/universal-discovery/content.edit.tab.module.js
  src/lib/Behat/Page/ContentUpdateItemPage.php
Labels: Bug, QA approved, Ready for MERGE

#346 IBX-2454: Content Type/Product Type page should be scrolled down to invalid fields
  src/bundle/Resources/public/js/scripts/admin.contenttype.edit.js
Labels: Improvement, QA approved

#348 IBX-2177: Page builder - Error state on icon
  src/bundle/Resources/public/js/scripts/fieldType/base/base-field.js
Labels: Bug, QA approved, Ready for MERGE

#351 IBX-2450: Object state group view design improvements
  features/standard/ObjectStates.feature
  src/bundle/Resources/public/scss/_object-state-group-view.scss
  src/bundle/Resources/public/scss/ibexa.scss
  src/bundle/Resources/translations/object_state.en.xliff
  src/bundle/Resources/views/themes/admin/object_state/list.html.twig
  src/bundle/Resources/views/themes/admin/object_state/object_state_group/view.html.twig
  src/bundle/Resources/views/themes/admin/object_state/view.html.twig
  src/lib/Behat/Page/ObjectStateGroupPage.php
  src/lib/Behat/Page/ObjectStatePage.php
Labels: QA approved, Ready for MERGE

#352 IBX-2494: No icon with custom content type in location view
  src/bundle/Resources/views/themes/admin/content/location_view.html.twig
Labels: QA approved

#350 IBX-2412: Improve checkbox styling
  src/bundle/Resources/public/scss/_inputs.scss
  src/bundle/Resources/public/scss/_tables.scss
Labels: QA approved, Ready for MERGE

#359 IBX-2427: Reschedule modal - calendar popup is not fully visible
  src/bundle/Resources/public/scss/mixins/_modals.scss
Labels: QA approved

#356 Autogenerate value for attribut selection
  src/bundle/Resources/encore/ibexa.js.config.js
  src/bundle/Resources/public/js/scripts/autogenerate.identifier.js
  src/bundle/Resources/public/js/scripts/core/slug.value.input.autogenerator.js
Labels: Improvement, QA approved

#358 IBX-2415: Fix bell icon alignment in the header
  src/bundle/Resources/public/scss/_header-user-menu.scss
Labels: QA approved, Ready for review

#361 IBX-2520: Fix action buttons from the header overlapping with other things before adaptive items is initialized
  src/bundle/Resources/public/js/scripts/admin.context.menu.js
  src/bundle/Resources/public/scss/_context-menu.scss
  src/bundle/Resources/public/scss/_header.scss
  src/bundle/Resources/views/themes/admin/ui/component/context_menu/context_menu.html.twig
Labels: QA approved, Ready for review

#364 IBX-2529: Unnecessary subtitle in Notifications popup
  src/bundle/Resources/views/themes/admin/account/notifications/modal.html.twig
Labels: Bug, QA approved, Ready for MERGE

#349 Add #[\ReturnTypeWillChange] to disable PHP 8.1 deprecation warnings
  src/lib/UI/Config/ConfigWrapper.php
Labels: QA approved

#365 IBX-2540: MFU - changing window width triggers file upload
  src/bundle/ui-dev/src/modules/multi-file-upload/components/drop-area/drop.area.component.js
  src/bundle/ui-dev/src/modules/multi-file-upload/components/upload-list/upload.list.component.js
  src/bundle/ui-dev/src/modules/multi-file-upload/components/upload-popup/upload.popup.component.js
  src/bundle/ui-dev/src/modules/multi-file-upload/multi.file.upload.module.js
Labels: QA approved

#353 Menu on small screen
  src/bundle/Resources/public/js/scripts/core/adaptive.items.js
  src/bundle/Resources/public/js/scripts/sidebar/main.menu.js
  src/bundle/Resources/public/scss/_main-menu.scss
  src/bundle/Resources/public/scss/_popup-menu.scss
  src/bundle/Resources/views/themes/admin/ui/menu/first_level_popup_menu_item.html.twig
  src/bundle/Resources/views/themes/admin/ui/menu/main.html.twig
  src/bundle/Resources/views/themes/admin/ui/menu/main_base.html.twig
  src/lib/Menu/MainMenuBuilder.php
Labels: Bug, Ready for QA

#371 [Behat] Increased go to the top timeout
  src/lib/Behat/Component/Pagination.php
Labels: Ready for review

#297 IBX-1339: DateTime Widget
  src/bundle/Resources/encore/ibexa.js.config.js
  src/bundle/Resources/public/js/scripts/admin.input.text.js
  src/bundle/Resources/public/js/scripts/admin.picker.js
  src/bundle/Resources/public/js/scripts/admin.search.filters.js
  src/bundle/Resources/public/js/scripts/admin.trash.list.js
  src/bundle/Resources/public/js/scripts/core/date.time.picker.js
  src/bundle/Resources/public/js/scripts/fieldType/ezdate.js
  src/bundle/Resources/public/js/scripts/fieldType/ezdatetime.js
  src/bundle/Resources/public/js/scripts/fieldType/eztime.js
  src/bundle/Resources/public/scss/_date-time-picker.scss
  src/bundle/Resources/public/scss/_inputs.scss
  src/bundle/Resources/public/scss/ibexa.scss
  src/bundle/Resources/views/themes/admin/ui/component/input_text.html.twig
  src/bundle/Resources/views/themes/admin/ui/component/inputs/input_date_time_picker.html.twig
  src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezdate.html.twig
  src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezdatetime.html.twig
  src/bundle/Resources/views/themes/admin/ui/field_type/edit/eztime.html.twig
  src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
Labels: QA approved, Ready for MERGE

#368 IBX-2565: Main menu - text outside popup when too long
  src/bundle/Resources/public/scss/_main-menu.scss
Labels: Bug, QA approved

#372 [WiP][Behat] IBX-1313 Added selection of editor launch mode in content type
  src/lib/Behat/BrowserContext/ContentTypeContext.php
  src/lib/Behat/Page/ContentTypeUpdatePage.php
Labels: Ready for review

#373 IBX-2591: Main menu - list button from 2nd stage not opening
  src/bundle/Resources/public/scss/_main-menu.scss
Labels: Bug, QA approved

#384 IBX-2459: Fixed error when selecting bookmarked content in UDW
  src/bundle/ui-dev/src/modules/universal-discovery/services/universal.discovery.service.js
Labels: QA approved

#366 IBX-1593: View switcher
  src/bundle/Resources/public/js/scripts/core/dropdown.js
  src/bundle/Resources/public/scss/_dropdown.scss
  src/bundle/Resources/public/scss/ui/modules/_common.scss
  src/bundle/Resources/public/scss/ui/modules/_universal.discovery.scss
  src/bundle/Resources/public/scss/ui/modules/common/_simple.dropdown.scss
  src/bundle/Resources/public/scss/ui/modules/universal-discovery/_view.switcher.scss
  src/bundle/Resources/translations/messages.en.xliff
  src/bundle/Resources/translations/section.en.xliff
  src/bundle/Resources/translations/sub_items.en.xliff
  src/bundle/Resources/translations/universal_discovery_widget.en.xliff
  src/bundle/Resources/views/themes/admin/section/view.html.twig
  src/bundle/Resources/views/themes/admin/ui/component/dropdown/dropdown.html.twig
  src/bundle/Resources/views/themes/admin/ui/component/dropdown/dropdown_item.html.twig
  src/bundle/Resources/views/themes/admin/ui/component/dropdown/dropdown_selected_item.html.twig
  src/bundle/Resources/views/themes/admin/ui/component/dropdown/dropdown_selected_item_icon.html.twig
  src/bundle/ui-dev/src/modules/common/simple-dropdown/simple.dropdown.js
  src/bundle/ui-dev/src/modules/sub-items/components/view-switcher/view.switcher.component.js
  src/bundle/ui-dev/src/modules/universal-discovery/components/simple-dropdown/simple.dropdown.js
  src/bundle/ui-dev/src/modules/universal-discovery/components/sort-switcher/sort.switcher.js
  src/bundle/ui-dev/src/modules/universal-discovery/components/view-switcher/view.switcher.js
  src/bundle/ui-dev/src/modules/universal-discovery/universal.discovery.module.js
Labels: Improvement, QA approved, Ready for MERGE
