Repository ibexa/admin-ui, pull requests merged in 2022-06, with the labels that each got.

#452 [Behat] Restore deleted ElementTextCriterion
  src/lib/Behat/Page/ContentUpdateItemPage.php
Labels: Ready for review

#434 IBX-2940: Introduced middle ellipsis component
  src/bundle/Resources/encore/ibexa.js.config.js
  src/bundle/Resources/public/js/scripts/admin.middle.ellipsis.js
  src/bundle/Resources/public/js/scripts/core/tag.view.select.js
  src/bundle/Resources/public/js/scripts/helpers/middle.ellipsis.js
  src/bundle/Resources/public/scss/_middle-ellipsis.scss
  src/bundle/Resources/public/scss/_tag-view-select.scss
  src/bundle/Resources/public/scss/_tag.scss
  src/bundle/Resources/public/scss/ibexa.scss
  src/bundle/Resources/views/themes/admin/ui/component/middle_ellipsis/middle_ellipsis.html.twig
  src/bundle/Resources/views/themes/admin/ui/component/tag_view_select/tag_view_select_selected_item_tag.html.twig
  src/bundle/Resources/views/themes/admin/ui/tag.html.twig
Labels: QA approved

#437 IBX-2943: Section is not fully switched when editing content with multiple sections
  src/bundle/Resources/public/js/scripts/admin.anchor.navigation.js
  src/bundle/Resources/public/js/scripts/admin.content.edit.js
Labels: QA approved, Ready for MERGE

#458 Fixed dart-sass failing in compiling by encore
  src/bundle/Resources/public/scss/_custom.scss
Labels: Bug

#459 Fixed dart-sass failing in compiling by encore
  src/bundle/Resources/public/scss/_custom.scss
Labels: Bug

#464 IBX-2965: Added min-height to header title
  src/bundle/Resources/public/scss/_edit-header.scss
Labels: QA approved, Ready for MERGE

#465 IBX-2913: Changed type of filter button in fieldtypes widget
  src/bundle/Resources/views/themes/admin/ui/component/input_text.html.twig
Labels: QA approved, Ready for MERGE

#460 IBX-2924: [Content types] An exception occurred when user replace position of field 'Content query' in content field definition section.
  src/bundle/Resources/public/js/scripts/admin.contenttype.edit.js
Labels: QA approved, Ready for MERGE

#466 IBX-3007: [Content Tree] As a user, I want to have warning modal about hiding content with reverse relations
  src/bundle/Resources/views/themes/admin/content/modal/hide_confirmation.html.twig
Labels: QA approved, Ready for MERGE

#468 IBX-2996: Hide group if all items are hidden in dropdown
  src/bundle/Resources/public/js/scripts/core/dropdown.js
  src/bundle/Resources/public/scss/_dropdown.scss
Labels: QA approved, Ready for MERGE

#428 IBX-2912: Placeholder in D&D blinks when user doesn't move mouse
  src/bundle/Resources/public/js/scripts/admin.contenttype.edit.js
  src/bundle/Resources/public/js/scripts/core/draggable.js
Labels: QA approved, Ready for MERGE

#471 IBX-2961: Refactored Extension to rely on Encore Configuration Dumper
  composer.json
  src/bundle/DependencyInjection/IbexaAdminUiExtension.php
Labels: Doc needed, Improvement, QA approved, Ready for MERGE

#474 IBX-2821: Fixed icon background in read notification
  src/bundle/Resources/public/scss/mixins/_type-icon.scss
Labels: QA approved, Ready for MERGE

#475 IBX-3070: User thumbnail should not be rendered with border and other minor bugs
  src/bundle/Resources/public/scss/_header-user-menu.scss
  src/bundle/Resources/views/themes/admin/ui/menu/user.html.twig
Labels: QA approved
