Repository ibexa/admin-ui, pull requests merged in 2022-01, with the labels that each got.

#158 Merge IBX-1799: Added new UDW configuration for Subtree filter
  src/bundle/Resources/config/universal_discovery_widget.yaml
  src/bundle/Resources/views/themes/admin/ui/search/filters.html.twig
  src/lib/UniversalDiscovery/Event/ConfigResolveEvent.php
Labels: Ready for MERGE

#148 IBX-1588: add location helper; fix ibexa-input--checkbox input, ibexa-tag
  src/bundle/Resources/encore/ibexa.js.config.js
  src/bundle/Resources/public/js/scripts/helpers/location.helper.js
  src/bundle/Resources/public/scss/_inputs.scss
  src/bundle/Resources/public/scss/_tag.scss
Labels: Doc needed

#157 IBX-1772: Passed created content draft to ContentProxyCreateEvent context
  src/contracts/Event/ContentProxyCreateEvent.php
  src/lib/Event/Options.php
  src/lib/EventListener/ContentProxyCreateDraftListener.php
  tests/lib/EventListener/ContentProxyCreateDraftListenerTest.php
Labels: Improvement, Ready for review

#164 IBX-1776: Removed "Change password" item from user menu
  features/personas/ChangePassword.feature
  src/bundle/Resources/translations/menu.en.xliff
  src/lib/Behat/BrowserContext/NavigationContext.php
  src/lib/Behat/Page/ChangePasswordPage.php
  src/lib/EventListener/UserMenuListener.php
Labels: Doc needed

#169 IBX-1765: Added customize label on/off for toggle widget
  src/bundle/Resources/views/themes/admin/ui/form_fields/toggle_widget.html.twig
Labels: Feature, Ready for review

#170 IBX-1526: change edit fields width to full column; Page Builder updates
  src/bundle/Resources/public/scss/_buttons.scss
  src/bundle/Resources/public/scss/_edit-header.scss
  src/bundle/Resources/public/scss/_inputs.scss
  src/bundle/Resources/public/scss/fieldType/edit/_base-preview.scss
  src/bundle/Resources/public/scss/fieldType/edit/_ezcountry.scss
  src/bundle/Resources/public/scss/fieldType/edit/_ezemail.scss
  src/bundle/Resources/public/scss/fieldType/edit/_ezfloat.scss
  src/bundle/Resources/public/scss/fieldType/edit/_ezgmaplocation.scss
  src/bundle/Resources/public/scss/fieldType/edit/_ezstring.scss
  src/bundle/Resources/public/scss/ibexa.scss
  src/bundle/Resources/public/scss/ui/modules/universal-discovery/_content.meta.preview.scss
  src/bundle/Resources/views/themes/admin/content/edit_base.html.twig
  src/bundle/ui-dev/src/modules/common/popup/popup.component.js
Labels: Improvement

#193 IBX-1956: Detect username/password automatic autofill on login page
  src/bundle/Resources/public/js/scripts/login.js
Labels: Bug

#251 IBX-1696: Removed class parameters from ibexa/admin-ui repository
  src/bundle/Resources/config/services/role_form_mappers.yaml
  src/bundle/Resources/config/services/views.yaml
Labels: Improvement, Ready for review

#273 IBX-2139: Reverted event name change
  src/bundle/Controller/ContentOnTheFlyController.php
  src/bundle/Resources/views/themes/admin/ui/on_the_fly/create_on_the_fly.html.twig
  src/contracts/Event/ContentOnTheFlyEvents.php
  src/contracts/Event/UserOnTheFlyEvents.php
  src/lib/Form/Processor/User/UserOnTheFlyProcessor.php
  src/lib/View/ContentTranslateSuccessView.php
Labels: QA approved
