Repository ibexa/admin-ui, pull requests merged in 2022-09, with the labels that each got.

#554 IBX-3716: Updated design of the selection field on the content preview screen
  src/bundle/Resources/public/scss/fieldType/preview/_ezselection.scss
  src/bundle/Resources/views/themes/admin/ui/field_type/preview/content_fields.html.twig
Labels: Bug, QA approved

#556 IBX-3408: Added notice to table
  src/bundle/Resources/public/scss/_tables.scss
  src/bundle/Resources/translations/content_type.en.xliff
  src/bundle/Resources/translations/section.en.xliff
  src/bundle/Resources/views/themes/admin/content_type/content_type_group/list.html.twig
  src/bundle/Resources/views/themes/admin/content_type/list.html.twig
  src/bundle/Resources/views/themes/admin/section/list.html.twig
  src/bundle/Resources/views/themes/admin/ui/component/table/table.html.twig
  src/bundle/Resources/views/themes/admin/ui/component/table/table_header.html.twig
  src/lib/Behat/Page/ContentTypeGroupPage.php
  src/lib/Behat/Page/ContentTypeGroupsPage.php
Labels: Improvement, QA approved

#560 IBX-3561: Removed readonly state for flatpickr inputs
  src/bundle/Resources/public/scss/_forms.scss
Labels: QA approved, Ready for MERGE

#559 IBX-3761: Fixed toast notification text
  src/bundle/Resources/views/themes/admin/ui/component/alert/alert.html.twig
Labels: QA approved, Ready for MERGE

#564 [Behat] Added small waiting before adding new Content Type fields
  src/lib/Behat/Page/ContentTypeUpdatePage.php
Labels: Ready for review

#565 Fixed microcopy notice for Content Type Group and Groups
  src/bundle/Resources/translations/content_type.en.xliff
  src/bundle/Resources/views/themes/admin/content_type/content_type_group/list.html.twig
  src/bundle/Resources/views/themes/admin/content_type/list.html.twig
Labels: QA approved

#568 Hotfix for `content.create.widget.js`
  src/bundle/ui-dev/src/modules/universal-discovery/components/content-create-widget/content.create.widget.js
Labels: Bug, Ready for review

#542 IBX-3654: Left menu and sections in edit form cleanup
  src/bundle/Resources/encore/ibexa.js.config.js
  src/bundle/Resources/public/js/scripts/admin.anchor.navigation.js
  src/bundle/Resources/public/js/scripts/admin.anchor.sections.navigation.js
  src/bundle/Resources/public/scss/_anchor-navigation.scss
  src/bundle/Resources/public/scss/_content-edit.scss
  src/bundle/Resources/public/scss/_main-container.scss
  src/bundle/Resources/public/scss/_navigation-menu.scss
  src/bundle/Resources/public/scss/ibexa.scss
  src/bundle/Resources/views/themes/admin/content/components/meta_fields.html.twig
  src/bundle/Resources/views/themes/admin/content/edit_base.html.twig
  src/bundle/Resources/views/themes/admin/ui/anchor_navigation_menu.html.twig
  src/bundle/Resources/views/themes/admin/ui/anchor_navigation_section.html.twig
  src/bundle/Resources/views/themes/admin/ui/component/anchor_navigation/section.html.twig
  src/bundle/Resources/views/themes/admin/ui/component/anchor_navigation/section_group.html.twig
  src/bundle/Resources/views/themes/admin/ui/component/dropdown/dropdown.html.twig
  src/bundle/Resources/views/themes/admin/ui/component/dropdown/dropdown_item.html.twig
  src/bundle/Resources/views/themes/admin/ui/edit_section.html.twig
  src/bundle/Resources/views/themes/admin/ui/menu/anchor_menu.html.twig
  src/bundle/Resources/views/themes/admin/user/role_assignment/create.html.twig
  src/lib/Behat/Page/AdminUpdateItemPage.php
  src/lib/Behat/Page/ContentUpdateItemPage.php
Labels: QA approved, Ready for MERGE

#576 [Behat] Fixed UDW bookmarks editing
  src/lib/Behat/Component/UniversalDiscoveryWidget.php
Labels: Ready for review

#575 IBX-3833: Fixed helper text labels in the table headers
  src/bundle/Resources/translations/section.en.xliff
  src/bundle/Resources/views/themes/admin/section/list.html.twig
Labels: Bug, QA approved

#578 IBX-3869: set more precise seletor for ibexa-btn
  src/bundle/Resources/public/scss/_buttons.scss
Labels: Bug, QA approved

#579 IBX-3873: Create/edit content - unnecessary content switcher on left menu
  src/bundle/Resources/views/themes/admin/ui/menu/anchor_menu.html.twig
Labels: QA approved

#571 Version comparison 4.2
  src/lib/Behat/Component/Fields/Matrix.php
  src/lib/Behat/Component/IbexaDropdown.php
Labels: Ready for review
