Repository ibexa/admin-ui, pull requests merged in 2023-02, with the labels that each got.

#687 IBX-4925: Udw fetched version if fast clicked button
  src/bundle/ui-dev/src/modules/universal-discovery/universal.discovery.module.js
Labels: QA approved

#670 IBX-4327: Content airtime settings modal design
  src/bundle/Resources/encore/ibexa.css.config.js
  src/bundle/Resources/public/scss/_flatpickr.scss
Labels: QA approved, Ready for MERGE

#679 IBX-4678: Unnecessary remove icon in enabled state of inputs- Article content form
  src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
Labels: QA approved

#688 IBX-4972: Middle elippsis fixed container class checked
  src/bundle/Resources/public/js/scripts/helpers/middle.ellipsis.js
Labels: QA approved

#680 IBX-4629: Implement Meta field groups
  src/bundle/DependencyInjection/Configuration/Parser/AdminUiForms.php
  src/bundle/Resources/config/admin_ui_forms.yaml
  src/bundle/Resources/views/themes/admin/content/components/meta_fields.html.twig
  src/lib/Behat/BrowserContext/ContentUpdateContext.php
  src/lib/Behat/Page/ContentUpdateItemPage.php
  src/lib/Component/Content/ContentEditMetaFieldsComponent.php
  src/lib/EventListener/SetViewParametersListener.php
  src/lib/Form/Provider/GroupedNonMetaFormFieldsProvider.php
  src/lib/Menu/ContentEditAnchorMenuBuilder.php
  tests/bundle/DependencyInjection/Configuration/Parser/AdminUiFormsTest.php
  tests/lib/EventListener/SetViewParametersListenerTest.php
Labels: Doc needed, Feature, QA approved

#690 IBX-4913: Blank space cannot be added to product collection search
  src/bundle/Resources/public/js/scripts/admin.input.text.js
Labels: QA approved

#696 [Behat] Increased timeout when searching for subitem headers
  src/lib/Behat/Component/SubItemsList.php
Labels: Ready for review

#691 IBX-4922: [Product type] Missing translation for validation message for identifier field and notification message
  src/bundle/Resources/translations/ezplatform_content_forms_policies.en.xliff
  src/bundle/Resources/translations/validators.en.xliff
  src/lib/Validator/Constraints/UniqueContentTypeIdentifier.php
  src/lib/Validator/Constraints/UniqueFieldDefinitionIdentifier.php
Labels: QA approved, Ready for MERGE

#692 IBX-4937: Content Tree has CSS issues when loading plenty of children under a node
  src/bundle/Resources/public/scss/ui/modules/content-tree/_list.item.scss
Labels: QA approved

#694 IBX-5013: Removed mergin from header in objectrelation fieldtype
  src/bundle/Resources/public/scss/fieldType/edit/_ezobjectrelationlist.scss
Labels: QA approved

#693 IBX-4993 changed content_fields.html.twig to display table header for single/multiple relation in preview
  src/bundle/Resources/views/themes/admin/ui/field_type/preview/content_fields.html.twig
Labels: QA approved, Ready for MERGE

#702 IBX-4386: Removed argument binding to prevent breaking external libraries
  src/bundle/Resources/config/services/events.yaml
Labels: Ready for review

#678 IBX-4791: [Date picker] Cannot open date time picker by clicking on calendar icon in the input
  src/bundle/Resources/public/js/scripts/core/date.time.picker.js
  src/bundle/Resources/public/scss/_date-time-picker.scss
  src/bundle/Resources/views/themes/admin/ui/component/inputs/input_date_time_picker.html.twig
Labels: QA approved, Ready for MERGE

#689 [Behat] Removed code reliant on MutationObserver changes
  src/lib/Behat/Component/UniversalDiscoveryWidget.php
Labels: Ready for review

#658 IBX-4339: Input validation - wrong style
  src/bundle/Resources/encore/ibexa.js.config.js
  src/bundle/Resources/public/js/scripts/admin.contenttype.edit.js
  src/bundle/Resources/public/js/scripts/admin.form.error.js
  src/bundle/Resources/public/js/scripts/fieldType/base/base-field.js
  src/bundle/Resources/public/js/scripts/fieldType/ezimage.js
  src/bundle/Resources/public/js/scripts/helpers/form.error.helper.js
  src/bundle/Resources/public/js/scripts/user_password.change.js
  src/bundle/Resources/public/scss/_forms.scss
  src/bundle/Resources/public/scss/mixins/_inputs.scss
  src/bundle/Resources/views/themes/admin/account/change_password/form_fields.html.twig
  src/bundle/Resources/views/themes/admin/content/form_fields.html.twig
  src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezimage.html.twig
  src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
  src/bundle/Resources/views/themes/admin/user/invitation/issue_email_empty.html.twig
  src/bundle/Resources/views/themes/admin/user/invitation/issue_email_not_valid.html.twig
  src/bundle/Resources/views/themes/admin/user/invitation/modal_entry.html.twig
  src/lib/Behat/Page/AdminUpdateItemPage.php
Labels: QA approved, Ready for MERGE

#700 IBX-5017: Select all checkbox in Relation List is inconsistent
  src/bundle/Resources/public/js/scripts/admin.table.js
  src/bundle/Resources/public/js/scripts/fieldType/ezobjectrelationlist.js
Labels: QA approved

#706 IBX-4343: PB timeline grey backdrop
  src/bundle/Resources/public/scss/_backdrop.scss
Labels: QA approved

#710 IBX-4887: Content type group with space or '/' causes js an error in the BackOffice search
  src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
Labels: QA approved
