Repository ibexa/admin-ui, pull requests merged in 2023-11, with the labels that each got.

#968 Translation test
  .github/workflows/ci.yaml
  composer.json
  phpstan-baseline.neon
  phpunit.integration.xml
  src/bundle/Resources/config/services/components.yaml
  src/bundle/Resources/config/services/events.yaml
  src/bundle/Resources/config/services/form_processors.yaml
  src/bundle/Resources/config/services/tabs.yaml
  src/bundle/Resources/config/services/tabs/content_type.yaml
  src/bundle/Resources/config/services/tabs/locationview.yaml
  src/bundle/Resources/config/services/universal_discovery_widget.yaml
  src/bundle/Resources/config/services/utils.yaml
  src/bundle/Resources/config/services/validators.yaml
  tests/integration/AdminUiIbexaTestKernel.php
  tests/integration/DependencyInjection/Configuration/IgnoredConfigParser.php
  tests/integration/Resources/ibexa.yaml
  tests/integration/TranslationTest.php
  tests/integration/bootstrap.php
Labels: Ready for review

#938 IBX-6725: Autosave notification is in wrong place
  features/standard/Autosave.feature
  src/bundle/Resources/public/js/scripts/admin.content.edit.js
  src/bundle/Resources/public/scss/_autosave.scss
  src/bundle/Resources/public/scss/_context-menu.scss
  src/bundle/Resources/public/scss/_edit-header.scss
  src/bundle/Resources/translations/ibexa_content.en.xliff
  src/bundle/Resources/translations/messages.en.xliff
  src/bundle/Resources/views/themes/admin/content/edit/edit.html.twig
  src/bundle/Resources/views/themes/admin/ui/component/autosave/autosave.html.twig
  src/bundle/Resources/views/themes/admin/ui/edit_header.html.twig
  src/lib/Behat/BrowserContext/ContentUpdateContext.php
  src/lib/Behat/Page/ContentUpdateItemPage.php
Labels: QA approved

#972 [Behat] Removed test tag
  features/standard/ObjectStates.feature
Labels: Ready for review

#953 IBX-6845: Matrix field columns table header not present until saved
  src/bundle/Resources/views/themes/admin/ui/component/table/table.html.twig
Labels: Ready for QA

#960 IBX-6883: [PB] Add tooltips for all buttons in header
  src/bundle/Resources/public/js/scripts/helpers/tooltips.helper.js
Labels: QA approved, Ready for MERGE

#916 Adding condition to display sorting options
  src/bundle/Resources/public/js/scripts/admin.location.view.js
  src/bundle/Resources/views/themes/admin/content/tab/details.html.twig
Labels: Bug, QA approved, Ready for MERGE

#978 IBX-6993: [Fieldtype Matrix] After adding field, "select all checkbox" in table does not work
  src/bundle/Resources/public/js/scripts/admin.table.js
Labels: QA approved, Ready for MERGE

#980 [Behat] Removed hardcoded button positions
  src/lib/Behat/Component/Fields/RichText.php
Labels: Ready for review

#982 IBX-6998: First table row has white background
  src/bundle/Resources/views/themes/admin/ui/component/table/table.html.twig
Labels: QA approved, Ready for MERGE

#969 IBX-6955: Filters in global search are misaligned for long content type name
  src/bundle/Resources/public/scss/_filters.scss
  src/bundle/Resources/public/scss/ui/modules/universal-discovery/_filters.scss
  src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
  src/bundle/ui-dev/src/modules/universal-discovery/components/collapsible/collapsible.js
  src/bundle/ui-dev/src/modules/universal-discovery/components/content-type-selector/content.type.selector.js
Labels: QA approved

#983 Fixed typo in FieldDefinitionCreate Content-Type header
  src/bundle/Resources/config/services/rest.yaml
  src/bundle/Resources/public/js/scripts/admin.contenttype.edit.js
Labels: Improvement, Ready for QA

#981 [Behat] Country field: switch to using Ibexa dropdown
  src/lib/Behat/Component/Fields/Country.php
Labels: Ready for review

#940 IBX-6547: Updated Popup modal
  src/bundle/ui-dev/src/modules/common/popup/popup.component.js
  src/bundle/ui-dev/src/modules/multi-file-upload/components/upload-popup/upload.popup.component.js
  src/bundle/ui-dev/src/modules/sub-items/sub.items.module.js
Labels: QA approved

#970 IBX-6612: [Customer] JS exception occurs while user navigate on content action menu
  src/bundle/Resources/views/themes/admin/content/edit_base.html.twig
  src/bundle/Resources/views/themes/admin/ui/anchor_navigation_menu.html.twig
  src/bundle/Resources/views/themes/admin/ui/anchor_navigation_section.html.twig
Labels: QA approved, Ready for MERGE

#975 IBX-6985: Product code badge at wrong position
  src/bundle/Resources/public/scss/_badges.scss
  src/bundle/Resources/public/scss/_page-title.scss
  src/bundle/Resources/views/themes/admin/ui/page_title.html.twig
Labels: QA approved

#988 IBX-7061: Cannot switching filed groups on create and edit PT form
  src/bundle/Resources/views/themes/admin/content_type/edit_base.html.twig
  src/bundle/Resources/views/themes/admin/ui/edit_section.html.twig
  src/bundle/Resources/views/themes/admin/user/role_assignment/create.html.twig
Labels: QA approved

#943 IBX-6550: Global redesign of placeholder for trees
  src/bundle/Resources/public/scss/mixins/_drag-and-drop.scss
Labels: Ready for QA

#955 IBX-6843: Focus mode
  src/bundle/Resources/encore/ibexa.js.config.js
  src/bundle/Resources/public/img/ibexa-icons.svg
  src/bundle/Resources/public/img/icons/un-focus.svg
  src/bundle/Resources/public/js/scripts/admin.focus.mode.js
  src/bundle/Resources/public/scss/_alerts.scss
  src/bundle/Resources/public/scss/fieldType/edit/_base-field.scss
  src/bundle/Resources/translations/messages.en.xliff
  src/bundle/Resources/views/themes/admin/content/form_fields.html.twig
  src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
  src/lib/Behat/Component/Fields/RichText.php
Labels: Improvement, QA approved

#901 IBX-6413: As an Editor, I'd to see autocomplete in global search
  src/bundle/Resources/config/services/components/layout.yaml
  src/bundle/Resources/config/services/ui_config/common.yaml
  src/bundle/Resources/encore/ibexa.js.config.js
  src/bundle/Resources/public/js/scripts/admin.search.autocomplete.content.js
  src/bundle/Resources/public/js/scripts/admin.search.autocomplete.js
  src/bundle/Resources/public/js/scripts/admin.search.js
  src/bundle/Resources/public/js/scripts/helpers/content.type.helper.js
  src/bundle/Resources/public/js/scripts/helpers/highlight.helper.js
  src/bundle/Resources/public/scss/_filters.scss
  src/bundle/Resources/public/scss/_global-search.scss
  src/bundle/Resources/public/scss/_main-header.scss
  src/bundle/Resources/public/scss/_search-form.scss
  src/bundle/Resources/public/scss/ibexa.scss
  src/bundle/Resources/translations/ibexa_search.en.xliff
  src/bundle/Resources/translations/messages.en.xliff
  src/bundle/Resources/views/themes/admin/ui/global_search.html.twig
  src/bundle/Resources/views/themes/admin/ui/global_search_autocomplete_content_item.html.twig
  src/bundle/Resources/views/themes/admin/ui/global_search_autocomplete_content_template.html.twig
  src/bundle/Resources/views/themes/admin/ui/global_search_autocomplete_highlight.html.twig
  src/bundle/Resources/views/themes/admin/ui/search/form.html.twig
  src/lib/UI/Config/Provider/SuggestionSetting.php
Labels: QA approved, Ready for MERGE

#973 IBX-6950: Added style for invalid fields
  src/bundle/Resources/public/scss/mixins/_drag-and-drop.scss
Labels: Bug, QA approved

#965 IBX-6839: [Smart mode] As the User I want to view Authors tab with only selected data
  phpstan-baseline.neon
  src/bundle/Resources/translations/ibexa_locationview.en.xliff
  src/bundle/Resources/views/themes/admin/content/tab/authors.html.twig
  src/bundle/Resources/views/themes/admin/content/tab/details.html.twig
  src/lib/Tab/LocationView/AuthorsTab.php
  src/lib/Tab/LocationView/ContentTab.php
  src/lib/Tab/LocationView/DetailsTab.php
Labels: Doc needed, Ready for review

#992 IBX-6783:[Quick actions block] added missing icons: company, lighting
  src/bundle/Resources/public/img/ibexa-icons.svg
  src/bundle/Resources/public/img/icons/company.svg
  src/bundle/Resources/public/img/icons/lighting.svg
Labels: Feature

#990 IBX-7077: Add image_picker UDW config
  src/bundle/Resources/config/universal_discovery_widget.yaml
Labels: Doc needed

#989 IBX-6957: Moved UDW endpoints to REST API
  phpstan-baseline.neon
  src/bundle/Controller/UniversalDiscoveryController.php
  src/bundle/ControllerArgumentResolver/UniversalDiscoveryRequestQueryArgumentResolver.php
  src/bundle/Resources/config/routing.yaml
  src/bundle/Resources/config/routing_rest.yaml
  src/bundle/Resources/config/services.yaml
  src/bundle/Resources/config/services/controller_argument_resolvers.yaml
  src/bundle/Resources/config/services/controllers.yaml
  src/bundle/Resources/config/services/rest.yaml
  src/bundle/ui-dev/src/modules/universal-discovery/services/universal.discovery.service.js
  src/bundle/ui-dev/src/modules/universal-discovery/universal.discovery.module.js
  src/contracts/UniversalDiscovery/Provider.php
  src/lib/Exception/ValidationFailedException.php
  src/lib/REST/Output/ValueObjectVisitor/UniversalDiscovery/AbstractLocationDataVisitor.php
  src/lib/REST/Output/ValueObjectVisitor/UniversalDiscovery/AccordionDataVisitor.php
  src/lib/REST/Output/ValueObjectVisitor/UniversalDiscovery/LocationDataVisitor.php
  src/lib/REST/Output/ValueObjectVisitor/UniversalDiscovery/LocationListDataVisitor.php
  src/lib/REST/Value/UniversalDiscovery/AccordionData.php
  src/lib/REST/Value/UniversalDiscovery/LocationData.php
  src/lib/REST/Value/UniversalDiscovery/LocationListData.php
  src/lib/REST/Value/UniversalDiscovery/RequestQuery.php
  src/lib/UniversalDiscovery/UniversalDiscoveryProvider.php
  src/lib/Validator/Builder/REST/UniversalDiscoveryRequestValidatorBuilder.php
Labels: Improvement

#993 [Behat] Disabled COTF tests on Experience and Commerce editions
  features/standard/Bookmark.feature
  features/standard/SearchContent.feature
Labels: Ready for review

#1001 IBX-6549: Implemeted redesign loader
  src/bundle/Resources/public/js/scripts/embedded.item.actions.js
  src/bundle/Resources/public/scss/_embedded-item-actions.scss
  src/bundle/Resources/public/scss/ibexa.scss
  src/bundle/Resources/public/scss/mixins/_spinner.scss
  src/bundle/Resources/views/themes/admin/ui/component/embedded_item_actions/embedded_item_actions.html.twig
Labels: QA approved

#1004 [Behat] Disabled tests checking status of button hidden in the Context menu
  features/personas/SubtreeEditor.feature
Labels: Ready for review

#1003 IBX-7147: Fixed issue where multiple Encore entries are applied to ESI fragments
  src/bundle/Resources/views/themes/admin/ui/dashboard/block/all.html.twig
  src/bundle/Resources/views/themes/admin/ui/dashboard/block/me.html.twig
  src/bundle/Resources/views/themes/admin/ui/tab/default.html.twig
Labels: Bug

#998 IBX-6939: As the User I want to change mode in User settings
  src/bundle/DependencyInjection/Configuration/Parser/AdminUiParser.php
  src/bundle/IbexaAdminUiBundle.php
  src/bundle/Resources/config/default_parameters.yaml
  src/bundle/Resources/config/services/user_settings.yaml
  src/bundle/Resources/translations/ibexa_user_settings.en.xliff
  src/lib/Form/Type/User/UserModeChoiceType.php
  src/lib/UserSetting/Group/UserModeGroup.php
  src/lib/UserSetting/UserMode.php
Labels: Ready for review

#1009 IBX-7163: Remove Bootstrap classes, change trigger for bootstrap btns to hover
  src/bundle/Resources/public/js/scripts/helpers/tooltips.helper.js
  src/bundle/Resources/public/scss/_empty-chart.scss
  src/bundle/Resources/public/scss/ibexa.scss
  src/bundle/Resources/translations/messages.en.xliff
  src/bundle/Resources/views/themes/admin/ui/dashboard/block/all.html.twig
  src/bundle/Resources/views/themes/admin/ui/dashboard/block/me.html.twig
  src/bundle/Resources/views/themes/admin/ui/empty_chart.html.twig
Labels: QA approved
