Repository ibexa/admin-ui, pull requests merged in 2023-09, with the labels that each got.

#904 Fixed PHPStan for multiple PHP versions
  .github/workflows/ci.yaml
  phpstan-baseline-7.4.neon
  phpstan-baseline-8.0.neon
  phpstan-baseline.neon
  phpstan-baseline.neon.php
  phpstan.neon
Labels: Ready for review

#889 IBX-3698: Conditional icon for form_help
  src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
Labels: Improvement, QA approved

#905 Added PHPStan for 4.5 version
  .github/workflows/ci.yaml
  composer.json
  phpstan-baseline-7.4.neon
  phpstan-baseline-8.0.neon
  phpstan-baseline.neon
  phpstan-baseline.neon.php
  phpstan.neon
  src/lib/Behat/Component/ContentItemAdminPreview.php
Labels: Improvement, Ready for review

#877 IBX-6252: Update hover styles for --selector button
  src/bundle/Resources/public/scss/_buttons.scss
Labels: QA approved

#898 [Behat] IBX-6335: Added PropertiesList component
  src/bundle/Resources/config/services/test/components.yaml
  src/lib/Behat/Component/PropertiesList.php
Labels: Ready for review

#884 IBX-6338: As an Editor I'd like to sort the list of search results
  src/bundle/Resources/encore/ibexa.js.config.js
  src/bundle/Resources/public/js/scripts/admin.search.sorting.js
  src/bundle/Resources/views/themes/admin/ui/search/results.html.twig
Labels: QA approved

#871 IBX-6339: As an Editor I'd like use facets to filter global search results
  src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
  src/bundle/Resources/views/themes/admin/ui/search/filters.html.twig
Labels: Feature, QA approved, Ready for MERGE

#907 [Behat] IBX-6505: Covered Content on the Fly with Visual Test
  src/lib/Behat/Component/ContentTypePicker.php
  src/lib/Behat/Component/UniversalDiscoveryWidget.php
Labels: Ready for review

#899 IBX-6502: Drafts under content
  src/bundle/Resources/translations/ibexa_dashboard.en.xliff
  src/bundle/Resources/translations/ibexa_menu.en.xliff
  src/bundle/Resources/views/themes/admin/ui/dashboard/dashboard.html.twig
  src/lib/Menu/MainMenuBuilder.php
Labels: Doc needed, Feature, Ready for QA, Ready for review

#903 IBX-6492: Keyboard support for redo and undo
  src/bundle/Resources/encore/ibexa.js.config.js
  src/bundle/Resources/public/js/scripts/helpers/system.helper.js
Labels: QA approved

#915 IBX-6627: Removed non-existing service definition
  src/bundle/Resources/config/services/validators.yaml
Labels: Bug, Ready for review

#734 IBX-5280: Added constraint LocationIsContainer to parentLocation in ContentCreateData
  src/lib/Form/Data/Content/Draft/ContentCreateData.php
Labels: Bug, QA approved

#912 IBX-6343: ezdate and ezdatetime validation is styled properly
  src/bundle/Resources/public/js/scripts/fieldType/ezdate.js
  src/bundle/Resources/public/js/scripts/fieldType/ezdatetime.js
  src/bundle/Resources/public/scss/_mixins.scss
Labels: Bug, QA approved, Ready for MERGE

#902 IBX-6454: Added new css spinner mixin
  src/bundle/Resources/public/scss/_mixins.scss
  src/bundle/Resources/public/scss/mixins/_spinner.scss
Labels: QA approved

#917 IBX-5854: Unified cookies names
  src/bundle/Resources/public/js/scripts/sidebar/main.menu.js
  src/bundle/Resources/views/themes/admin/content/location_view.html.twig
  src/bundle/Resources/views/themes/admin/ui/component/adaptive_filters/adaptive_filters.html.twig
  src/bundle/Resources/views/themes/admin/ui/menu/main_2nd_level.html.twig
Labels: QA approved

#909 IBX-6378: Create content on the fly view is not styled properly
  src/bundle/Resources/public/scss/_main-container.scss
Labels: Bug, QA approved, Ready for MERGE

#920 IBX-6475: Fix translation variable visible in UI
  src/bundle/Resources/translations/ibexa_content_create.en.xliff
  src/bundle/Resources/translations/ibexa_content_edit.en.xliff
  src/bundle/Resources/views/themes/admin/content/create/create.html.twig
  src/bundle/Resources/views/themes/admin/content/edit/edit.html.twig
  src/bundle/Resources/views/themes/admin/ui/on_the_fly/edit_on_the_fly.html.twig
Labels: QA approved, Ready for MERGE

#924 Fixed PHPStan errors after upstream update
  phpstan-baseline.neon
  src/lib/Menu/ContentEditAnchorMenuBuilder.php
  src/lib/Menu/ContentTypeEditAnchorMenuBuilder.php
  tests/lib/Form/Data/FormMapper/ContentTypeDraftMapperTest.php
Labels: Ready for review
