Repository ibexa/admin-ui, pull requests merged in 2023-06, with the labels that each got.

#807 IBX-5784: CkEditor toolbar overflow fix
  src/bundle/Resources/public/scss/_edit-header.scss
  src/bundle/Resources/public/scss/_main-container.scss
Labels: QA approved

#796 IBX-4233: Form Inputs - space between fields
  src/bundle/Resources/public/scss/_add-translation.scss
  src/bundle/Resources/public/scss/_anchor-navigation.scss
  src/bundle/Resources/public/scss/_card.scss
  src/bundle/Resources/public/scss/_content-type-edit.scss
  src/bundle/Resources/public/scss/_custom-url-form.scss
  src/bundle/Resources/public/scss/_edit-header.scss
  src/bundle/Resources/public/scss/_labels.scss
  src/bundle/Resources/public/scss/_tabs.scss
  src/bundle/Resources/public/scss/fieldType/edit/_base-field.scss
  src/bundle/Resources/public/scss/fieldType/edit/_eznoneditable.scss
  src/bundle/Resources/public/scss/fieldType/edit/_ezuser.scss
  src/bundle/Resources/public/scss/mixins/_containers.scss
  src/bundle/Resources/views/themes/admin/content/tab/url/modal_add_custom_url.html.twig
  src/bundle/Resources/views/themes/admin/content_type/content_type_group/create.html.twig
  src/bundle/Resources/views/themes/admin/content_type/content_type_group/edit.html.twig
  src/bundle/Resources/views/themes/admin/language/create.html.twig
  src/bundle/Resources/views/themes/admin/language/edit.html.twig
  src/bundle/Resources/views/themes/admin/object_state/add.html.twig
  src/bundle/Resources/views/themes/admin/object_state/edit.html.twig
  src/bundle/Resources/views/themes/admin/object_state/object_state_group/add.html.twig
  src/bundle/Resources/views/themes/admin/object_state/object_state_group/edit.html.twig
  src/bundle/Resources/views/themes/admin/section/create.html.twig
  src/bundle/Resources/views/themes/admin/section/update.html.twig
  src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
  src/bundle/Resources/views/themes/admin/url_wildcard/modal_create.html.twig
  src/bundle/Resources/views/themes/admin/url_wildcard/update.html.twig
  src/bundle/Resources/views/themes/admin/user/policy/add.html.twig
  src/bundle/Resources/views/themes/admin/user/role/add.html.twig
  src/bundle/Resources/views/themes/admin/user/role/copy.html.twig
  src/bundle/Resources/views/themes/admin/user/role/edit.html.twig
  src/bundle/Resources/views/themes/admin/user/role_assignment/create.html.twig
Labels: QA approved

#809 IBX-5945: Fix Trash's pagination
  src/bundle/Resources/views/themes/admin/trash/list.html.twig
Labels: Bug, QA approved, Ready for MERGE

#810 IBX-5411: Fixed form exception due to incomplete field definition
  src/lib/Form/Type/ContentType/FieldDefinitionsCollectionType.php
Labels: Bug, QA approved, Ready for review

#812 [Behat] Fix for create and edit company form
  src/lib/Behat/Component/Fields/ContentRelationSingle.php
Labels: Ready for review

#814 [Behat] IBX-4482 Fix for toggle button enabled (#786)
  src/lib/Behat/Component/Fields/User.php
Labels: Ready for review

#819 [Behat] Fix for company edition
  src/lib/Behat/Component/Fields/ContentRelationSingle.php
Labels: Ready for review

#816 IBX-5934: added icon 'business-deal-cash'
  src/bundle/Resources/public/img/ibexa-icons.svg
  src/bundle/Resources/public/img/icons/business-deal-cash.svg
Labels: Bug, QA approved, Ready for MERGE

#821 IBX-6003: Fixed tab rendering after changing page in the Assignments tab in the Roles module
  src/bundle/Resources/views/themes/admin/user/role_assignment/list.html.twig
Labels: Bug, QA approved

#813 IBX-4676: Update label for button 'Discard changes' [edit content type]
  features/standard/ContentType.feature
  src/bundle/Resources/translations/menu.en.xliff
  src/lib/Menu/Admin/ContentType/ContentTypeCreateRightSidebarBuilder.php
  src/lib/Menu/Admin/ContentType/ContentTypeEditRightSidebarBuilder.php
Labels: Bug, QA approved

#822 IBX-5999: Tag styles updated
  src/bundle/Resources/public/scss/_tag.scss
Labels: QA approved

#826 IBX-2766: Made custom url aliases tab more generic
  src/bundle/Resources/translations/content_url.en.xliff
  src/bundle/Resources/views/themes/admin/content/tab/url/custom_urls_table.html.twig
  src/bundle/Resources/views/themes/admin/content/tab/url/system_urls_table.html.twig
Labels: Ready for QA, Ready for review
