Repository ibexa/admin-ui, pull requests merged in 2023-04, with the labels that each got.

#722 IBX-5121: Streamlined SiteaccessResolverInterface
  src/bundle/Resources/config/services/forms.yaml
  src/bundle/Resources/config/services/menu.yaml
  src/lib/Component/Content/PreviewUnavailableTwigComponent.php
  src/lib/Form/Type/ChoiceList/Loader/SiteAccessChoiceLoader.php
  src/lib/Form/Type/Content/CustomUrl/CustomUrlAddType.php
  src/lib/Menu/ContentEditRightSidebarBuilder.php
  src/lib/Siteaccess/NonAdminSiteaccessResolver.php
  src/lib/Siteaccess/SiteaccessResolver.php
  src/lib/Siteaccess/SiteaccessResolverInterface.php
Labels: QA approved

#753 IBX-1961: Added extensibility point to edit header
  src/bundle/Resources/views/themes/admin/ui/edit_header.html.twig
Labels: QA approved, Ready for MERGE

#747 IBX-5412: Removed parseInt from selectedItem.dataset.id
  src/bundle/Resources/public/js/scripts/core/tag.view.select.js
  src/bundle/Resources/views/themes/admin/ui/search/filters.html.twig
Labels: Bug, QA approved

#752 IBX-5368: fix popup menu item height for multiline items
  src/bundle/Resources/public/scss/_popup-menu.scss
Labels: QA approved

#754 IBX-3482: Fixed position of actions in details header
  src/bundle/Resources/public/scss/_details.scss
Labels: QA approved, Ready for MERGE

#750 IBX-5361: Use NotCompromisedPassword constraint
  src/bundle/Resources/translations/content_type.en.xliff
  src/bundle/Resources/views/themes/admin/content_type/field_types.html.twig
  src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
  src/lib/FieldType/Mapper/UserAccountFormMapper.php
Labels: Doc needed, Feature, Ready for QA

#760 IBX-5518: Add tag block in page_title twig component
  src/bundle/Resources/views/themes/admin/ui/page_title.html.twig
Labels: QA approved, Ready for MERGE

#758 IBX-4012: [Sections] Recalculate last section padding on section height change
  src/bundle/Resources/public/js/scripts/admin.anchor.navigation.js
Labels: QA approved, Ready for QA

#767 IBX-5622: Adaptive filters styling improvements
  src/bundle/Resources/public/js/scripts/adaptive.filters.js
  src/bundle/Resources/public/scss/_adaptive-filters.scss
  src/bundle/Resources/views/themes/admin/ui/component/adaptive_filters/adaptive_filters.html.twig
Labels: QA approved, Ready for MERGE

#766 IBX-5565: Add reusable delete confirmation modal
  src/bundle/Resources/translations/content_type.en.xliff
  src/bundle/Resources/views/themes/admin/ui/modal/delete_confirmation.html.twig
  src/lib/FieldType/Mapper/UserAccountFormMapper.php
Labels: QA approved, Ready for MERGE

#763 IBX-5576: [Payments] Issues with filters
  src/bundle/Resources/public/js/scripts/core/dropdown.js
  src/bundle/Resources/public/scss/_dropdown.scss
Labels: QA approved

#771 IBX-5635: [Payments] Missing placeholder after removing all items from the filter
  src/bundle/Resources/public/scss/_dropdown.scss
  src/bundle/Resources/views/themes/admin/ui/component/dropdown/dropdown.html.twig
Labels: QA approved
