Repository ibexa/admin-ui, pull requests merged in 2023-05, with the labels that each got.

#744 IBX-5382: Optimize Content Tree node building when it comes to bookmarks
  src/lib/UI/Module/ContentTree/NodeFactory.php
Labels: Improvement, QA approved, Ready for MERGE

#773 IBX-5653: [Search] Theres JS error on Select subtree UDW confirm action
  src/bundle/Resources/public/js/scripts/helpers/middle.ellipsis.js
Labels: QA approved, Ready for MERGE

#774 IBX-5400: Subtree Filter with content long name have remove icon outside of badge
  src/bundle/Resources/public/scss/_tag-view-select.scss
Labels: QA approved, Ready for MERGE

#780 IBX-5697: [Dropdown] Change default placeholder to "All"
  src/bundle/Resources/translations/dropdown.en.xliff
  src/bundle/Resources/translations/trash.en.xliff
  src/bundle/Resources/views/themes/admin/ui/component/dropdown/dropdown.html.twig
  src/lib/Form/Type/Search/TrashSearchType.php
Labels: QA approved

#778 [Behat] Retry expanding the last fieldtype
  src/lib/Behat/Page/ContentTypeUpdatePage.php
Labels: Ready for review

#779 [Behat] Increased timeout for UDW closing
  src/lib/Behat/Component/UniversalDiscoveryWidget.php
Labels: Ready for review

#784 IBX-5702: Fixed ezselection rendering
  src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezselection.html.twig
  src/bundle/Resources/views/themes/admin/ui/form_fields/dropdown_widget.html.twig
Labels: Bug, QA approved

#783 IBX-5660: Added option to position headline items
  src/bundle/Resources/public/scss/_details.scss
  src/bundle/Resources/views/themes/admin/ui/component/details/details.html.twig
Labels: QA approved

#786 [Behat] IBX-4482 Fix for toggle button enabled
  src/lib/Behat/Component/Fields/User.php
Labels: Ready for review

#765 IBX-5606: Removed duplicated GraphQL request in the Subitems module
  src/bundle/ui-dev/src/modules/sub-items/sub.items.module.js
Labels: Bug, QA approved

#756 IBX-3528: Fixed collapse toggler rotation
  src/bundle/Resources/public/scss/_collapse.scss
  src/bundle/Resources/views/themes/admin/ui/component/collapse.html.twig
Labels: Bug, QA approved

#790 IBX-5717: Content type filter values in UDW have minor CSS issues
  src/bundle/Resources/public/scss/ui/modules/universal-discovery/_filters.scss
  src/bundle/ui-dev/src/modules/universal-discovery/components/content-type-selector/content.type.selector.js
Labels: QA approved, Ready for MERGE

#791 IBX-4674: Unnecessary wrap on text in checkbox on field - opened accordion
  src/bundle/Resources/views/themes/admin/content_type/field_types.html.twig
Labels: QA approved

#772 IBX-5620: Fixed validation in change password
  src/bundle/Resources/views/themes/admin/account/change_password/form_fields.html.twig
Labels: QA approved

#800 IBX-5789: [BO]: checkbox display broken when language is set to french
  src/bundle/Resources/public/scss/_inputs.scss
Labels: QA approved

#798 IBX-5778: CT translation dropdown is not aligned and its placement is wrong place
  src/bundle/Resources/public/scss/_details.scss
  src/bundle/Resources/views/themes/admin/content_type/tab/view.html.twig
  src/bundle/Resources/views/themes/admin/ui/component/details/details.html.twig
Labels: QA approved

#777 IBX-5455: Checkboxes are not aligned with other data in Languages & Currencies tabs
  src/bundle/Resources/public/scss/_inputs.scss
  src/bundle/Resources/public/scss/_tables.scss
  src/bundle/Resources/views/themes/admin/language/index.html.twig
  src/bundle/Resources/views/themes/admin/language/list.html.twig
Labels: QA approved
