Repository ibexa/admin-ui, pull requests merged in 2023-03, with the labels that each got.

#698 IBX-4681: Cannot swap sections with D&D in Content/Product Type
  src/bundle/Resources/views/themes/admin/content_type/field_definitions.html.twig
Labels: QA approved

#695 IBX-4445: Option to add last column in tables as sticky
  src/bundle/Resources/public/js/scripts/admin.table.js
  src/bundle/Resources/public/scss/_tables.scss
  src/bundle/Resources/views/themes/admin/ui/component/table/table.html.twig
Labels: QA approved

#712 IBX-5151: [Subitems] Clicking arrow in non-focused input priority doesn't change value
  src/bundle/Resources/public/scss/ui/modules/sub-items-list/_table.view.item.scss
  src/bundle/ui-dev/src/modules/sub-items/components/table-view/table.view.item.component.js
Labels: QA approved

#715 [Behat] IBX-4889: Cover file upload with a Visual Test
  src/lib/Behat/Page/ContentUpdateItemPage.php
  src/lib/Behat/Page/UserUpdatePage.php
Labels: Ready for review

#719 IBX-5197: [Change password] Error messages stack on submit
  src/bundle/Resources/public/js/scripts/user_password.change.js
Labels: QA approved, Ready for MERGE

#714 IBX-5138: The header in content edit view is displayed incorrectly when scrolling
  src/bundle/Resources/public/js/scripts/edit.header.js
  src/bundle/Resources/public/js/scripts/helpers/middle.ellipsis.js
  src/bundle/Resources/public/scss/_edit-header.scss
  src/bundle/Resources/public/scss/_middle-ellipsis.scss
  src/bundle/Resources/views/themes/admin/ui/edit_header.html.twig
Labels: QA approved

#707 IBX-5131: Add status badge
  src/bundle/Resources/public/scss/_badges.scss
Labels: QA approved

#729 IBX-5240: Fixed translation edit widget
  src/bundle/Resources/public/scss/_extra-actions.scss
  src/bundle/Resources/public/scss/ui/modules/universal-discovery/_translation.selector.scss
Labels: QA approved, Ready for MERGE

#720 IBX-5018: Unified 'Create' buttons in Content Types and Content Type Groups lists
  src/bundle/Controller/ContentTypeGroupController.php
  src/bundle/Resources/translations/content_type.en.xliff
  src/bundle/Resources/views/themes/admin/content_type/content_type_group/index.html.twig
  src/bundle/Resources/views/themes/admin/content_type/list.html.twig
Labels: Improvement, QA approved, Ready for MERGE

#728 IBX-5255: Move required validation method to helpers
  src/bundle/Resources/encore/ibexa.js.config.js
  src/bundle/Resources/public/js/scripts/admin.contenttype.edit.js
  src/bundle/Resources/public/js/scripts/core/dropdown.js
  src/bundle/Resources/public/js/scripts/fieldType/base/base-field.js
  src/bundle/Resources/public/js/scripts/helpers/form.error.helper.js
  src/bundle/Resources/public/js/scripts/helpers/form.validation.helper.js
  src/bundle/Resources/public/js/scripts/user_password.change.js
  src/bundle/Resources/public/scss/_forms.scss
  src/bundle/Resources/public/scss/fieldType/edit/_base-field.scss
  src/bundle/Resources/views/themes/admin/ui/form_fields/dropdown_widget.html.twig
Labels: QA approved

#730 IBX-5248: Fixed checkbox alignment in content center table cell
  src/bundle/Resources/public/scss/_tables.scss
Labels: QA approved, Ready for MERGE

#733 [Behat] Keep only inline custom styles to calculate offset
  src/lib/Behat/Component/Fields/RichText.php
Labels: Ready for review

#739 IBX-4953: badge custom color style
  src/bundle/Resources/public/scss/_badges.scss
Labels: Doc needed

#732 IBX-5293: Replaced custom redirect success handler with listener
  src/bundle/DependencyInjection/Compiler/SecurityLoginPass.php
  src/bundle/IbexaAdminUiBundle.php
  src/bundle/Resources/config/services.yaml
  src/bundle/Resources/config/services/security.yaml
  src/lib/Security/Authentication/RedirectToDashboardAuthenticationSuccessHandler.php
  src/lib/Security/Authentication/RedirectToDashboardListener.php
Labels: QA approved

#685 IBX-4929: ChangeOwnerLimitationMapper: Fix phpDoc
  src/lib/Limitation/Mapper/ChangeOwnerLimitationMapper.php
Labels: Ready for MERGE

#743 IBX-4929: TrashController::listAction: remove @internal
  src/bundle/Controller/TrashController.php
Labels: Ready for MERGE
