Repository ibexa/admin-ui, pull requests merged in 2023-01, with the labels that each got.

#671 Changed Entrypoint in AdminExceptionListener from "ezplatform" to "ibexa"
  src/lib/EventListener/AdminExceptionListener.php
Labels: Bug, QA approved, Ready for MERGE

#656 IBX-4328: Hover on icons preview switcher
  src/bundle/Resources/public/js/scripts/admin.preview.js
  src/bundle/Resources/public/scss/_buttons.scss
  src/bundle/Resources/views/themes/admin/content/content_preview.html.twig
  src/lib/Behat/Page/ContentPreviewPage.php
Labels: QA approved

#673 IBX-4544: Removed menu items from 404 page causing loops and timeouts
  src/bundle/Resources/views/themes/admin/ui/error_page/404.html.twig
  src/bundle/Resources/views/themes/admin/ui/layout.html.twig
Labels: QA approved, Ready for review

#674 IBX-4717: Fixed PolicyChoiceType translation domain configuration
  src/lib/Form/Type/Policy/PolicyChoiceType.php
Labels: QA approved

#677 IBX-4576: Added a keyup event so that set minutes and hours can be set from the keyboard
  src/bundle/Resources/public/js/scripts/core/date.time.picker.js
Labels: Bug, Ready for review

#681 IBX-4661: Double file upload in Image/ImageAsset/File
  src/bundle/Resources/public/scss/fieldType/edit/_base-preview.scss
  src/bundle/Resources/views/themes/admin/ui/field_type/edit/binary_base.html.twig
  src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezimageasset.html.twig
Labels: QA approved, Ready for MERGE

#683 IBX-4834: Fixed minute and hour listeners in flatpickr
  src/bundle/Resources/public/js/scripts/core/date.time.picker.js
Labels: QA approved, Ready for MERGE

#682 IBX-4767: Input_text updated extrabutton
  src/bundle/Resources/public/js/scripts/admin.input.text.js
  src/bundle/Resources/public/scss/_buttons.scss
  src/bundle/Resources/public/scss/_inputs.scss
  src/bundle/Resources/views/themes/admin/ui/component/input_text.html.twig
Labels: QA approved

#684 IBX-4918: Moved Specification abstraction from AdminUi to Core
  src/lib/Specification/AbstractSpecification.php
  src/lib/Specification/AndSpecification.php
  src/lib/Specification/NotSpecification.php
  src/lib/Specification/OrSpecification.php
  src/lib/Specification/SpecificationInterface.php
Labels: Ready for review
