Repository ibexa/admin-ui, pull requests merged in 2023-07, with the labels that each got.

#830 [Behat] Added small wait before interacting with Single relation button
  src/lib/Behat/Component/Fields/ContentRelationSingle.php
Labels: Ready for review

#820 IBX-5869: Search results table view for many translations
  src/bundle/Resources/public/scss/_search-form.scss
Labels: Bug, QA approved

#831 [Behat] Added small wait before interacting with Single relation butt…
  src/lib/Behat/Component/Fields/ContentRelationSingle.php
Labels: Ready for review

#815 IBX-5784, IBX-5743: CkEditor toolbar overflow
  src/bundle/Resources/encore/ibexa.js.config.js
  src/bundle/Resources/public/js/scripts/core/backdrop.js
  src/bundle/Resources/public/js/scripts/sidebar/extra.actions.js
  src/bundle/Resources/public/scss/_backdrop.scss
  src/bundle/Resources/public/scss/_edit-header.scss
  src/bundle/Resources/public/scss/_main-container.scss
  src/bundle/Resources/views/themes/admin/ui/layout.html.twig
Labels: QA approved

#837 [Behat] Hardened Field Type adding
  src/lib/Behat/Page/ContentTypeUpdatePage.php
Labels: Ready for review

#823 [Behat] IBX-5755 Added test scenarios for product variants
  src/lib/Behat/BrowserContext/NotificationContext.php
  src/lib/Behat/Component/Notification.php
Labels: Ready for review

#832 IBX-5979: Fixed creator filter overlapped by table elements in trash list
  src/bundle/Resources/public/scss/_filters.scss
  src/bundle/Resources/public/scss/_trash-search-form.scss
Labels: QA approved

#843 IBX-6001: Added cast items array to String
  src/bundle/Resources/public/js/scripts/core/tag.view.select.js
Labels: Bug, QA approved
