Repository ibexa/admin-ui, pull requests merged in 2023-08, with the labels that each got.

#839 IBX-4325: Added min-height for field definition header
  src/bundle/Resources/public/scss/_field-group.scss
Labels: QA approved

#841 IBX-4172: Fixed jumping headline in content structure
  src/bundle/Resources/public/scss/_field-group.scss
  src/bundle/Resources/views/themes/admin/content/content_view_fields.html.twig
Labels: QA approved

#845 IBX-3675: Fix unavailable state styling of PB sidebar blocks (d&d)
  src/bundle/Resources/public/scss/mixins/_drag-and-drop.scss
Labels: QA approved

#844 IBX-5145: Modified invitation modal for easier extending
  src/bundle/Resources/views/themes/admin/user/invitation/modal.html.twig
Labels: QA approved, Ready for MERGE

#868 IBX-6327: Added missing content_type_name parameter
  src/bundle/Resources/views/themes/admin/ui/on_the_fly/edit_on_the_fly.html.twig
Labels: Bug, Ready for QA

#850 IBX-6240: Create general css classes for switcher (from edit form left menu)
  src/bundle/Resources/public/js/scripts/admin.anchor.navigation.js
  src/bundle/Resources/public/scss/_anchor-navigation.scss
  src/bundle/Resources/public/scss/_switcher.scss
  src/bundle/Resources/public/scss/ibexa.scss
  src/bundle/Resources/views/themes/admin/ui/menu/anchor_menu.html.twig
  src/lib/Behat/Page/ContentUpdateItemPage.php
Labels: QA approved

#865 IBX-6260: Fixed preview voter taking language priority into consideration
  src/lib/Siteaccess/AbstractSiteaccessPreviewVoter.php
Labels: QA approved

#869 IBX-5886: Dispatched `ContentCreateContentTypeChoiceLoaderEvent`
  src/bundle/Resources/config/services/forms.yaml
  src/lib/Form/Type/ChoiceList/Loader/ContentCreateContentTypeChoiceLoader.php
  src/lib/Form/Type/Content/Draft/ContentCreateType.php
  src/lib/Form/Type/Event/ContentCreateContentTypeChoiceLoaderEvent.php
Labels: Improvement, QA approved, Ready for MERGE

#870 IBX-6214: default action set to publishContentType
  src/bundle/Controller/ContentTypeController.php
Labels: Bug, QA approved, Ready for MERGE

#873 IBX-6230: Fix incorrect CSS selectors in Behat code
  src/lib/Behat/Component/Fields/Matrix.php
  src/lib/Behat/Component/Table/TableBuilder.php
  src/lib/Behat/Component/UniversalDiscoveryWidget.php
  src/lib/Behat/Page/ContentTypePage.php
  src/lib/Behat/Page/ContentTypeUpdatePage.php
  src/lib/Behat/Page/SystemInfoPage.php
Labels: Ready for review

#861 IBX-6261: Fixed UDW Search module to set locations when unmounting
  src/bundle/ui-dev/src/modules/universal-discovery/search.tab.module.js
Labels: Bug, QA approved

#879 IBX-6280: [Behat] Retry entering Richtext value
  src/lib/Behat/Component/Fields/RichText.php
Labels: Ready for review

#885 IBX-6342: Fixed richtext field in user content type
  src/bundle/Resources/views/themes/admin/user/create.html.twig
  src/bundle/Resources/views/themes/admin/user/edit.html.twig
Labels: QA approved

#860 IBX-5854: Added base backoffice path to adminUI config
  src/bundle/Resources/config/services/ui_config/common.yaml
  src/bundle/Resources/public/js/scripts/adaptive.filters.js
  src/bundle/Resources/public/js/scripts/helpers/cookies.helper.js
  src/bundle/Resources/public/js/scripts/sidebar/main.menu.js
  src/lib/UI/Config/Provider/CurrentBackOfficePath.php
Labels: Ready for QA

#854 Added a UserSetting to toggle In-Context translations
  .sonarcloud.properties
  src/bundle/Resources/config/services/events.yaml
  src/bundle/Resources/config/services/user_settings.yaml
  src/bundle/Resources/translations/user_settings.en.xliff
  src/bundle/Resources/views/themes/admin/account/base.html.twig
  src/bundle/Resources/views/themes/admin/ui/layout.html.twig
  src/lib/EventListener/InContextTranslationListener.php
  src/lib/UserSetting/InContextTranslation.php
  tests/lib/EventListener/InContextTranslationListenerTest.php
Labels: Bug, QA approved

#893 Introduced PHP Stan
  .github/workflows/ci.yaml
  composer.json
  phpstan-baseline.neon
  phpstan.neon
  src/lib/Behat/Component/ContentItemAdminPreview.php
Labels: Ready for review
