Repository ibexa/admin-ui, pull requests merged in 2023-12, with the labels that each got.

#906 IBX-6566: As a Editor I'd like to get content type suggestions while creating content in given location
  phpstan-baseline.neon
  src/bundle/Resources/translations/ibexa_content_create.en.xliff
  src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
  src/lib/EventListener/ContentTypeSuggestionsListener.php
  src/lib/Form/Type/ChoiceList/Loader/ContentCreateContentTypeChoiceLoader.php
  src/lib/Form/Type/Content/Draft/ContentCreateType.php
  src/lib/Form/Type/ContentType/ContentTypeChoiceType.php
  src/lib/Form/Type/Event/ContentCreateContentTypeChoiceLoaderEvent.php
  tests/lib/EventListener/ContentTypeSuggestionsListenerTest.php
Labels: QA approved

#1019 IBX-7258: add getContentTypeDataByHref helper
  src/bundle/Resources/public/js/scripts/helpers/content.type.helper.js
Labels: Doc needed

#1012 IBX-7126: Allowed passing extra parameters to pager of "My Drafts" tab
  src/lib/Tab/Dashboard/MyDraftsTab.php
  tests/lib/Tab/Dashboard/MyDraftsTabTest.php
Labels: Bug, QA approved

#923 IBX-6649: Added support for spell checking
  src/bundle/Resources/public/scss/_search-criteria-tags.scss
  src/bundle/Resources/public/scss/_search-form.scss
  src/bundle/Resources/translations/ibexa_search.en.xliff
  src/bundle/Resources/views/themes/admin/ui/search/criteria_tags.html.twig
  src/bundle/Resources/views/themes/admin/ui/search/results.html.twig
  src/bundle/Resources/views/themes/admin/ui/search/spellcheck.html.twig
Labels: Doc needed

#966 IBX-6937: Used NumberType field to set max image size in ImageFormMapper
  src/lib/FieldType/Mapper/ImageFormMapper.php
Labels: Improvement, QA approved

#1006 IBX-7158: As an Editor, I'd like to have shortcut for search focus
  src/bundle/Resources/public/js/scripts/admin.search.autocomplete.js
  src/bundle/Resources/public/js/scripts/helpers/system.helper.js
  src/bundle/Resources/public/scss/_global-search.scss
  src/bundle/Resources/translations/ibexa_search.en.xliff
  src/bundle/Resources/views/themes/admin/ui/global_search.html.twig
Labels: QA approved

#1015 IBX-7246: Burger menu duplicated for tabs without children
  src/bundle/Resources/views/themes/admin/ui/menu/main_2nd_level.html.twig
Labels: QA approved

#1034 Fixed PHPStan issues
  phpstan-baseline.neon
  src/lib/View/Filter/AdminSearchViewFilter.php
Labels: Bug, Ready for review

#1027 IBX-7275: Exposed base admin UI configuration in REST API
  src/bundle/Controller/ApplicationConfigController.php
  src/bundle/Resources/config/routing_rest.yaml
  src/bundle/Resources/config/services/controllers.yaml
  src/bundle/Resources/config/services/rest.yaml
  src/bundle/Resources/config/services/ui_config/common.yaml
  src/contracts/REST/ApplicationConfigRestGeneratorInterface.php
  src/contracts/REST/ApplicationConfigRestGeneratorRegistryInterface.php
  src/lib/REST/Generator/ApplicationConfigRestGeneratorRegistry.php
  src/lib/REST/Generator/ProfilePictureFieldConfigRestGenerator.php
  src/lib/REST/Generator/UserConfigRestGenerator.php
  src/lib/REST/Output/ValueObjectVisitor/ApplicationConfigVisitor.php
  src/lib/REST/Value/ApplicationConfig.php
Labels: Doc needed, Improvement, QA approved

#1042 [Behat] Increased the timeout for opening Content update Page
  src/lib/Behat/Page/ContentUpdateItemPage.php
Labels: Ready for review

#1041 [Behat] Increased timeout for UDW searching
  src/lib/Behat/Component/UniversalDiscoveryWidget.php
Labels: Ready for review

#1038 IBX-7250: [Site context] Long site name should be truncated with '...'
  src/bundle/Resources/public/js/scripts/core/dropdown.js
Labels: QA approved

#1043 IBX-7122: Hidden hide/show toggler
  src/bundle/Resources/views/themes/admin/account/settings/list.html.twig
Labels: Bug, Ready for QA

#1021 IBX-6856: Added mimeTypes field to ImageFormMapper
  phpstan-baseline.neon
  src/bundle/Resources/config/services/fieldtype_form_mappers.yaml
  src/bundle/Resources/public/js/scripts/fieldType/base/base-file-field.js
  src/bundle/Resources/public/js/scripts/fieldType/base/base-preview-field.js
  src/bundle/Resources/public/js/scripts/fieldType/ezbinaryfile.js
  src/bundle/Resources/public/js/scripts/fieldType/ezimage.js
  src/bundle/Resources/public/js/scripts/fieldType/ezimageasset.js
  src/bundle/Resources/public/js/scripts/fieldType/ezmedia.js
  src/bundle/Resources/public/scss/fieldType/edit/_base-preview.scss
  src/bundle/Resources/translations/ibexa_content_forms_content.en.xliff
  src/bundle/Resources/translations/ibexa_content_type.en.xliff
  src/bundle/Resources/translations/validators.en.xliff
  src/bundle/Resources/views/themes/admin/content_type/field_types.html.twig
  src/bundle/Resources/views/themes/admin/ui/field_type/edit/binary_base.html.twig
  src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezimage.html.twig
  src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezimageasset.html.twig
  src/bundle/Resources/views/themes/admin/ui/layout.html.twig
  src/lib/FieldType/Mapper/ImageFormMapper.php
Labels: Feature, Ready for QA

#1063 IBX-7401: Fixed input file type validation for image asset field
  src/bundle/Resources/public/js/scripts/fieldType/base/base-file-field.js
  src/bundle/Resources/public/js/scripts/fieldType/ezimage.js
  src/bundle/Resources/public/js/scripts/fieldType/ezimageasset.js
Labels: Bug, QA approved, Ready for review

#1030 IBX-7020: Redirect to a parent Location after saving and closing a draft
  src/bundle/Resources/config/services/form_processors.yaml
  src/lib/Form/Processor/ContentEditFormProcessor.php
Labels: Bug, Ready for QA

#1055 IBX-7356: [Sub-items] - disable Columns settings in Grid view
  src/bundle/Resources/public/scss/ui/modules/common/_simple.dropdown.scss
  src/bundle/Resources/public/scss/ui/modules/sub-items-list/_main.scss
  src/bundle/ui-dev/src/modules/sub-items/components/view-columns-toggler/view.columns.toggler.js
  src/bundle/ui-dev/src/modules/sub-items/sub.items.module.js
Labels: Bug, QA approved

#1056 [Behat] Increased timeout for UDW searching (#1041)
  src/lib/Behat/Component/UniversalDiscoveryWidget.php
Labels: Ready for review

#1031 IBX-7294: Gracefully handle missing user's thumbnail image
  src/bundle/Resources/views/themes/admin/ui/component/user_thumbnail/user_thumbnail.html.twig
Labels: Bug, QA approved

#1069 IBX-7415: [Subitems] As a User I want to see columns dependant on focus mode
  src/bundle/ui-dev/src/modules/sub-items/sub.items.module.js
Labels: QA approved, Ready for QA
