Repository ibexa/admin-ui, pull requests merged in 2023-10, with the labels that each got.

#918 IBX-6638: Provided tooltips for breadcrumbs in the Content View
  src/bundle/Resources/views/themes/admin/ui/breadcrumbs.html.twig
Labels: Improvement, QA approved

#932 Add page builder tests
  .github/workflows/browser-tests.yaml
Labels: Ready for review

#931 [CI] Increased job count for Behat
  .github/workflows/browser-tests.yaml
Labels: Ready for review

#922 Behat actions usage
  src/lib/Behat/Component/Fields/ContentRelationSingle.php
  src/lib/Behat/Component/SubItemsList.php
  src/lib/Behat/Component/Table/TableRow.php
  src/lib/Behat/Page/ContentTypeUpdatePage.php
  src/lib/Behat/Page/RoleUpdatePage.php
Labels: Ready for review

#911 IBX-6599: New grid view item design
  src/bundle/Resources/public/scss/_grid-view-item.scss
  src/bundle/Resources/public/scss/ui/modules/universal-discovery/_grid.scss
  src/bundle/Resources/views/themes/admin/ui/component/grid_view/grid_view_item.html.twig
  src/bundle/ui-dev/src/modules/sub-items/components/grid-view/grid.view.item.component.js
  src/bundle/ui-dev/src/modules/universal-discovery/components/grid-view/grid.view.item.js
Labels: QA approved

#926 Overwrote ContentTypeData::isNew method
  phpstan-baseline.neon
  src/lib/Form/Data/ContentTypeData.php
  tests/lib/FieldType/FieldTypeFormMapperDispatcherTest.php
  tests/lib/Form/Data/ContentTypeDataTest.php
  tests/lib/Form/Processor/ContentTypeFormProcessorTest.php
  tests/lib/Validator/Constraint/UniqueContentTypeIdentifierValidatorTest.php
  tests/lib/Validator/Constraint/UniqueFieldDefinitionIdentifierValidatorTest.php
Labels: Improvement, QA approved

#933 IBX-3240: Added notice message in edit section
  src/bundle/Resources/public/scss/_content-type-edit.scss
  src/bundle/Resources/views/themes/admin/content_type/edit_section.html.twig
Labels: QA approved

#883 IBX-6249: Create toolbox with structure view & Dropzones update
  src/bundle/Resources/public/js/scripts/helpers/tooltips.helper.js
  src/bundle/Resources/public/scss/mixins/_drag-and-drop.scss
Labels: QA approved

#942 [Behat] Adjusted error message for duplicated language code
  features/standard/Languages.feature
Labels: Ready for review

#937 IBX-6635: Empty product list is not adapted to low resolution screens
  src/bundle/Resources/public/scss/_tables.scss
Labels: QA approved, Ready for MERGE

#928 IBX-6377: Wrong table color in RTE in content preview
  src/bundle/Resources/public/scss/_custom.scss
Labels: QA approved

#936 [Behat] Replaced assertion with Wait condition
  src/lib/Behat/Component/Notification.php
Labels: Ready for review

#946 [Behat] Increased timeout for subitems loading
  src/lib/Behat/Component/SubItemsList.php
Labels: Ready for review

#934 IBX-6718: Missing scroll in language dropdown
  src/bundle/ui-dev/src/modules/common/dropdown/dropdown.js
Labels: QA approved

#945 [Behat] Emulate a focused page when interacting with Richtext
  src/lib/Behat/Component/Fields/RichText.php
Labels: Ready for review

#947 [Behat] Removed duplicated folders
  features/standard/ContentManagement.feature
  features/standard/Trash.feature
Labels: Ready for review

#872 IBX-6315: Edit embedded items
  phpstan-baseline-7.4.neon
  phpstan-baseline-8.0.neon
  phpstan-baseline.neon
  src/bundle/Controller/Permission/LanguageLimitationController.php
  src/bundle/Resources/config/routing.yaml
  src/bundle/Resources/config/services/components.yaml
  src/bundle/Resources/config/services/controllers.yaml
  src/bundle/Resources/config/services/permissions.yaml
  src/bundle/Resources/config/services/ui_config/common.yaml
  src/bundle/Resources/encore/ibexa.js.config.js
  src/bundle/Resources/public/js/scripts/admin.location.view.js
  src/bundle/Resources/public/js/scripts/core/multilevel.popup.menu.js
  src/bundle/Resources/public/js/scripts/embedded.item.actions.js
  src/bundle/Resources/public/js/scripts/fieldType/ezobjectrelationlist.js
  src/bundle/Resources/public/scss/_multilevel-popup-menu.scss
  src/bundle/Resources/public/scss/fieldType/edit/_ezobjectrelationlist.scss
  src/bundle/Resources/public/scss/ibexa.scss
  src/bundle/Resources/translations/ibexa_content.en.xliff
  src/bundle/Resources/translations/ibexa_multilevel_popup_menu.en.xliff
  src/bundle/Resources/views/themes/admin/ui/component/embedded_item_actions/embedded_item_actions.html.twig
  src/bundle/Resources/views/themes/admin/ui/component/multilevel_popup_menu/multilevel_popup_menu_branch.html.twig
  src/bundle/Resources/views/themes/admin/ui/component/multilevel_popup_menu/multilevel_popup_menu_item.html.twig
  src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezrichtext.html.twig
  src/bundle/Resources/views/themes/admin/ui/field_type/edit/relation_base.html.twig
  src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
  src/bundle/Resources/views/themes/admin/ui/layout.html.twig
  src/bundle/Resources/views/themes/admin/ui/layout_content_after.html.twig
  src/bundle/Templating/Twig/EmbeddedItemEditFormExtension.php
  src/contracts/Permission/PermissionCheckerInterface.php
  src/lib/Permission/LimitationResolver.php
  src/lib/Permission/LimitationResolverInterface.php
  src/lib/Permission/PermissionChecker.php
  tests/bundle/Templating/Twig/EmbeddedItemEditFormExtensionTest.php
  tests/bundle/Templating/Twig/_fixtures/render_embedded_item_edit_form/ibexa_render_embedded_item_edit_form.test
  tests/lib/Permission/LimitationResolverTest.php
  tests/lib/Permission/PermissionCheckerTest.php
Labels: Improvement, QA approved

#941 IBX-6459: Fixed eztext preview in content structure
  src/bundle/Resources/public/scss/_field-group.scss
  src/bundle/Resources/public/scss/_page-title.scss
Labels: QA approved

#939 IBX-6729: Drafts should be removed from user menu
  src/bundle/Resources/translations/ibexa_menu.en.xliff
  src/lib/Menu/UserMenuBuilder.php
Labels: QA approved

#914 IBX-6597: Content type pickers are inconsistent
  src/bundle/Resources/public/js/scripts/sidebar/btn/location.create.js
  src/bundle/Resources/public/scss/_extra-actions.scss
  src/bundle/Resources/translations/locationview.en.xliff
  src/bundle/Resources/translations/universal_discovery_widget.en.xliff
  src/bundle/Resources/views/themes/admin/content/widget/content_create.html.twig
  src/bundle/ui-dev/src/modules/universal-discovery/components/content-create-button/content.create.button.js
  src/bundle/ui-dev/src/modules/universal-discovery/components/content-create-widget/content.create.widget.js
  src/lib/Behat/Component/ContentTypePicker.php
  src/lib/Behat/Page/ContentViewPage.php
Labels: Bug, QA approved

#944 IBX-6517: Search form for activity log
  src/bundle/Resources/public/js/scripts/core/dropdown.js
Labels: Bug, Ready for review

#957 IBX-6475: fix transaltions
  src/bundle/Resources/views/themes/admin/content/widget/content_create.html.twig
Labels: Bug, QA approved

#880 IBX-6250: Redesign PB Config panel
  src/bundle/Resources/encore/ibexa.js.config.js
  src/bundle/Resources/public/js/scripts/admin.anchor.navigation.js
  src/bundle/Resources/public/js/scripts/admin.form.tabs.validation.js
  src/bundle/Resources/public/js/scripts/fieldType/ezgmaplocation.js
  src/bundle/Resources/public/scss/_anchor-navigation.scss
  src/bundle/Resources/public/scss/_buttons.scss
  src/bundle/Resources/public/scss/_dropdown.scss
  src/bundle/Resources/public/scss/_inputs.scss
  src/bundle/Resources/public/scss/_main-container.scss
  src/bundle/Resources/public/scss/_switcher.scss
  src/bundle/Resources/public/scss/_tabs.scss
  src/bundle/Resources/views/themes/admin/ui/anchor_navigation_menu.html.twig
  src/bundle/Resources/views/themes/admin/ui/component/tab/tabs_header.html.twig
  src/bundle/Resources/views/themes/admin/ui/component/tab/tabs_tab_warning_icon.html.twig
  src/bundle/Resources/views/themes/admin/ui/component/tab_switcher/popup_menu.html.twig
  src/bundle/Resources/views/themes/admin/ui/component/tab_switcher/popup_menu_item.html.twig
  src/bundle/Resources/views/themes/admin/ui/menu/anchor_menu.html.twig
  src/lib/Behat/Component/Fields/RichText.php
  src/lib/Behat/Page/ContentUpdateItemPage.php
Labels: QA approved
