Repository ibexa/admin-ui, pull requests merged in 2024-08, with the labels that each got.

#1309 IBX-7936: slugify group_name
  src/bundle/Resources/views/themes/admin/content/content_view_fields.html.twig
Labels: Bug, QA approved

#1305 IBX-8554: Added checks if flatpickrDate and this.flatpickrConfig.minDate exists
  src/bundle/Resources/public/js/scripts/core/date.time.picker.js
Labels: Bug, QA approved

#1303 IBX-8527: [Hide later] Error in console when typing the time
  src/bundle/Resources/public/js/scripts/core/date.time.picker.js
Labels: Bug, QA approved

#1310 IBX-8672: User can add several tags with the same tag name
  src/bundle/ui-dev/src/modules/common/taggify/taggify.js
Labels: Bug, QA approved

#1296 IBX-8584: [Tags] Long tag name is not properly displayed within the field tags
  src/bundle/Resources/public/js/scripts/fieldType/ezkeyword.js
  src/bundle/Resources/public/scss/fieldType/edit/_ezkeyword.scss
  src/bundle/Resources/public/scss/fieldType/preview/_ezkeyword.scss
  src/bundle/Resources/views/themes/admin/ui/field_type/preview/content_fields.html.twig
Labels: QA approved

#1312 IBX-7550: Text is not wrapped in Payment method details
  src/bundle/Resources/public/scss/_details.scss
Labels: QA approved

#1313 IBX-8533: Dropped deprecated code
  phpstan-baseline-7.4.neon
  phpstan-baseline-8.0.neon
  phpstan-baseline.neon
  src/bundle/Controller/Content/ContentTreeController.php
  src/bundle/DependencyInjection/Configuration/Parser/AdminUiForms.php
  src/bundle/DependencyInjection/Configuration/Parser/Pagination.php
  src/bundle/DependencyInjection/IbexaAdminUiExtension.php
  src/bundle/Resources/config/ezplatform_default_settings.yaml
  src/bundle/Resources/config/services/dashboard.yaml
  src/bundle/Resources/config/services/translation.yaml
  src/bundle/Resources/config/services/universal_discovery_widget.yaml
  src/bundle/Templating/Twig/UiConfigExtension.php
  src/bundle/Templating/Twig/UserPreferencesGlobalExtension.php
  src/contracts/Permission/PermissionCheckerInterface.php
  src/contracts/UniversalDiscovery/Provider.php
  src/lib/Form/Type/Content/Draft/ContentCreateType.php
  src/lib/Menu/ContentRightSidebarBuilder.php
  src/lib/Permission/PermissionChecker.php
  src/lib/Siteaccess/NonAdminSiteaccessResolver.php
  src/lib/Siteaccess/SiteaccessResolver.php
  src/lib/Siteaccess/SiteaccessResolverInterface.php
  src/lib/Specification/AbstractSpecification.php
  src/lib/Specification/AndSpecification.php
  src/lib/Specification/Content/ContentDraftHasConflict.php
  src/lib/Specification/Content/ContentHaveAssetRelation.php
  src/lib/Specification/Content/ContentHaveUniqueRelation.php
  src/lib/Specification/ContentType/ContentTypeIsUser.php
  src/lib/Specification/ContentType/ContentTypeIsUserGroup.php
  src/lib/Specification/Location/HasChildren.php
  src/lib/Specification/Location/IsContainer.php
  src/lib/Specification/Location/IsRoot.php
  src/lib/Specification/Location/IsWithinCopySubtreeLimit.php
  src/lib/Specification/NotSpecification.php
  src/lib/Specification/OrSpecification.php
  src/lib/Specification/SiteAccess/IsAdmin.php
  src/lib/Specification/SpecificationInterface.php
  src/lib/Specification/Version/VersionHasConflict.php
  src/lib/Tab/Dashboard/PagerContentToDataMapper.php
  src/lib/Tab/LocationView/PoliciesTab.php
  src/lib/Tab/LocationView/RolesTab.php
  src/lib/Translation/Extractor/LimitationTranslationExtractor.php
  src/lib/Translation/Extractor/PolicyTranslationExtractor.php
  src/lib/UI/Dataset/ContentDraftsDataset.php
  src/lib/UI/Dataset/DatasetFactory.php
  src/lib/UI/Dataset/RelationsDataset.php
  src/lib/UI/Value/ValueFactory.php
  src/lib/UniversalDiscovery/UniversalDiscoveryProvider.php
  src/lib/Validator/Constraints/FieldTypeValidator.php
  src/lib/Validator/ValidationErrorsProcessor.php
  src/lib/View/Filter/AdminSearchViewFilter.php
  tests/lib/Permission/PermissionCheckerTest.php
  tests/lib/Translation/Extractor/LimitationTranslationExtractorTest.php
  tests/lib/Translation/Extractor/fixtures/input_policies.yaml
Labels: Ready for review

#1298 IBX-8602: Always load root location using `sudo` in the `ContentTreeController`
  phpstan-baseline-7.4.neon
  phpstan-baseline-8.0.neon
  src/bundle/Controller/Content/ContentTreeController.php
Labels: Bug, QA approved

#1314 [Behat] IBX-8638: As a QA I want to add behat coverage to user profile
  .github/workflows/browser-tests.yaml
  behat_suites.yml
  features/standard/UserProfile.feature
  src/bundle/Resources/config/services/test/feature_contexts.yaml
  src/bundle/Resources/config/services/test/pages.yaml
  src/lib/Behat/BrowserContext/NavigationContext.php
  src/lib/Behat/BrowserContext/UserProfileContext.php
  src/lib/Behat/Page/UserProfilePage.php
Labels: Ready for review

#1317 [Behat] IBX-8636: Added new tag to user profile feature
  features/standard/UserProfile.feature
Labels: Ready for review

#1322 Fixed tests
  phpstan-baseline.neon
  tests/bundle/Templating/Twig/LimitationValueRenderingExtensionTest.php
Labels: Ready for MERGE

#1319 IBX-8671: Missing notification text when removing required field
  src/bundle/Resources/public/js/scripts/admin.contenttype.edit.js
  src/bundle/Resources/public/js/scripts/helpers/request.helper.js
  src/bundle/Resources/translations/messages.en.xliff
Labels: Bug, QA approved

#1290 IBX-8433: Added content tree children filtering
  composer.json
  src/bundle/Controller/Content/ContentTreeController.php
  src/bundle/ControllerArgumentResolver/ContentTreeChildrenQueryArgumentResolver.php
  src/bundle/Resources/config/services/controller_argument_resolvers.yaml
  src/bundle/Resources/config/services/rest.yaml
  src/lib/REST/Input/Parser/CriterionProcessor.php
  src/lib/REST/Output/ValueObjectVisitor/ContentTree/Node.php
  tests/bundle/ControllerArgumentResolver/ContentTreeChildrenQueryArgumentResolverTest.php
  tests/integration/REST/GetContentTreeChildrenTest.php
  tests/integration/Resources/REST/Schemas/ContentTreeNode.json
  tests/integration/Resources/REST/Schemas/ContentTreeNode.xsd
  tests/integration/Resources/REST/Snapshots/ContentTreeNode/filter/json/filter-by-content-type-identifier-folder-and-landing-page.json
  tests/integration/Resources/REST/Snapshots/ContentTreeNode/filter/json/filter-by-content-type-identifier-folder-and-media-location-id.json
  tests/integration/Resources/REST/Snapshots/ContentTreeNode/filter/json/filter-by-content-type-identifier-folder-or-subtree.json
  tests/integration/Resources/REST/Snapshots/ContentTreeNode/filter/json/filter-by-content-type-identifier-folder.json
  tests/integration/Resources/REST/Snapshots/ContentTreeNode/filter/json/no-filter.json
  tests/integration/Resources/REST/Snapshots/ContentTreeNode/filter/xml/no-filter.xml
Labels: Improvement, QA approved

#1327 IBX-8752: Notifications are misaligned on the list
  src/bundle/Resources/public/scss/_notifications-modal.scss
Labels: Bug, QA approved

#1315 IBX-8684: Updated spinner for UDW
  src/bundle/Resources/public/scss/ui/modules/_common.scss
  src/bundle/Resources/public/scss/ui/modules/common/_spinner.scss
  src/bundle/Resources/public/scss/ui/modules/universal-discovery/_content.meta.preview.scss
  src/bundle/Resources/public/scss/ui/modules/universal-discovery/_finder.branch.scss
  src/bundle/ui-dev/src/modules/common/spinner/spinner.js
  src/bundle/ui-dev/src/modules/universal-discovery/components/bookmarks-list/bookmarks.list.js
  src/bundle/ui-dev/src/modules/universal-discovery/components/finder/finder.branch.js
  src/bundle/ui-dev/src/modules/universal-discovery/components/search/search.js
  src/bundle/ui-dev/src/modules/universal-discovery/content.meta.preview.module.js
Labels: Bug, QA approved

#1329 IBX-8640: Weird listing of translations in search result
  src/bundle/Resources/public/scss/_search-form.scss
Labels: Bug, QA approved

#1316 IBX-8690: [DAM] Both side panels should be hidable
  src/bundle/Resources/public/img/icons/expand-left.svg
  src/bundle/Resources/public/img/icons/filters.svg
  src/bundle/ui-dev/src/modules/common/icon/inculdedIcon.js
Labels: Bug, QA approved

#1330 IBX-8709: Inconsistent padding in content view tabs
  src/bundle/Resources/public/scss/_tabs.scss
Labels: QA approved, Ready for QA

#1326 IBX-8770: Image picker tree displays Location folder while content of Images folder is displayed
  src/bundle/ui-dev/src/modules/universal-discovery/universal.discovery.module.js
Labels: Bug, QA approved

#1324 IBX-8768: Add specific prefixes to all CSS (standalone app)
  src/bundle/Resources/public/scss/_pagination.scss
  src/bundle/Resources/public/scss/mixins/_pagination.scss
Labels: Bug, QA approved

#1328 IBX-8800: Fixed subitems filtering
  src/bundle/Controller/Content/ContentTreeController.php
  src/bundle/ControllerArgumentResolver/ContentTreeChildrenQueryArgumentResolver.php
Labels: Bug, QA approved
