Repository ibexa/admin-ui, pull requests merged in 2024-03, with the labels that each got.

#1192 IBX-7540: [Password reset form] Buttons to clear input and discover password does not work
  src/bundle/Resources/encore/ibexa.js.config.js
  src/bundle/Resources/views/themes/admin/account/reset_password/index.html.twig
Labels: QA approved

#1177 IBX-7645: Added secondary-dark btn
  src/bundle/Resources/public/scss/_buttons.scss
Labels: QA approved

#1168 IBX-7194: Fix spacing in distraction free mode
  src/bundle/Resources/public/scss/fieldType/edit/_base-field.scss
Labels: QA approved

#1190 IBX-7825: UDW Blank browse tab after going from bookmarks from search
  src/bundle/ui-dev/src/modules/universal-discovery/bookmarks.tab.module.js
  src/bundle/ui-dev/src/modules/universal-discovery/search.tab.module.js
Labels: QA approved

#1170 IBX-6877: Fix multilevel popup menu in context menu's "more items" menu
  src/bundle/Resources/public/js/scripts/admin.context.menu.js
  src/bundle/Resources/views/themes/admin/ui/menu/context_menu.html.twig
Labels: QA approved

#1171 IBX-7027: Publish later button stays visible after choosing it
  src/bundle/Resources/public/js/scripts/core/multilevel.popup.menu.js
  src/bundle/Resources/public/js/scripts/sidebar/extra.actions.js
Labels: QA approved

#1179 IBX-7574: Hidded label in doughnut chart when unchecked
  src/bundle/Resources/public/js/scripts/core/doughnut.chart.js
Labels: QA approved

#1193 IBX-7613: header-user-menu UI fixes
  src/bundle/Resources/public/scss/_header-user-menu.scss
  src/bundle/Resources/public/scss/_popup-menu.scss
  src/bundle/Resources/views/themes/admin/ui/focus_mode_form.html.twig
  src/bundle/Resources/views/themes/admin/ui/menu/user.html.twig
Labels: QA approved

#1162 IBX-7185: Fix subitems upload refresh
  src/bundle/ui-dev/src/modules/multi-file-upload/multi.file.upload.module.js
Labels: QA approved

#1181 IBX-7810: Fixed type error while validating the blocks
  src/bundle/Resources/public/js/scripts/helpers/form.validation.helper.js
Labels: QA approved

#1178 IBX-7781: Upgraded toast notifications
  src/bundle/Resources/public/js/scripts/admin.notifications.js
  src/bundle/Resources/public/scss/_alerts.scss
  src/bundle/Resources/views/themes/admin/ui/component/alert/alert.html.twig
  src/bundle/ui-dev/src/modules/common/alert/alert.js
Labels: QA approved

#1183 IBX-7804: Fix dropdown offsetHeight error when ibexa-main-header not present
  src/bundle/ui-dev/src/modules/common/dropdown/dropdown.js
Labels: QA approved

#1204 IBX-7870: Fixed an old product name in "Change password" screen
  src/bundle/Resources/translations/messages.en.xliff
  src/bundle/Resources/views/themes/admin/account/reset_password/confirmation_page.html.twig
Labels: Bug, QA approved

#1182 IBX-6905: Changing Country in Corporate Account form removes current data without any warning
  src/bundle/Resources/public/scss/_mixins.scss
  src/bundle/Resources/public/scss/mixins/_spinner.scss
Labels: QA approved

#1175 IBX-7030: [UDW] Inactive edit button in grid view
  src/bundle/ui-dev/src/modules/universal-discovery/components/breadcrumbs/breadcrumbs.helpers.js
  src/bundle/ui-dev/src/modules/universal-discovery/components/breadcrumbs/breadcrumbs.js
  src/bundle/ui-dev/src/modules/universal-discovery/components/grid-view/grid.view.item.js
  src/bundle/ui-dev/src/modules/universal-discovery/components/grid-view/grid.view.js
  src/bundle/ui-dev/src/modules/universal-discovery/universal.discovery.module.js
Labels: QA approved

#1205 IBX-7856: Added possibility to add tag with Enter
  src/bundle/Resources/public/js/scripts/fieldType/ezkeyword.js
Labels: QA approved

#1215 IBX-7442: Escaped values in JS
  src/bundle/Resources/public/js/scripts/core/dropdown.js
  src/bundle/Resources/public/js/scripts/helpers/text.helper.js
Labels: Bug, QA approved, Ready for review

#1213 IBX-7959: Create content permission regression with section limitation
  dependencies.json
  src/bundle/Controller/Permission/LanguageLimitationController.php
  src/lib/Permission/LimitationResolver.php
Labels: Bug, QA approved

#1206 IBX-7607: [Sub-items] User avatar is misaligned
  src/bundle/Resources/public/scss/ui/modules/common/thumbnail.scss
Labels: QA approved

#1208 IBX-7517: [Dashboard] Quick actions: selected tags aren't fully displayed
  src/bundle/Resources/public/js/scripts/core/dropdown.js
Labels: QA approved

#867 Fixed extraction of translation
  src/lib/Menu/Admin/ContentType/AbstractContentTypeRightSidebarBuilder.php
  src/lib/Menu/Admin/ContentType/ContentTypeCreateRightSidebarBuilder.php
  src/lib/Menu/Admin/ContentType/ContentTypeEditRightSidebarBuilder.php
Labels: Bug

#1210 IBX-7926: [Distraction free mode] Black screen when user exceeds RTE field input in distraction free mode
  src/bundle/Resources/public/scss/fieldType/edit/_base-field.scss
Labels: QA approved

#1209 IBX-7901: [UDW] Removing from bookmarks content is still visible on bookmark list
  src/bundle/ui-dev/src/modules/universal-discovery/bookmarks.tab.module.js
  src/bundle/ui-dev/src/modules/universal-discovery/components/bookmarks-list/bookmarks.list.js
  src/bundle/ui-dev/src/modules/universal-discovery/components/tree-view/tree.view.js
  src/bundle/ui-dev/src/modules/universal-discovery/content.meta.preview.module.js
  src/bundle/ui-dev/src/modules/universal-discovery/helpers/locations.helper.js
  src/bundle/ui-dev/src/modules/universal-discovery/hooks/useLoadBookmarksFetch.js
Labels: QA approved

#1217 IBX-7981: [DAM] Added folder configuration
  src/bundle/Resources/config/default_parameters.yaml
  src/bundle/Resources/config/services/ui_config/common.yaml
  src/lib/UI/Config/Provider/Module/DamWidget.php
  tests/lib/UI/Config/Provider/Module/DamWidgetTest.php
Labels: Improvement, QA approved

#1227 IBX-7954: Fixed translation domain
  src/bundle/Resources/public/js/scripts/fieldType/ezimageasset.js
Labels: Bug, QA approved, Ready for review
