Repository ibexa/admin-ui, pull requests merged in 2024-12, with the labels that each got.

#1391 IBX-8445: Added storage class
  src/bundle/Resources/encore/ibexa.js.config.js
  src/bundle/Resources/public/js/scripts/core/storage.js
Labels: QA approved

#1402 IBX-9261 added translate function with correct translation domain
  src/bundle/Resources/views/themes/admin/content_type/tab/view.html.twig
Labels: QA approved

#1373 IBX-9109: Enabling TypeScript (ts-loader) with Webpack Encore
  package.json
  src/bundle/Resources/encore/ibexa.config.setup.js
  src/bundle/Resources/encore/ibexa.js.config.js
  src/bundle/Resources/public/js/scripts/admin.search.js
  src/bundle/Resources/public/ts/admin.search.ts
  src/bundle/ui-dev/src/modules/common/thumbnail/thumbnail.tsx
  src/bundle/ui-dev/src/modules/common/thumbnail/thumbnail.types.ts
  src/bundle/ui-dev/src/modules/common/types/common.d.ts
  tsconfig.eslint.json
Labels: Ready for review

#1392 IBX-9136: [ALW] UI language issue vs content language
  src/bundle/ui-dev/src/modules/universal-discovery/services/universal.discovery.service.js
Labels: Bug, QA approved, Ready for review

#1400 IBX-8937: Problem displaying the “Embed” icon in text editor
  src/bundle/Resources/public/img/ibexa-icons.svg
Labels: QA approved

#1405 IBX-9289: `NodeFactory` optimization
  src/bundle/Controller/Content/ContentTreeController.php
  src/lib/REST/Output/ValueObjectVisitor/ContentTree/Node.php
  src/lib/REST/Output/ValueObjectVisitor/ContentTree/NodeExtendedInfoVisitor.php
  src/lib/REST/Value/ContentTree/Node.php
  src/lib/REST/Value/ContentTree/NodeExtendedInfo.php
  src/lib/UI/Module/ContentTree/NodeFactory.php
  tests/integration/Resources/REST/Schemas/ContentTreeNode.json
  tests/integration/Resources/REST/Schemas/ContentTreeNode.xsd
  tests/integration/Resources/REST/Schemas/ContentTreeNodeExtendedInfo.json
  tests/integration/Resources/REST/Schemas/ContentTreeNodeExtendedInfo.xsd
  tests/integration/Resources/REST/Snapshots/ContentTreeNode/filter/json/filter-by-content-type-identifier-folder-and-landing-page.json
  tests/integration/Resources/REST/Snapshots/ContentTreeNode/filter/json/filter-by-content-type-identifier-folder-and-media-location-id.json
  tests/integration/Resources/REST/Snapshots/ContentTreeNode/filter/json/filter-by-content-type-identifier-folder-or-subtree.json
  tests/integration/Resources/REST/Snapshots/ContentTreeNode/filter/json/filter-by-content-type-identifier-folder.json
  tests/integration/Resources/REST/Snapshots/ContentTreeNode/filter/json/no-filter.json
  tests/integration/Resources/REST/Snapshots/ContentTreeNode/filter/xml/no-filter.xml
  tests/integration/Resources/REST/Snapshots/ContentTreeNodeExtendedInfo.json
  tests/integration/Resources/REST/Snapshots/ContentTreeNodeExtendedInfo.xml
  tests/integration/Resources/REST/Snapshots/ContentTreeRoot.json
Labels: Improvement, QA approved

#1406 IBX-9314: UDW's suggestions query performance optimization
  src/bundle/ui-dev/src/modules/universal-discovery/hooks/useFindLocationsByParentLocationIdFetch.js
  src/bundle/ui-dev/src/modules/universal-discovery/services/universal.discovery.service.js
Labels: Improvement, QA approved

#1361 IBX-8837: Distraction free mode: Text obstruction by toolbar's fixed position
  src/bundle/Resources/public/js/scripts/admin.distraction.free.mode.js
Labels: QA approved

#1385 IBX-9170: AI Assistant
  src/bundle/Resources/config/bazinga_js_translation.yaml
  src/bundle/Resources/public/js/scripts/admin.input.text.js
  src/bundle/Resources/public/js/scripts/helpers/config.loader.js
  src/bundle/Resources/public/js/scripts/helpers/react.helper.js
  src/bundle/Resources/public/scss/ui/modules/_common.scss
  src/bundle/Resources/public/scss/ui/modules/common/_draggable.dialog.scss
  src/bundle/Resources/public/scss/ui/modules/common/_popup.menu.scss
  src/bundle/Resources/translations/ibexa_popup_menu.en.xliff
  src/bundle/Resources/views/themes/admin/content/form_fields.html.twig
  src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
  src/bundle/ui-dev/src/modules/common/draggable-dialog/draggable.dialog.js
  src/bundle/ui-dev/src/modules/common/popup-menu/popup.menu.group.js
  src/bundle/ui-dev/src/modules/common/popup-menu/popup.menu.helper.js
  src/bundle/ui-dev/src/modules/common/popup-menu/popup.menu.item.js
  src/bundle/ui-dev/src/modules/common/popup-menu/popup.menu.js
  src/bundle/ui-dev/src/modules/common/popup-menu/popup.menu.search.js
Labels: QA approved

#1387 Made template for showing image_field in admin-ui more robust
  src/bundle/Resources/views/themes/admin/ui/field_type/preview/content_fields.html.twig
Labels: Ready for QA
