Repository ibexa/admin-ui, pull requests merged in 2024-02, with the labels that each got.

#1134 IBX-7153: Fix context menu popup buttons disabled state
  src/bundle/Resources/public/js/scripts/admin.context.menu.js
Labels: QA approved

#1075 IBX-7278: Changed HTML form to symfony one
  src/bundle/Controller/ContentController.php
  src/bundle/Resources/config/services/forms.yaml
  src/bundle/Resources/views/themes/admin/content/content_preview.html.twig
  src/lib/Form/Type/ChoiceList/Loader/SiteAccessPreviewChoiceLoader.php
  src/lib/Form/Type/Preview/SiteAccessChoiceType.php
Labels: QA approved

#1147 IBX-7448: Fixed wrong used of name instead of identifier for siteaccess form dropdown value
  src/lib/Form/Type/ChoiceList/Loader/SiteAccessPreviewChoiceLoader.php
Labels: QA approved

#1141 Renamed ImagePicker config provider to DamWidget
  src/bundle/Resources/config/default_parameters.yaml
  src/bundle/Resources/config/services/ui_config/common.yaml
  src/lib/UI/Config/Provider/Module/DamWidget.php
  tests/lib/UI/Config/Provider/Module/DamWidgetTest.php
Labels: Improvement, QA approved

#1144 IBX-7675: Added showImageFilters parameter to DamWidget config provider
  src/lib/UI/Config/Provider/Module/DamWidget.php
  tests/lib/UI/Config/Provider/Module/DamWidgetTest.php
Labels: Bug, QA approved

#1153 For 4.6 IBX-7495 Fix user profile image width responsive, rebased PR 1109 for main branch.
  src/bundle/Resources/public/scss/_user-thumbnail.scss
Labels: QA approved

#1145 IBX-7191: Fix clickable preview - disabled pointer events
  src/bundle/Resources/public/scss/_preview.scss
Labels: QA approved

#1137 IBX-7606: [Site context] Site dropdown changes width after entering a search term
  src/bundle/Resources/public/js/scripts/core/dropdown.js
Labels: QA approved

#1139 IBX-6815: [REST] Fixed isBookmarked property in load-subtree response
  .gitignore
  composer.json
  phpstan-baseline.neon
  phpunit.integration.xml
  src/lib/UI/Module/ContentTree/NodeFactory.php
  tests/integration/AdminUiIbexaTestKernel.php
  tests/integration/REST/BaseAdminUiRestWebTestCase.php
  tests/integration/REST/PostPostLoadSubtreeTest.php
  tests/integration/Resources/REST/InputPayloads/ContentTreeLoadSubtreeRequest.json
  tests/integration/Resources/REST/Schemas/ContentTreeRoot.json
  tests/integration/Resources/REST/Snapshots/ContentTreeRoot.json
  tests/integration/Resources/ibexa_test_config.yaml
  tests/integration/Resources/routing.yaml
  tests/integration/SetupValidationTest.php
  tests/integration/bootstrap.php
Labels: Bug, QA approved, Ready for MERGE, Ready for review

#1132 IBX-7667: Added support for search by ContentNameCriterion
  src/bundle/ui-dev/src/modules/universal-discovery/hooks/useSearchByQueryFetch.js
Labels: Improvement, QA approved

#1152 IBX-7680: Wrong empty screen after no search results
  src/bundle/Resources/public/scss/_search-form.scss
  src/bundle/Resources/public/scss/mixins/_search-form-no-results.scss
  src/bundle/Resources/public/scss/ui/modules/universal-discovery/_search.scss
Labels: Bug, QA approved

#1129 IBX-7304: Exposed pathString property in load-subtree REST response
  src/lib/REST/Output/ValueObjectVisitor/ContentTree/Node.php
  src/lib/REST/Value/ContentTree/Node.php
  src/lib/UI/Module/ContentTree/NodeFactory.php
  tests/integration/Resources/REST/Snapshots/ContentTreeRoot.json
Labels: Bug, QA approved, Ready for MERGE, Ready for review

#1151 IBX-7189: [Sub-items] Background for a white row in a table changes to gray when clicked on
  src/bundle/Resources/public/scss/ui/modules/sub-items-list/_table.view.item.scss
Labels: QA approved

#1149 IBX-7365: Changed order of admin menu items
  src/lib/Menu/MainMenuBuilder.php
Labels: Bug, QA approved

#1146 IBX-7472: Set view to empty file, when uri value is empty
  src/bundle/Resources/views/themes/admin/ui/field_type/edit/binary_base.html.twig
Labels: QA approved

#1159 IBX-7738: Changed query selector string for selector anchor
  src/bundle/Resources/public/js/scripts/core/adaptive.items.js
Labels: QA approved

#1160 IBX-7744: Update Ibexa logo
  src/bundle/Resources/public/img/favicon-16x16.png
  src/bundle/Resources/public/img/favicon-32x32.png
  src/bundle/Resources/public/img/favicon.ico
  src/bundle/Resources/public/img/ibexa-logo.svg
  src/bundle/Resources/public/img/ibexa-wordmark.svg
  src/bundle/Resources/views/themes/admin/ui/footer.html.twig
Labels: QA approved

#1127 IBX-7555: User profile updated UI for summary
  src/bundle/Resources/public/scss/_alerts.scss
  src/bundle/Resources/public/scss/_details.scss
  src/bundle/Resources/public/scss/_user-profile.scss
  src/bundle/Resources/translations/ibexa_admin_ui.en.xliff
  src/bundle/Resources/views/themes/admin/account/profile/view.html.twig
  src/bundle/Resources/views/themes/admin/ui/component/alert/alert.html.twig
  src/bundle/Resources/views/themes/admin/ui/component/details/details.html.twig
  src/bundle/ui-dev/src/modules/common/alert/alert.js
Labels: QA approved

#1167 IBX-7773: Fix Sub-items sorting order form vertical alignment
  src/bundle/Resources/public/scss/_dropdown.scss
  src/bundle/Resources/views/themes/admin/content/tab/details.html.twig
  src/bundle/Resources/views/themes/admin/ui/component/dropdown/dropdown.html.twig
Labels: QA approved

#1174 Added missing IbexaNotificationsBundle dependency in integration test stack
  composer.json
  tests/integration/AdminUiIbexaTestKernel.php
Labels: Bug, Ready for review

#1172 IBX-7677: Remove markedLocationId reset to null from useSearchByQueryFetch
  src/bundle/ui-dev/src/modules/universal-discovery/components/search/search.js
  src/bundle/ui-dev/src/modules/universal-discovery/hooks/useSearchByQueryFetch.js
Labels: QA approved

#1140 IBX-7655: Added root and starting location id for richtext embeded image UDW config
  src/bundle/Resources/config/universal_discovery_widget.yaml
Labels: Bug, QA approved

#1131 IBX-7526: Added cutomizable block name to content blocks
  src/bundle/Resources/views/themes/admin/ui/dashboard/block/all.html.twig
  src/bundle/Resources/views/themes/admin/ui/dashboard/block/me.html.twig
Labels: QA approved

#1158 IBX-7720: Fixed content-type not highlighted in COTF
  src/bundle/ui-dev/src/modules/universal-discovery/components/content-create-widget/content.create.widget.js
Labels: QA approved

#1180 IBX-7802: Fix React multi-select dropdown checkbox lack of onChange prop error
  src/bundle/ui-dev/src/modules/common/dropdown/dropdown.js
Labels: QA approved

#1176 IBX-7637: [User settings] Enabled/Disabled labels should be in upper case
  src/bundle/Resources/translations/ibexa_user_settings.en.xliff
  src/bundle/Resources/views/themes/admin/ui/component/details/details.html.twig
  src/lib/Behat/Page/UserSettingsPage.php
  src/lib/UserSetting/Autosave.php
  src/lib/UserSetting/InContextTranslation.php
Labels: QA approved

#1187 IBX-7690: [Full view] Exit full view should redirect user to View tab, not Fields
  src/bundle/Resources/public/js/scripts/admin.location.tab.js
Labels: QA approved

#1188 IBX-7209: Clear results button in UDW Search
  src/bundle/Resources/public/scss/ui/modules/universal-discovery/_search.scss
  src/bundle/Resources/translations/ibexa_universal_discovery_widget.en.xliff
  src/bundle/ui-dev/src/modules/universal-discovery/components/search/search.js
  src/bundle/ui-dev/src/modules/universal-discovery/universal.discovery.module.js
Labels: QA approved

#1154 IBX-7671: [Content structure] Two different behaviour by clicking create from context menu and from action main button
  src/bundle/Resources/public/js/scripts/sidebar/btn/location.create.js
  src/bundle/Resources/public/js/scripts/sidebar/instant.filter.js
  src/bundle/Resources/views/themes/admin/content/widget/content_create.html.twig
  src/bundle/Resources/views/themes/admin/content/widget/instant_filter_group_template.html.twig
  src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
  src/bundle/ui-dev/src/modules/universal-discovery/hooks/useFindLocationsByParentLocationIdFetch.js
  src/bundle/ui-dev/src/modules/universal-discovery/services/universal.discovery.service.js
Labels: QA approved

#1150 IBX-7612: [Dark theme] Wrong UI in main menu
  src/bundle/Resources/public/img/ibexa-icons.svg
  src/bundle/Resources/public/img/icons/expand-left.svg
  src/bundle/Resources/public/scss/_custom.scss
  src/bundle/Resources/public/scss/_custom.tooltip.scss
  src/bundle/Resources/public/scss/_main-header.scss
  src/bundle/Resources/public/scss/_main-menu.scss
  src/bundle/Resources/public/scss/_popup-menu.scss
  src/bundle/Resources/views/themes/admin/ui/menu/main.html.twig
  src/bundle/Resources/views/themes/admin/ui/menu/main_2nd_level.html.twig
  src/lib/Menu/MainMenuBuilder.php
  tests/lib/Menu/MainMenuBuilerTest.php
Labels: QA approved

#1165 IBX-7196: Fix distraction free mode btn styling in richtext editor
  src/bundle/Resources/public/scss/fieldType/edit/_base-field.scss
  src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
Labels: QA approved

#1166 IBX-7214: Remove distraction free mode exit btn unnecessary tooltip
  src/bundle/Resources/translations/ibexa_admin_ui.en.xliff
  src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
Labels: QA approved
