Repository ibexa/admin-ui, pull requests merged in 2024-01, with the labels that each got.

#1070 IBX-7167: Added tooltip option to popup
  src/bundle/ui-dev/src/modules/common/popup/popup.component.js
Labels: QA approved

#1035 IBX-7222: Added 4px line to dropzone placeholder
  src/bundle/Resources/public/scss/mixins/_drag-and-drop.scss
Labels: QA approved

#1047 IBX-7037: Added check if user has permission to change password
  src/bundle/Resources/translations/messages.en.xliff
  src/bundle/Resources/views/themes/admin/account/settings/list.html.twig
Labels: Bug, QA approved

#1091 [Behat] Adapted tests after redirect change
  features/personas/ChangePassword.feature
  src/lib/Behat/Page/UserSettingsPage.php
Labels: Ready for review

#1044 IBX-7121: Added asterisks in password user settings
  src/bundle/Resources/views/themes/admin/account/settings/list.html.twig
Labels: Bug, QA approved

#1024 IBX-7184: [Sub-items] For lower resolution list header actions ale not fully visible
  src/bundle/Resources/public/scss/ui/modules/sub-items-list/_main.scss
  src/bundle/ui-dev/src/modules/multi-file-upload/multi.file.upload.module.js
  src/bundle/ui-dev/src/modules/sub-items/sub.items.module.js
Labels: QA approved

#1095 IBX-7489: Fix user settings password change Discard button link
  src/lib/EventListener/UserPasswordChangeRightSidebarListener.php
  src/lib/Menu/UserPasswordChangeRightSidebarBuilder.php
Labels: QA approved

#1049 IBX-7050: Frontend: top bar and change site switcher
  src/bundle/Resources/public/js/scripts/admin.user.menu.js
  src/bundle/Resources/public/js/scripts/core/popup.menu.js
  src/bundle/Resources/public/scss/_global-search.scss
  src/bundle/Resources/public/scss/_header-user-menu.scss
  src/bundle/Resources/public/scss/_main-header.scss
  src/bundle/Resources/public/scss/_user-mode-badge.scss
  src/bundle/Resources/public/scss/ibexa.scss
  src/bundle/Resources/translations/ibexa_user_mode_badge.en.xliff
  src/bundle/Resources/views/themes/admin/ui/layout.html.twig
  src/bundle/Resources/views/themes/admin/ui/user_mode_badge.html.twig
  src/lib/Behat/Component/UpperMenu.php
Labels: QA approved

#1058 IBX-7357: Adjusted Authors & Details tabs to modes specification
  src/lib/Behat/Component/UpperMenu.php
  src/lib/Behat/Page/ContentViewPage.php
  src/lib/Tab/LocationView/AuthorsTab.php
  src/lib/Tab/LocationView/DetailsTab.php
  tests/lib/Tab/LocationView/AuthorsTabVisibilityTest.php
Labels: QA approved

#1073 IBX-7154: Fixed breadcrumb styles in autocomplete
  src/bundle/Resources/public/js/scripts/admin.search.autocomplete.content.js
  src/bundle/Resources/public/scss/_global-search.scss
  src/bundle/Resources/views/themes/admin/ui/global_search_autocomplete_content_item.html.twig
  src/bundle/Resources/views/themes/admin/ui/global_search_autocomplete_content_template.html.twig
Labels: QA approved

#1072 IBX-7420: Added total number of results to autocomplete
  src/bundle/Resources/public/js/scripts/admin.search.autocomplete.js
  src/bundle/Resources/public/scss/_global-search.scss
  src/bundle/Resources/translations/ibexa_search.en.xliff
  src/bundle/Resources/views/themes/admin/ui/global_search.html.twig
Labels: QA approved

#1101 IBX-6539: Fixed "Last modified" and "Created" filters style in global search
  src/bundle/Resources/public/scss/_filters.scss
Labels: QA approved

#1052 IBX-7367: Added config provider for image picker
  src/bundle/Resources/config/default_parameters.yaml
  src/bundle/Resources/config/services/ui_config/common.yaml
  src/lib/UI/Config/Provider/Module/ImagePicker.php
  tests/lib/UI/Config/Provider/Module/ImagePickerTest.php
Labels: Improvement, QA approved

#1033 IBX-7271: Missing suggestions while creating content in COFT
  src/bundle/ui-dev/src/modules/universal-discovery/components/content-create-widget/content.create.widget.js
  src/bundle/ui-dev/src/modules/universal-discovery/hooks/useFindLocationsByParentLocationIdFetch.js
  src/bundle/ui-dev/src/modules/universal-discovery/services/universal.discovery.service.js
  src/bundle/ui-dev/src/modules/universal-discovery/universal.discovery.module.js
Labels: QA approved

#1080 IBX-6679: Disabled delete action in field definition form when translating content type
  src/bundle/Resources/views/themes/admin/content_type/field_definition.html.twig
Labels: QA approved

#1039 Remove unused LeftSidebar menu
  phpstan-baseline.neon
  src/bundle/Resources/config/services/menu.yaml
  src/bundle/Resources/translations/ibexa_menu.en.xliff
  src/lib/Menu/Event/ConfigureMenuEvent.php
  src/lib/Menu/LeftSidebarBuilder.php
Labels: QA approved

#1088 IBX-7052: UDW gets closed after switching Bookmarks view into grid view
  src/bundle/ui-dev/src/modules/universal-discovery/universal.discovery.module.js
Labels: Ready for QA

#1076 IBX-7352: Aligned focus mode labels in user settings with design
  src/bundle/Resources/translations/ibexa_user_settings.en.xliff
  src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
  src/lib/UserSetting/FocusMode.php
Labels: QA approved

#1103 IBX-7496: Fix centering double input separator
  src/bundle/Resources/public/scss/_double-input-range.scss
Labels: QA approved

#1067 IBX-6724: Simplify context menus
  features/standard/ContentType.feature
  src/bundle/Resources/public/js/scripts/core/multilevel.popup.menu.js
  src/bundle/Resources/public/scss/_buttons.scss
  src/bundle/Resources/public/scss/_split-button.scss
  src/bundle/Resources/translations/ibexa_menu.en.xliff
  src/bundle/Resources/views/themes/admin/account/change_password/index.html.twig
  src/bundle/Resources/views/themes/admin/account/settings/update.html.twig
  src/bundle/Resources/views/themes/admin/ui/anchor_navigation_menu.html.twig
  src/bundle/Resources/views/themes/admin/ui/component/multilevel_popup_menu/multilevel_popup_menu_branch.html.twig
  src/bundle/Resources/views/themes/admin/ui/component/multilevel_popup_menu/multilevel_popup_menu_group.html.twig
  src/bundle/Resources/views/themes/admin/ui/component/split_btn/split_btn.html.twig
  src/lib/Menu/Admin/ContentType/ContentTypeEditRightSidebarBuilder.php
  src/lib/Menu/UserSetting/UserSettingUpdateRightSidebarBuilder.php
Labels: QA approved

#1110 IBX-7448: Fixed siteaccess dropdown values
  src/bundle/Resources/views/themes/admin/content/content_preview.html.twig
Labels: QA approved

#1083 IBX-7119, IBX-7171, IBX-7123: Corrected Headers inconsistency in Account settings
  src/bundle/Resources/public/scss/_edit-header.scss
  src/bundle/Resources/translations/ibexa_user_change_password.en.xliff
  src/bundle/Resources/translations/ibexa_user_settings.en.xliff
  src/bundle/Resources/views/themes/admin/account/change_password/index.html.twig
  src/bundle/Resources/views/themes/admin/account/settings/update.html.twig
  src/lib/Behat/Page/ChangePasswordPage.php
  src/lib/Behat/Page/UserSettingsPage.php
Labels: Bug, Ready for QA

#1121 IBX-7563: Redirect only if user profile is enabled
  src/lib/EventListener/UserProfileListener.php
Labels: QA approved

#1125 IBX-7598: Added missing import for scss file
  src/bundle/Resources/public/scss/ibexa.scss
Labels: Bug, Ready for QA

#1090 IBX-7465: Updated Noto Sans fonts
  src/bundle/Resources/public/font/NotoSans-Bold.ttf
  src/bundle/Resources/public/font/NotoSans-BoldItalic.ttf
  src/bundle/Resources/public/font/NotoSans-Italic.ttf
  src/bundle/Resources/public/font/NotoSans-Regular.ttf
  src/bundle/Resources/public/font/NotoSans-SemiBold.ttf
  src/bundle/Resources/public/font/NotoSans-SemiBoldItalic.ttf
Labels: QA approved, Ready for review

#1126 IBX-7595: Removed :focus styles for ibexa-header-user-menu
  src/bundle/Resources/public/scss/_header-user-menu.scss
Labels: Bug, QA approved

#1119 IBX-7493: Dropped dependency on user variable in user_thumbnail
  src/bundle/Resources/views/themes/admin/ui/component/user_thumbnail/user_thumbnail.html.twig
Labels: QA approved

#1130 IBX-7168: Changed label to `create user` based on parent location
  src/bundle/Resources/translations/ibexa_menu.en.xliff
  src/bundle/Resources/translations/ibexa_user_settings.en.xliff
  src/lib/Behat/Page/ContentViewPage.php
  src/lib/Menu/ContentRightSidebarBuilder.php
Labels: QA approved

#1138 IBX-7656: Changed quick action to work with fragment
  src/bundle/Resources/public/js/scripts/sidebar/extra.actions.js
Labels: Bug, QA approved

#1142 IBX-7604: Fixed checkbox toggler
  src/bundle/Resources/public/scss/_inputs.scss
Labels: Bug, QA approved

#1143 IBX-7674: Skip redirection to user profile if user CT is edited via configuration view
  src/bundle/Resources/config/services/events.yaml
  src/lib/EventListener/UserProfileListener.php
Labels: Bug, QA approved
