Repository ibexa/admin-ui, pull requests merged in 2024-09, with the labels that each got.

#1339 [PHPStan] Fixed errors after PHPStan update
  phpstan-baseline.neon
  src/lib/Form/EventListener/BuildPathFromRootListener.php
Labels: Ready for review

#1337 IBX-8685: Create a new URL alias modal - too narrow spaces above labels
  src/bundle/Resources/public/scss/_custom-url-form.scss
Labels: Bug, QA approved

#1332 IBX-8789: Fix double handling of file upload on window d&d
  src/bundle/ui-dev/src/modules/multi-file-upload/components/drop-area/drop.area.component.js
  src/bundle/ui-dev/src/modules/multi-file-upload/multi.file.upload.module.js
Labels: QA approved

#1345 IBX-8182: Uppercase letter for bookmarks for bookmarks tooltip
  src/bundle/Resources/translations/ibexa_locationview.en.xliff
  src/bundle/Resources/views/themes/admin/account/bookmarks/toggle_switch.html.twig
Labels: Bug, Ready for QA

#1341 IBX-8717: Added display inline block to .ibexa-middle-ellipsis__name-ellipsized
  src/bundle/Resources/public/scss/_middle-ellipsis.scss
Labels: Bug, QA approved

#1323 IBX-8722: Added Bookmarsk to Image Picker
  src/bundle/Resources/public/scss/_mixins.scss
  src/bundle/Resources/public/scss/mixins/_tab-selector.scss
  src/bundle/Resources/public/scss/ui/modules/universal-discovery/_tab.selector.scss
  src/bundle/ui-dev/src/modules/universal-discovery/hooks/useSearchByQueryFetch.js
Labels: QA approved

#1344 Extracted menu builder from ProductCatalog package
  src/bundle/Resources/config/services/menu.yaml
  src/bundle/Resources/translations/ibexa_menu.en.xliff
  src/contracts/Menu/AbstractBuilder.php
  src/contracts/Menu/AbstractFormContextMenuBuilder.php
  src/contracts/Menu/CopyFormContextMenuBuilder.php
  src/contracts/Menu/CreateFormContextMenuBuilder.php
  src/contracts/Menu/MenuItemFactoryInterface.php
  src/contracts/Menu/UpdateFormContextMenuBuilder.php
  src/lib/Menu/Admin/ContentType/ContentTypeGroupCreateRightSidebarBuilder.php
  src/lib/Menu/Admin/ContentType/ContentTypeGroupEditRightSidebarBuilder.php
  src/lib/Menu/Admin/Language/LanguageCreateRightSidebarBuilder.php
  src/lib/Menu/Admin/Language/LanguageEditRightSidebarBuilder.php
  src/lib/Menu/Admin/ObjectState/ObjectStateGroupCreateRightSidebarBuilder.php
  src/lib/Menu/Admin/ObjectState/ObjectStateGroupEditRightSidebarBuilder.php
  src/lib/Menu/Admin/Role/RoleCopyRightSidebarBuilder.php
  src/lib/Menu/Admin/Role/RoleCreateRightSidebarBuilder.php
  src/lib/Menu/Admin/Role/RoleEditRightSidebarBuilder.php
  src/lib/Menu/ContentCreateRightSidebarBuilder.php
  src/lib/Menu/ContentEditAnchorMenuBuilder.php
  src/lib/Menu/ContentEditRightSidebarBuilder.php
  src/lib/Menu/ContentRightSidebarBuilder.php
  src/lib/Menu/ContentTypeEditAnchorMenuBuilder.php
  src/lib/Menu/ContentTypeRightSidebarBuilder.php
  src/lib/Menu/MainMenuBuilder.php
  src/lib/Menu/MenuItemFactory.php
  src/lib/Menu/SectionCreateRightSidebarBuilder.php
  src/lib/Menu/SectionEditRightSidebarBuilder.php
  src/lib/Menu/TrashRightSidebarBuilder.php
  src/lib/Menu/URLEditRightSidebarBuilder.php
  src/lib/Menu/URLWildcardEditRightSidebarBuilder.php
  src/lib/Menu/UserMenuBuilder.php
  src/lib/Menu/UserPasswordChangeRightSidebarBuilder.php
  src/lib/Menu/UserSetting/UserSettingUpdateRightSidebarBuilder.php
  tests/lib/Menu/MainMenuBuilerTest.php
Labels: QA approved, Ready for review

#1340 IBX-8132: [UDW] For object relation field user can remove selected item from bookmarks
  src/bundle/Resources/translations/ibexa_universal_discovery_widget.en.xliff
  src/bundle/ui-dev/src/modules/universal-discovery/components/selected-locations/selected.locations.js
  src/bundle/ui-dev/src/modules/universal-discovery/components/tab/tab.js
  src/lib/Translation/Extractor/JavaScriptFileVisitor.php
Labels: Bug, QA approved

#1347 Added filter script
  src/bundle/Resources/public/js/scripts/filters.action.btns.js
Labels: QA approved

#1346 IBX-8130: UDW gets closed while switching into Grid view
  src/bundle/ui-dev/src/modules/universal-discovery/universal.discovery.module.js
Labels: Bug, QA approved

#1343 IBX-8829: [Richtext] Distraction free mode button should be disabled when richtext field isn't translatable
  src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
Labels: Bug, QA approved

#1350 [Behat] IBX-7780: taxonomy behat fails fix
  src/lib/Behat/Component/CreateNewPopup.php
Labels: Ready for review

#1352 IBX-8955: [Page builder] 500 occurs after adding certain blocks
  src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
Labels: QA approved

#1349 IBX-8943: [Image field] Alternative text retains after deleting asset
  src/bundle/Resources/public/js/scripts/fieldType/base/base-preview-field.js
Labels: QA approved

#1353 IBX-7447: Hide allowed extensions if no extensions are defined in image fieldtype
  src/bundle/Resources/views/themes/admin/ui/field_type/edit/binary_base.html.twig
Labels: QA approved
