Repository ibexa/admin-ui, pull requests merged in 2024-05, with the labels that each got.

#1260 IBX-8254: Added check if relation is accessible
  src/bundle/Resources/views/themes/admin/content/tab/relations/table_relations.html.twig
Labels: Bug, QA approved

#1198 Get getNotificationsStatusLoop interval from YAML config
  src/bundle/Controller/NotificationController.php
  src/bundle/DependencyInjection/Configuration/Parser/Notifications.php
  src/bundle/Resources/config/ezplatform_default_settings.yaml
  src/bundle/Resources/public/js/scripts/admin.notifications.modal.js
  src/bundle/Resources/views/themes/admin/account/notifications/list.html.twig
Labels: Doc needed, QA approved, Ready for review

#1161 IBX-7653: Allow filtering for loadSubtreeAction
  phpstan-baseline.neon
  src/bundle/Controller/Content/ContentTreeController.php
  src/lib/REST/Input/Parser/ContentTree/LoadSubtreeRequest.php
  src/lib/REST/Value/ContentTree/LoadSubtreeRequest.php
  src/lib/UI/Module/ContentTree/NodeFactory.php
Labels: QA approved

#1248 IBX-8142: removed depreacated code
  src/bundle/Resources/public/js/scripts/admin.anchor.sections.navigation.js
  src/bundle/Resources/public/js/scripts/admin.contenttype.relation.default.location.js
  src/bundle/Resources/public/js/scripts/admin.middle.ellipsis.js
  src/bundle/Resources/public/js/scripts/core/base.chart.js
  src/bundle/Resources/public/js/scripts/core/tag.view.select.js
  src/bundle/Resources/public/js/scripts/helpers/config.loader.js
  src/bundle/Resources/public/js/scripts/helpers/form.error.helper.js
  src/bundle/Resources/public/js/scripts/helpers/middle.ellipsis.js
  src/bundle/Resources/public/scss/_alerts.scss
  src/bundle/Resources/public/scss/_content-type-edit.scss
  src/bundle/Resources/public/scss/_footer.scss
  src/bundle/Resources/public/scss/_mixins.scss
  src/bundle/Resources/public/scss/ibexa.scss
  src/bundle/Resources/public/scss/mixins/_drag-and-drop.scss
  src/bundle/Resources/public/scss/mixins/_font.scss
  src/bundle/Resources/translations/ibexa_content.en.xliff
  src/bundle/Resources/translations/messages.en.xliff
  src/bundle/Resources/views/themes/admin/account/change_password/form_fields.html.twig
  src/bundle/Resources/views/themes/admin/account/change_password/index.html.twig
  src/bundle/Resources/views/themes/admin/account/forgot_password/index.html.twig
  src/bundle/Resources/views/themes/admin/account/forgot_password/index_with_login.html.twig
  src/bundle/Resources/views/themes/admin/account/form_fields.html.twig
  src/bundle/Resources/views/themes/admin/account/reset_password/index.html.twig
  src/bundle/Resources/views/themes/admin/content/edit/content_header.html.twig
  src/bundle/Resources/views/themes/admin/content/edit/content_header_tooltip.html.twig
  src/bundle/Resources/views/themes/admin/content/location_view.html.twig
  src/bundle/Resources/views/themes/admin/ui/footer.html.twig
  src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
  src/bundle/ui-dev/src/modules/multi-file-upload/components/drop-area/drop.area.component.js
  src/bundle/ui-dev/src/modules/multi-file-upload/components/upload-list/upload.item.component.js
  src/bundle/ui-dev/src/modules/multi-file-upload/helpers/text.helper.js
Labels: Ready for QA

#1261 IBX-8144: [Rebranding] Remove compatibility layer from webpack encore
  docs/field-type-validator-usage.md
  src/bundle/Resources/public/js/scripts/core/toggle.button.js
  src/bundle/Resources/public/js/scripts/toggle.button.state.toggle.js
  src/bundle/Resources/public/scss/_flatpickr.scss
  src/bundle/Resources/views/themes/admin/ui/layout.html.twig
Labels: QA approved

#1255 IBX-8184: Implemented reusable RichText validator
  src/bundle/Resources/public/js/scripts/fieldType/ezrichtext.js
  src/bundle/Resources/public/js/scripts/fieldType/validator/richtext-validator.js
  src/bundle/Resources/public/js/scripts/helpers/form.validation.helper.js
Labels: Bug, QA approved

#1211 IBX-7542: Fixed elements position under main-container-edit
  src/bundle/Resources/public/scss/_main-container.scss
Labels: QA approved

#1266 Regenerated PHPStan baseline
  phpstan-baseline.neon
Labels: Ready for review

#1264 IBX-8140: Enabled authenticator manager-based security
  src/bundle/Resources/config/services/controllers.yaml
Labels: Feature, Ready for review

#1249 IBX-8058: Implemented subscriber that adds content type groups to `ContentTypes` UI config event
  src/lib/Event/AddContentTypeGroupToUIConfigEvent.php
  src/lib/UI/Config/Provider/ContentTypes.php
Labels: Improvement, QA approved
