Repository ibexa/admin-ui, pull requests merged in 2024-07, with the labels that each got.

#1284 IBX-8322: Fixed lack of redirections to last visited pages after successful authentication
  src/bundle/Resources/views/themes/admin/ui/component/user_thumbnail/user_thumbnail.html.twig
  src/bundle/Resources/views/themes/admin/ui/menu/user.html.twig
Labels: Bug, QA approved

#1279 IBX-8449: [Main menu] Selected area of second level menu item changes after expanding/collapsing
  src/bundle/Resources/public/js/scripts/sidebar/main.menu.js
  src/bundle/Resources/public/scss/_main-menu.scss
  src/bundle/Resources/views/themes/admin/ui/menu/main_2nd_level.html.twig
Labels: QA approved

#1280 [Behat] IBX-8216: As a QA I want to cover Focus mode with a Visual Test
  src/lib/Behat/Component/LeftMenu.php
Labels: Ready for review

#1287 IBX-8485: Redirect after creating location should point to referer location
  src/bundle/Controller/LocationController.php
Labels: Bug, QA approved

#1288 IBX-8396: Moved pointer-events inside iframe body for scrolling to work properly
  src/bundle/Resources/public/js/scripts/admin.preview.js
  src/bundle/Resources/public/scss/_preview.scss
Labels: Bug, QA approved

#1120 IBX-7558: Added posibiity to close navbar menu
  .github/workflows/browser-tests.yaml
  features/personas/AddLocation.feature
  features/personas/SubtreeEditor.feature
  src/bundle/Resources/public/js/scripts/sidebar/main.menu.js
  src/lib/Behat/BrowserContext/NavigationContext.php
  src/lib/Behat/Component/LeftMenu.php
Labels: QA approved

#1291 IBX-8477: Removed check whether the draft belongs to the user
  src/bundle/Resources/views/themes/admin/content/tab/versions/table.html.twig
Labels: Bug, QA approved

#1297 [Behat] Added broken tag to addLocation and subtreeEditor features
  features/personas/AddLocation.feature
  features/personas/SubtreeEditor.feature
Labels: Ready for review

#1281 IBX-7745: State for icon in search has wrong color
  src/bundle/Resources/public/scss/_global-search.scss
  src/bundle/Resources/views/themes/admin/ui/component/input_text.html.twig
Labels: Bug, QA approved

#1292 IBX-8545: Trash icon jump when uploading long name files
  src/bundle/Resources/public/scss/ui/modules/muti-file-upload/_upload.item.scss
Labels: Bug, QA approved

#1289 IBX-8137: Dropped SwiftMailer in integration tests setup
  tests/integration/AdminUiIbexaTestKernel.php
Labels: Rebase required

#1299 IBX-8588: [Image Picker] Clicking edit button on multi-file upload modal causes an error
  src/bundle/ui-dev/src/modules/multi-file-upload/components/upload-list/upload.item.component.js
  src/bundle/ui-dev/src/modules/multi-file-upload/components/upload-list/upload.list.component.js
  src/bundle/ui-dev/src/modules/multi-file-upload/components/upload-popup/upload.popup.component.js
  src/bundle/ui-dev/src/modules/multi-file-upload/multi.file.upload.module.js
Labels: Bug, QA approved

#1300 IBX-8321: Taxonomy entry assignment field: Gap when empty
  src/bundle/Resources/public/js/scripts/core/tag.view.select.js
  src/bundle/Resources/public/scss/_tag-view-select.scss
  src/bundle/Resources/views/themes/admin/ui/component/tag_view_select/tag_view_select.html.twig
Labels: Bug, QA approved

#1282 IBX-8110: ALW images edit
  src/bundle/Resources/config/default_parameters.yaml
  src/bundle/Resources/public/img/ibexa-icons.svg
  src/bundle/Resources/public/img/icons/circle-close.svg
  src/bundle/Resources/public/img/icons/download.svg
  src/bundle/Resources/public/img/icons/duplicate.svg
  src/bundle/Resources/public/img/icons/edit.svg
  src/bundle/Resources/public/img/icons/qa-form.svg
  src/bundle/Resources/public/img/icons/system-information.svg
  src/bundle/Resources/public/js/scripts/helpers/content.type.helper.js
  src/bundle/Resources/public/scss/_tag.scss
  src/bundle/Resources/public/scss/ui/modules/_common.scss
  src/bundle/Resources/public/scss/ui/modules/common/_popup.scss
  src/bundle/Resources/public/scss/ui/modules/common/_taggify.scss
  src/bundle/ui-dev/src/modules/common/icon/inculdedIcon.js
  src/bundle/ui-dev/src/modules/common/tag/tag.js
  src/bundle/ui-dev/src/modules/common/taggify/taggify.js
  src/bundle/ui-dev/src/modules/multi-file-upload/services/multi.file.upload.service.js
  src/bundle/ui-dev/src/modules/universal-discovery/content.edit.tab.module.js
  src/bundle/ui-dev/src/modules/universal-discovery/hooks/useSelectedLocationsReducer.js
  src/bundle/ui-dev/src/modules/universal-discovery/universal.discovery.module.js
Labels: Feature, QA approved

#1308 IBX-8670: Clear input icon is too big
  src/bundle/Resources/views/themes/admin/ui/component/input_text.html.twig
Labels: Bug, QA approved

#1304 IBX-8649: [UDW] can't reselect initial language
  src/bundle/ui-dev/src/modules/universal-discovery/components/filters/filters.js
Labels: QA approved
