Repository ibexa/admin-ui, pull requests merged in 2024-06, with the labels that each got.

#1271 IBX-8344: Added endpoint for download images
  composer.json
  src/bundle/Controller/DownloadImageController.php
  src/bundle/Resources/config/default_parameters.yaml
  src/bundle/Resources/config/routing_rest.yaml
  src/bundle/Resources/config/services/controllers.yaml
  src/lib/UI/Config/Provider/Module/DamWidget.php
  tests/lib/UI/Config/Provider/Module/DamWidgetTest.php
Labels: Feature, QA approved

#1212 IBX-7911: Replaced usage of magic getters for load subtree code paths
  src/lib/EventListener/InContextTranslationListener.php
  src/lib/Siteaccess/AbstractSiteaccessPreviewVoter.php
  src/lib/Siteaccess/SiteaccessResolver.php
  src/lib/Strategy/ContentTypeThumbnailStrategy.php
  src/lib/UI/Module/ContentTree/NodeFactory.php
Labels: Bug, QA approved, Rebase required

#1262 IBX-8280: Move previewableTranslations info to node extended info endpoint
  src/bundle/Controller/Content/ContentTreeController.php
  src/lib/REST/Output/ValueObjectVisitor/ContentTree/Node.php
  src/lib/REST/Output/ValueObjectVisitor/ContentTree/NodeExtendedInfoVisitor.php
  src/lib/REST/Value/ContentTree/Node.php
  src/lib/REST/Value/ContentTree/NodeExtendedInfo.php
  src/lib/UI/Module/ContentTree/NodeFactory.php
  tests/integration/REST/GetContentTreeExtendedInfoTest.php
  tests/integration/Resources/REST/Schemas/ContentTreeNodeExtendedInfo.json
  tests/integration/Resources/REST/Schemas/ContentTreeNodeExtendedInfo.xsd
  tests/integration/Resources/REST/Snapshots/ContentTreeNodeExtendedInfo.json
  tests/integration/Resources/REST/Snapshots/ContentTreeNodeExtendedInfo.xml
  tests/integration/Resources/REST/Snapshots/ContentTreeRoot.json
Labels: QA approved

#1265 IBX-8195: Content items are displayed multiple times in UDW after adding item to bookmarks
  src/bundle/Resources/public/scss/ui/modules/universal-discovery/_finder.branch.scss
  src/bundle/ui-dev/src/modules/universal-discovery/components/finder/finder.branch.js
  src/bundle/ui-dev/src/modules/universal-discovery/hooks/useFindLocationsByParentLocationIdFetch.js
Labels: QA approved

#1272 IBX-8360: Removed event listener for drop and dragover when showing upload popup
  src/bundle/ui-dev/src/modules/multi-file-upload/multi.file.upload.module.js
Labels: Bug, QA approved

#1270 [Behat] IBX-5092: Removed test files
  behat_suites.yml
  src/lib/Behat/TestFiles/binary1.txt
  src/lib/Behat/TestFiles/binary2.txt
  src/lib/Behat/TestFiles/image1.png
  src/lib/Behat/TestFiles/image2.png
  src/lib/Behat/TestFiles/imageasset1.png
  src/lib/Behat/TestFiles/imageasset2.png
  src/lib/Behat/TestFiles/video1.mp4
  src/lib/Behat/TestFiles/video2.mp4
Labels: Ready for review

#1256 IBX-7808: Removed duplicated svg in ibexa-icons
  src/bundle/Resources/public/img/ibexa-icons.svg
Labels: Ready for QA

#1220 IBX-7198: Updated ibexa label margin, form styling in edit and create
  src/bundle/Resources/public/scss/_adaptive-filters.scss
  src/bundle/Resources/public/scss/_anchor-navigation.scss
  src/bundle/Resources/public/scss/_content-edit.scss
  src/bundle/Resources/public/scss/_content-type-edit.scss
  src/bundle/Resources/public/scss/_custom.scss
  src/bundle/Resources/public/scss/_details.scss
  src/bundle/Resources/public/scss/_edit-header.scss
  src/bundle/Resources/public/scss/_extra-actions.scss
  src/bundle/Resources/public/scss/_field-group.scss
  src/bundle/Resources/public/scss/_general.scss
  src/bundle/Resources/public/scss/_header.scss
  src/bundle/Resources/public/scss/_labels.scss
  src/bundle/Resources/public/scss/_main-container.scss
  src/bundle/Resources/public/scss/_search-form.scss
  src/bundle/Resources/public/scss/_tables.scss
  src/bundle/Resources/public/scss/_tabs.scss
  src/bundle/Resources/public/scss/fieldType/edit/_base-field.scss
  src/bundle/Resources/public/scss/fieldType/edit/_ezobjectrelationlist.scss
  src/bundle/Resources/public/scss/fieldType/edit/_ezuser.scss
  src/bundle/Resources/public/scss/mixins/_containers.scss
  src/bundle/Resources/public/scss/mixins/_modals.scss
  src/bundle/Resources/public/scss/ui/modules/sub-items-list/_main.scss
  src/bundle/Resources/views/themes/admin/account/change_password/form_fields.html.twig
  src/bundle/Resources/views/themes/admin/account/change_password/index.html.twig
  src/bundle/Resources/views/themes/admin/account/settings/update.html.twig
  src/bundle/Resources/views/themes/admin/content/create/create.html.twig
  src/bundle/Resources/views/themes/admin/content/edit/edit.html.twig
  src/bundle/Resources/views/themes/admin/content/edit_macros.html.twig
  src/bundle/Resources/views/themes/admin/content/form_fields.html.twig
  src/bundle/Resources/views/themes/admin/content_type/content_type_group/create.html.twig
  src/bundle/Resources/views/themes/admin/content_type/content_type_group/edit.html.twig
  src/bundle/Resources/views/themes/admin/content_type/create.html.twig
  src/bundle/Resources/views/themes/admin/content_type/edit.html.twig
  src/bundle/Resources/views/themes/admin/language/create.html.twig
  src/bundle/Resources/views/themes/admin/language/edit.html.twig
  src/bundle/Resources/views/themes/admin/object_state/add.html.twig
  src/bundle/Resources/views/themes/admin/object_state/edit.html.twig
  src/bundle/Resources/views/themes/admin/object_state/object_state_group/add.html.twig
  src/bundle/Resources/views/themes/admin/object_state/object_state_group/edit.html.twig
  src/bundle/Resources/views/themes/admin/section/create.html.twig
  src/bundle/Resources/views/themes/admin/section/update.html.twig
  src/bundle/Resources/views/themes/admin/ui/edit_header.html.twig
  src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
  src/bundle/Resources/views/themes/admin/user/create.html.twig
  src/bundle/Resources/views/themes/admin/user/edit.html.twig
  src/bundle/Resources/views/themes/admin/user/role/add.html.twig
  src/bundle/Resources/views/themes/admin/user/role/copy.html.twig
  src/bundle/Resources/views/themes/admin/user/role/edit.html.twig
Labels: QA approved

#935 Allowed overwriting component id using tag property for RendererInterface::renderSingle
  src/bundle/DependencyInjection/Compiler/ComponentPass.php
Labels: Improvement, Ready for review

#1276 IBX-8163: Upload modal files display too short file names
  src/bundle/Resources/public/scss/ui/modules/muti-file-upload/_progress.bar.scss
  src/bundle/Resources/public/scss/ui/modules/muti-file-upload/_upload.item.scss
Labels: Bug, QA approved

#1275 IBX-8392: [Image picker] Sorting by name and date does not work
  src/bundle/ui-dev/src/modules/universal-discovery/components/search/search.js
  src/bundle/ui-dev/src/modules/universal-discovery/hooks/useSearchByQueryFetch.js
  src/bundle/ui-dev/src/modules/universal-discovery/services/universal.discovery.service.js
Labels: Bug, QA approved, Ready for MERGE

#1254 IBX-8109: [ALW] folders management
  src/bundle/Resources/public/img/icons/about.svg
  src/bundle/Resources/public/img/icons/approved.svg
  src/bundle/Resources/public/img/icons/create.svg
  src/bundle/Resources/public/img/icons/notice.svg
  src/bundle/Resources/public/img/icons/options.svg
  src/bundle/Resources/public/js/scripts/helpers/content.type.helper.js
  src/bundle/Resources/public/js/scripts/helpers/context.helper.js
  src/bundle/Resources/public/js/scripts/helpers/notification.helper.js
  src/bundle/Resources/public/scss/_custom.scss
  src/bundle/Resources/public/scss/mixins/_modals.scss
  src/bundle/Resources/public/scss/ui/modules/universal-discovery/_main.scss
  src/bundle/ui-dev/src/modules/common/icon/inculdedIcon.js
  src/bundle/ui-dev/src/modules/common/popup/popup.component.js
  src/bundle/ui-dev/src/modules/content-tree/components/list-item/list.item.component.js
  src/bundle/ui-dev/src/modules/multi-file-upload/components/upload-popup/upload.popup.component.js
  src/bundle/ui-dev/src/modules/universal-discovery/components/breadcrumbs/breadcrumbs.js
  src/bundle/ui-dev/src/modules/universal-discovery/components/content-create-widget/content.create.widget.js
  src/bundle/ui-dev/src/modules/universal-discovery/content.meta.preview.module.js
  src/bundle/ui-dev/src/modules/universal-discovery/universal.discovery.module.js
Labels: Feature, QA approved

#1240 IBX-8001: Fixed section limitation
  src/bundle/Resources/views/themes/admin/user/role_assignment/create.html.twig
Labels: QA approved

#1278 IBX-8424: Fixed criterions build for hook useSearchByQueryFetch
  src/bundle/ui-dev/src/modules/universal-discovery/hooks/useSearchByQueryFetch.js
Labels: Bug, QA approved
