Repository ibexa/admin-ui, pull requests merged in 2024-04, with the labels that each got.

#1219 IBX-7989: Unable to access content group fields in Page Builder interface form view
  src/bundle/Resources/public/scss/_anchor-navigation.scss
  src/bundle/Resources/translations/ibexa_fields_groups.en.xliff
  src/bundle/Resources/views/themes/admin/content/components/meta_fields.html.twig
  src/bundle/Resources/views/themes/admin/content/edit/edit.html.twig
  src/bundle/Resources/views/themes/admin/ui/component/anchor_navigation/section_group.html.twig
Labels: Bug, QA approved

#1229 IBX-7627: Implemented theme colors for toolbox
  src/bundle/Resources/public/scss/mixins/_drag-and-drop.scss
Labels: QA approved

#1235 IBX-8086: Updated infographic for empty graph
  src/bundle/Resources/public/img/ibexa-empty-graph.svg
Labels: QA approved

#1197 IBX-7717: UDW location endpoint additional permission info
  composer.json
  phpunit.integration.xml
  src/bundle/Controller/Content/ContentTreeController.php
  src/bundle/Resources/config/routing_rest.yaml
  src/bundle/Resources/config/services/rest.yaml
  src/bundle/Resources/public/scss/ui/modules/common/_popup.scss
  src/contracts/Permission/PermissionCheckerInterface.php
  src/lib/REST/Output/ValueObjectVisitor/ContentTree/NodeExtendedInfoVisitor.php
  src/lib/REST/Value/ContentTree/NodeExtendedInfo.php
  src/lib/UniversalDiscovery/UniversalDiscoveryProvider.php
  tests/integration/AdminUiIbexaTestKernel.php
  tests/integration/REST/BaseAdminUiRestWebTestCase.php
  tests/integration/REST/GetContentTreeExtendedInfoTest.php
  tests/integration/Resources/REST/Schemas/ContentTreeNodeExtendedInfo.json
  tests/integration/Resources/REST/Schemas/ContentTreeNodeExtendedInfo.xsd
  tests/integration/Resources/REST/Snapshots/ContentTreeNodeExtendedInfo.json
  tests/integration/Resources/REST/Snapshots/ContentTreeNodeExtendedInfo.xml
Labels: QA approved, Ready for review

#1238 Fixed merge 4.5 into 4.6
  src/lib/REST/Value/ContentTree/NodeExtendedInfo.php
  tests/integration/AdminUiIbexaTestKernel.php
Labels: Bug, Ready for review

#1232 IBX-8009: Unnecessary tooltips in udw bookmarks
  src/bundle/ui-dev/src/modules/universal-discovery/components/bookmarks-list/bookmarks.list.js
Labels: QA approved

#1236 IBX-8089: Added configuration for image management
  src/bundle/Resources/config/default_parameters.yaml
  src/bundle/Resources/config/services/ui_config/common.yaml
  src/lib/UI/Config/Provider/Module/DamWidget.php
  tests/lib/UI/Config/Provider/Module/DamWidgetTest.php
Labels: Doc needed, Improvement, QA approved

#1231 IBX-7981: Improved folder configuration
  src/bundle/Resources/config/default_parameters.yaml
  src/bundle/Resources/config/services/ui_config/common.yaml
  src/lib/UI/Config/Provider/Module/DamWidget.php
  tests/lib/UI/Config/Provider/Module/DamWidgetTest.php
Labels: Doc needed, Improvement, QA approved

#1246 Fixed PHPStan
  phpstan-baseline.neon
Labels: Improvement, Ready for review

#1184 IBX-7816: ALW files upload
  phpstan-baseline.neon
  src/bundle/Resources/encore/ibexa.js.config.js
  src/bundle/Resources/public/img/icons/about-info.svg
  src/bundle/Resources/public/img/icons/trash.svg
  src/bundle/Resources/public/img/icons/upload.svg
  src/bundle/Resources/public/img/icons/warning.svg
  src/bundle/Resources/public/js/scripts/admin.location.view.js
  src/bundle/Resources/public/js/scripts/helpers/context.helper.js
  src/bundle/Resources/public/scss/ui/modules/common/_tooltip.popup.scss
  src/bundle/Resources/public/scss/ui/modules/muti-file-upload/_drop.area.scss
  src/bundle/Resources/public/scss/ui/modules/muti-file-upload/_progress.bar.scss
  src/bundle/Resources/public/scss/ui/modules/muti-file-upload/_upload.item.scss
  src/bundle/Resources/public/scss/ui/modules/muti-file-upload/_upload.list.scss
  src/bundle/Resources/public/scss/ui/modules/muti-file-upload/_upload.popup.scss
  src/bundle/Resources/translations/ibexa_content.en.xliff
  src/bundle/Resources/translations/ibexa_multi_file_upload.en.xliff
  src/bundle/Resources/views/themes/admin/ui/component/sub_items/multifile_upload.html.twig
  src/bundle/ui-dev/src/modules/common/icon/icon.js
  src/bundle/ui-dev/src/modules/common/icon/inculdedIcon.js
  src/bundle/ui-dev/src/modules/common/pagination/pagination.button.js
  src/bundle/ui-dev/src/modules/common/tooltip-popup/tooltip.popup.component.js
  src/bundle/ui-dev/src/modules/multi-file-upload/components/drop-area/drop.area.component.js
  src/bundle/ui-dev/src/modules/multi-file-upload/components/progress-bar/progress.bar.component.js
  src/bundle/ui-dev/src/modules/multi-file-upload/components/upload-list/upload.item.component.js
  src/bundle/ui-dev/src/modules/multi-file-upload/components/upload-list/upload.list.component.js
  src/bundle/ui-dev/src/modules/multi-file-upload/components/upload-popup/upload.popup.component.js
  src/bundle/ui-dev/src/modules/multi-file-upload/config.loader.js
  src/bundle/ui-dev/src/modules/multi-file-upload/multi.file.upload.module.js
  src/bundle/ui-dev/src/modules/multi-file-upload/services/multi.file.upload.service.js
  src/lib/UI/Config/Provider/ContentTypeMappings.php
Labels: QA approved

#1226 IBX-7839: Fixed loading items when scrolling
  src/bundle/Resources/public/scss/ui/modules/universal-discovery/_finder.branch.scss
  src/bundle/ui-dev/src/modules/universal-discovery/components/finder/finder.branch.js
  src/bundle/ui-dev/src/modules/universal-discovery/hooks/useFindLocationsByParentLocationIdFetch.js
Labels: QA approved

#1239 IBX-8011: Refine bookmarking in Content Tree
  src/bundle/Resources/public/js/scripts/admin.location.bookmark.js
Labels: QA approved

#1244 IBX-8075: User (group) re-selection not possible after failed role assignment
  src/bundle/Resources/views/themes/admin/user/role_assignment/create.html.twig
Labels: Bug, QA approved, Ready for review

#1241 IBX-8059: Validate Content Type's Group in the Content Type view action
  src/bundle/Controller/ContentTypeController.php
Labels: Bug, QA approved

#1195 IBX-7833: Added pagination to relation tab
  phpstan-baseline.neon
  src/bundle/Controller/ContentViewController.php
  src/bundle/Resources/config/ezplatform_default_settings.yaml
  src/bundle/Resources/views/themes/admin/content/location_view.html.twig
  src/bundle/Resources/views/themes/admin/content/tab/relations/tab.html.twig
  src/lib/Pagination/Pagerfanta/RelationAdapter.php
  src/lib/Tab/LocationView/RelationsTab.php
  src/lib/UI/Dataset/RelationListDataset.php
Labels: Bug, QA approved

#1251 IBX-7537: Expanded AdminUpdateItemPage by textarea input
  src/lib/Behat/Page/AdminUpdateItemPage.php
Labels: Ready for review

#1252 IBX-8119: Upgraded minimum PHP version to 8.3
  .github/workflows/ci.yaml
  .github/workflows/frontend-ci.yaml
  composer.json
Labels: Ready for review

#1230 IBX-7808: Added content type free icons
  src/bundle/Resources/public/img/ibexa-icons.svg
  src/bundle/Resources/public/img/icons/content-type-content.svg
  src/bundle/Resources/public/img/icons/customer-type.svg
  src/bundle/Resources/public/img/icons/dashboard-type.svg
  src/bundle/Resources/public/img/icons/media-type.svg
  src/bundle/Resources/public/img/icons/user-type.svg
Labels: QA approved

#1216 IBX-7699: Empty chart state updated
  src/bundle/Resources/public/scss/_empty-chart.scss
Labels: QA approved
