Repository ibexa/admin-ui, pull requests merged in 2025-08, with the labels that each got.

#1663 IBX-10417: Removed redundant information in header create/edit
  src/bundle/Resources/translations/ibexa_content_edit.en.xliff
  src/bundle/Resources/translations/ibexa_user_create.en.xliff
  src/bundle/Resources/translations/ibexa_user_edit.en.xliff
  src/bundle/Resources/views/themes/admin/ui/on_the_fly/create_on_the_fly.html.twig
  src/bundle/Resources/views/themes/admin/ui/on_the_fly/edit_on_the_fly.html.twig
  src/bundle/Resources/views/themes/admin/user/create.html.twig
  src/bundle/Resources/views/themes/admin/user/edit.html.twig
Labels: Bug, QA approved

#1523 IBX-9730: Taxonomy subtree limitation
  src/bundle/Resources/views/themes/admin/ui/component/tag_view_select/tag_view_select.html.twig
Labels: Feature, QA approved

#1669 IBX-9727: Added type-hints and adapted codebase to PHP8+ within contracts
  phpstan-baseline.neon
  src/bundle/Controller/UniversalDiscoveryController.php
  src/contracts/Controller/Controller.php
  src/contracts/Event/AutosaveEvents.php
  src/contracts/Event/ContentEditEvent.php
  src/contracts/Event/ContentOnTheFlyEvents.php
  src/contracts/Event/ContentProxyCreateEvent.php
  src/contracts/Event/ContentProxyTranslateEvent.php
  src/contracts/Event/FieldDefinitionMappingEvent.php
  src/contracts/Event/FocusModeChangedEvent.php
  src/contracts/Event/FormActionEvent.php
  src/contracts/Event/FormEvents.php
  src/contracts/Event/UserOnTheFlyEvents.php
  src/contracts/Form/ActionDispatcher/ActionDispatcherInterface.php
  src/contracts/Form/Data/FormMapper/FormDataMapperInterface.php
  src/contracts/Form/DataMapper/DataMapperInterface.php
  src/contracts/Menu/AbstractActionBuilder.php
  src/contracts/Menu/AbstractBuilder.php
  src/contracts/Menu/AbstractFormContextMenuBuilder.php
  src/contracts/Menu/MenuItemFactoryInterface.php
  src/contracts/Notification/NotificationHandlerInterface.php
  src/contracts/Notification/TranslatableNotificationHandlerInterface.php
  src/contracts/Permission/PermissionCheckerInterface.php
  src/contracts/REST/ApplicationConfigRestGeneratorInterface.php
  src/contracts/REST/ApplicationConfigRestResolverInterface.php
  src/contracts/Tab/AbstractControllerBasedTab.php
  src/contracts/Tab/AbstractEventDispatchingTab.php
  src/contracts/Tab/AbstractRouteBasedTab.php
  src/contracts/Tab/AbstractTab.php
  src/contracts/Tab/OrderedTabInterface.php
  src/contracts/Tab/TabInterface.php
  src/contracts/UI/Action/EventDispatcherInterface.php
  src/contracts/UI/Action/FormUiActionMapperInterface.php
  src/contracts/UI/Action/UiActionEventInterface.php
  src/contracts/UI/Config/ProviderInterface.php
  src/contracts/UniversalDiscovery/Provider.php
  src/lib/REST/Generator/ProfilePictureFieldConfigRestGenerator.php
  src/lib/REST/Generator/UserConfigRestGenerator.php
  src/lib/UI/Config/Provider/ScopeParameterBasedValue.php
  src/lib/UI/Config/Provider/UserContentTypes.php
  src/lib/UI/Config/Provider/Value.php
  tests/lib/Tab/TabRegistryTest.php
Labels: Ready for review

#1656 IBX-8698: Fixed user profile group navigation
  src/bundle/Resources/public/js/scripts/admin.anchor.navigation.js
Labels: QA approved

#1620 IBX-8111: Validated file mime type for multi file upload without specified location mapping
  src/bundle/ui-dev/src/modules/multi-file-upload/services/multi.file.upload.service.js
Labels: Bug, QA approved

#1661 IBX-10398: Modal close btn styles update
  src/bundle/Resources/public/scss/_modals.scss
  src/bundle/Resources/views/themes/admin/ui/component/modal/modal.html.twig
Labels: Ready for QA

#1654 IBX-6662: Handled re-positioning date picker on scroll
  src/bundle/Resources/public/js/scripts/core/date.time.picker.js
Labels: QA approved

#1664 IBX-10138: Not animated arrow in the drop-down in the share dialog
  src/bundle/Resources/public/js/scripts/core/popup.menu.js
Labels: Bug, QA approved

#1678 IBX-10454:[UDW] Error when open bookmarks
  src/bundle/ui-dev/src/modules/universal-discovery/components/bookmarks-list/bookmarks.list.js
Labels: Bug, QA approved

#1677 IBX-10507: Add PHP 8.4 to CI testing matrix
  .github/workflows/ci.yaml
  phpstan-baseline.neon
  src/lib/Form/DataTransformer/LanguageTransformer.php
  tests/lib/Form/DataTransformer/ContentInfoTransformerTest.php
  tests/lib/Form/DataTransformer/LanguageTransformerTest.php
Labels: Ready for review

#1689 IBX-10412: COTF - fixed confirm label
  src/bundle/Resources/translations/ibexa_content_create.en.xliff
  src/bundle/Resources/translations/ibexa_content_edit.en.xliff
  src/bundle/Resources/views/themes/admin/ui/on_the_fly/create_on_the_fly.html.twig
  src/bundle/Resources/views/themes/admin/ui/on_the_fly/edit_on_the_fly.html.twig
Labels: Bug, QA approved
