Repository ibexa/admin-ui, pull requests merged in 2025-03, with the labels that each got.

#1472 Refactored ContentType::isContainer property to method changed
  phpstan-baseline.neon
  src/bundle/Controller/LocationController.php
  src/lib/Form/Data/FormMapper/ContentTypeDraftMapper.php
  src/lib/Menu/ContentCreateRightSidebarBuilder.php
  src/lib/Menu/ContentRightSidebarBuilder.php
  src/lib/Specification/Location/IsContainer.php
  src/lib/UI/Config/Provider/ContentTypes.php
  tests/lib/Form/Data/FormMapper/ContentTypeDraftMapperTest.php
  tests/lib/Validator/Constraint/LocationIsContainerValidatorTest.php
Labels: Ready for review

#1473 IBX-9629: Improve the map location (ezgmaplocation) fields layout.
  src/bundle/Resources/public/scss/fieldType/edit/_ezgmaplocation.scss
Labels: Bug, QA approved

#1478 IBX-9338: Updated buttons label for create content on the fly
  src/bundle/Resources/translations/ibexa_content_create.en.xliff
  src/bundle/Resources/translations/ibexa_content_edit.en.xliff
  src/bundle/Resources/views/themes/admin/ui/on_the_fly/create_on_the_fly.html.twig
  src/bundle/Resources/views/themes/admin/ui/on_the_fly/edit_on_the_fly.html.twig
Labels: Bug, QA approved

#1435 IBX-9361: The 'x' button in search for Clients list doesn't work
  src/bundle/Resources/public/js/scripts/filters.action.btns.js
Labels: QA approved

#1466 IBX-9628: ellipsized details content
  src/bundle/Resources/encore/ibexa.js.config.js
  src/bundle/Resources/public/img/ibexa-icons.svg
  src/bundle/Resources/public/img/icons/arrow-down.svg
  src/bundle/Resources/public/js/scripts/details.js
  src/bundle/Resources/public/scss/_details.scss
  src/bundle/Resources/translations/ibexa_admin_ui.en.xliff
  src/bundle/Resources/views/themes/admin/ui/component/details/details.html.twig
Labels: QA approved, Tests update

#1446 IBX-9462: React Popup fix
  src/bundle/ui-dev/src/modules/common/popup/popup.component.js
Labels: QA approved, Ready for review

#1484 IBX-9649: Sticky columns in React table
  src/bundle/ui-dev/src/modules/common/table/table.js
Labels: QA approved, Ready for review

#1488 IBX-9632: Added inLanguage parameter to URL for download file
  src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezbinaryfile.html.twig
Labels: Bug, QA approved

#1418 IBX-9217: Added URL validation
  src/bundle/Resources/public/js/scripts/fieldType/ezurl.js
Labels: Bug, QA approved, Ready for review

#1487 IBX-9659: Fix dropdown elements sticking out and search icon is not in the input
  src/bundle/Resources/public/scss/_dropdown.scss
  src/bundle/ui-dev/src/modules/common/dropdown/dropdown.js
Labels: QA approved, Ready for review

#1486 IBX-9658: Fixed removing tooltips
  src/bundle/Resources/public/js/scripts/helpers/tooltips.helper.js
Labels: QA approved, Ready for review

#1495 IBX-8760: Fixed styles for nontranslatable field notice
  src/bundle/Resources/public/scss/fieldType/edit/_base-field.scss
Labels: QA approved

#1496 IBX-9614, IBX-9585, IBX-9586: Fixed pagination after upgrading to symfony 6
  phpstan-baseline.neon
  src/bundle/Controller/ContentViewController.php
Labels: Ready for QA

#1499 IBX-9723: Relative URLs in ezurl field no longer works
  src/bundle/Resources/public/js/scripts/fieldType/ezurl.js
  src/bundle/Resources/views/themes/admin/ui/layout.html.twig
Labels: Bug, QA approved

#1510 IBX-9652: TableHeadCell checkbox fixes
  src/bundle/Resources/public/scss/_tables.scss
  src/bundle/Resources/views/themes/admin/ui/component/table/table_head_cell.html.twig
  src/bundle/ui-dev/src/modules/common/table/table.head.cell.js
  tests/integration/bootstrap.php
Labels: QA approved

#1459 IBX-8941: Added error descrition handling
  src/bundle/Resources/public/js/scripts/helpers/request.helper.js
Labels: QA approved

#1507 IBX-9717: Fix permanent discount end date saving problem
  src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
Labels: QA approved

#1506 IBX-9060: Added open mail icon
  src/bundle/Resources/public/img/ibexa-icons.svg
  src/bundle/Resources/public/img/icons/mail-open.svg
  src/bundle/Resources/public/img/icons/mail.svg
Labels: Ready for review

#1498 IBX-9689: Fixed search icon placing
  src/bundle/ui-dev/src/modules/common/popup-menu/popup.menu.search.js
Labels: QA approved

#1513 IBX-9708: Rename activate-deactivate -> deactivate
  src/bundle/Resources/public/img/ibexa-icons.svg
  src/bundle/Resources/public/img/icons/deactivate.svg
Labels: Ready for review
