Repository ibexa/admin-ui, pull requests merged in 2025-02, with the labels that each got.

#1394 IBX-3456 Collapse all button support
  src/bundle/Resources/config/bazinga_js_translation.yaml
  src/bundle/Resources/public/js/scripts/core/collapse.js
  src/bundle/Resources/public/scss/_anchor-navigation.scss
  src/bundle/Resources/public/scss/_multi-collapse.scss
  src/bundle/Resources/public/scss/ibexa.scss
  src/bundle/Resources/translations/ibexa_collapse.en.xliff
  src/bundle/Resources/views/themes/admin/ui/component/collapse_all_btn/collapse_all_btn.html.twig
Labels: QA approved

#1425 IBX-9358 Fixed discard button in number input
  src/bundle/Resources/public/js/scripts/admin.input.text.js
Labels: QA approved

#1416 IBX-9332: Add refine text support to eztext fields
  src/bundle/Resources/public/js/scripts/admin.input.text.js
  src/bundle/Resources/public/scss/_inputs.scss
  src/bundle/Resources/views/themes/admin/ui/component/input_text.html.twig
  src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
Labels: QA approved

#1436 IBX-7670: Added padding between fields
  src/bundle/Resources/views/themes/admin/language/create.html.twig
  src/bundle/Resources/views/themes/admin/language/edit.html.twig
Labels: Ready for QA

#1421 IBX-9293: Base site access choice loader on language code
  src/lib/Form/Type/ChoiceList/Loader/SiteAccessChoiceLoader.php
  src/lib/Form/Type/Preview/SiteAccessChoiceType.php
  src/lib/Menu/ContentRightSidebarBuilder.php
Labels: Bug, QA approved

#1440 IBX-9489: [OSS] UncaughtTypeError after entering 'Content structure'
  src/bundle/ui-dev/src/modules/universal-discovery/components/tree-item-toggle-selection/tree.item.toggle.selection.js
Labels: QA approved

#1442 IBX-9511: Fixed incorrect object type in PolicyValueResolver
  src/bundle/ValueResolver/PolicyValueResolver.php
  tests/bundle/ValueResolver/PolicyValueResolverTest.php
Labels: QA approved

#1431 IBX-9374: stored copied link clipboard
  src/bundle/Resources/public/scss/_custom.tooltip.scss
  src/bundle/Resources/public/scss/_mixins.scss
  src/bundle/Resources/public/scss/mixins/_tooltips.scss
Labels: Ready for review

#1445 [Behat] Fix for ContentType.feature failure
  behat_suites.yml
  features/standard/ContentType.feature
Labels: Ready for review

#1449 [Behat] Fix for Roles.feature
  features/standard/Roles.feature
Labels: Ready for review

#1451 [Behat] Fix for Sections.feature
  features/standard/Sections.feature
Labels: Ready for review

#1457 IBX-9577: Fixed fetching query data for Trash search
  phpstan-baseline.neon
  src/bundle/Controller/TrashController.php
Labels: QA approved

#1437 IBX-8306: Fixed placement of bookmark and trash icon in menu navbar
  src/bundle/Resources/views/themes/admin/ui/menu/main.html.twig
  src/bundle/Resources/views/themes/admin/ui/menu/main_base.html.twig
Labels: QA approved

#1450 IBX-8809: Fixed long name in ezimage fieldtype
  src/bundle/Resources/public/scss/fieldType/edit/_base-preview.scss
Labels: Ready for QA

#1419 IBX-9333: introduced isUpdate to reload sub-items page after actions
  src/bundle/ui-dev/src/modules/sub-items/sub.items.module.js
Labels: Bug, QA approved

#1447 IBX-9412: Fixed allowed extensions in ezimage field
  src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezimage.html.twig
Labels: QA approved

#1461 IBX-9463: Disabled field based on passed attribute
  src/bundle/Resources/views/themes/admin/ui/component/input_text.html.twig
  src/bundle/Resources/views/themes/admin/ui/component/inputs/input_date_time_picker.html.twig
  src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
Labels: QA approved

#1462 IBX-9406: Added icons collaboration and share
  src/bundle/Resources/public/img/ibexa-icons.svg
  src/bundle/Resources/public/img/icons/collaboration.svg
  src/bundle/Resources/public/img/icons/share.svg
Labels: Doc needed

#1467 Refactored SearchResult::$count to SearchResult::$totalCount deprecation
  phpstan-baseline.neon
  src/lib/Menu/TrashRightSidebarBuilder.php
Labels: Ready for review

#1471 Bump `symfony/deprecation-contracts` package
  composer.json
Labels: Ready for review

#1448 IBX-8928: Tab with [...] is visible while loading the product details.
  src/bundle/Resources/public/js/scripts/admin.location.adaptive.tabs.js
  src/bundle/Resources/public/scss/_tabs.scss
Labels: QA approved

#1464 IBX-9459: [Left menu] it is possible for the tabs in left menu to merge
  src/bundle/Resources/public/js/scripts/sidebar/main.menu.js
Labels: QA approved

#1477 IBX-9636: Pagination arrows not displayed correctly
  src/bundle/View/Template/IbexaPagerfantaTemplate.php
Labels: Bug, QA approved

#1469 IBX-9633: Fixed z-index for content map preview
  src/bundle/Resources/public/scss/fieldType/preview/_ezgmaplocation.scss
Labels: Bug, QA approved

#1433 IBX-9449: Product Picker base object selection with variants
  src/bundle/Resources/public/scss/ui/modules/universal-discovery/_search.scss
  src/bundle/Resources/public/scss/ui/modules/universal-discovery/_selected.items.panel.item.scss
  src/bundle/Resources/public/scss/ui/modules/universal-discovery/_selected.items.panel.scss
  src/bundle/ui-dev/src/modules/common/middle-ellipsis/middle.ellipsis.js
  src/bundle/ui-dev/src/modules/common/popup/popup.component.js
  src/bundle/ui-dev/src/modules/universal-discovery/components/selected-items/selected.items.panel.item.js
  src/bundle/ui-dev/src/modules/universal-discovery/components/toggle-selection/toggle.item.selection.js
  src/bundle/ui-dev/src/modules/universal-discovery/hooks/usePaginableFetch.js
  src/bundle/ui-dev/src/modules/universal-discovery/hooks/useSelectedItemsReducer.js
  src/bundle/ui-dev/src/modules/universal-discovery/universal.discovery.module.js
Labels: Ready for review

#1452 IBX-9566: Product Picker - product type filter
  src/bundle/Resources/public/scss/_dropdown.scss
Labels: Ready for review

#1458 IBX-9599: empty table row and no search results component
  src/bundle/Resources/public/scss/ui/modules/_universal.discovery.scss
  src/bundle/Resources/public/scss/ui/modules/universal-discovery/_search.no.results.scss
  src/bundle/Resources/public/scss/ui/modules/universal-discovery/_search.scss
  src/bundle/Resources/translations/ibexa_universal_discovery_widget.en.xliff
  src/bundle/ui-dev/src/modules/common/table/empty.table.body.row.js
  src/bundle/ui-dev/src/modules/universal-discovery/components/search/search.js
  src/bundle/ui-dev/src/modules/universal-discovery/components/search/search.no.results.js
Labels: Ready for review
