Repository ibexa/admin-ui, pull requests merged in 2025-09, with the labels that each got.

#1700 IBX-10567: [Share dialog] Modal backdrop fade is not removed
  src/bundle/Resources/public/js/scripts/helpers/modal.helper.js
Labels: Bug, QA approved

#1702 IBX-10617: Allowed nullable field type identifier within `ModifyFieldDefinitionsCollectionTypeExtension`
  phpstan-baseline.neon
  src/lib/Form/Type/Extension/EventSubscriber/ModifyFieldDefinitionFieldsSubscriber.php
  src/lib/Form/Type/Extension/ModifyFieldDefinitionsCollectionTypeExtension.php
  tests/lib/Form/Type/Extension/EventSubscriber/ModifyFieldDefinitionFieldsSubscriberTest.php
Labels: Bug, Ready for review

#1707 IBX-10473: Refactor custom URL form styles and templates to match the design and improve maintainability and consistency.
  src/bundle/Resources/public/scss/_custom-url-form.scss
  src/bundle/Resources/views/themes/admin/content/tab/url/modal_add_custom_url.html.twig
Labels: Ready for QA

#1717 [Behat] Fix for no draft on draft list
  src/lib/Behat/Page/DashboardPage.php
Labels: Ready for review

#1713 IBX-10427: Fixed date and datetime filters clearing
  src/bundle/Resources/public/js/scripts/filters.action.btns.js
Labels: Bug, QA approved

#1711 IBX-10274: Added fallback handling for invalid previewLanguageCode
  phpstan-baseline.neon
  src/bundle/Resources/public/js/scripts/embedded.item.actions.js
  src/lib/Form/Type/Extension/EventSubscriber/ModifyFieldDefinitionFieldsSubscriber.php
  tests/lib/Form/Type/Extension/EventSubscriber/ModifyFieldDefinitionFieldsSubscriberTest.php
Labels: QA approved

#1710 [Behat] IBX-10333 Added scenarios for hide and reveal content
  features/standard/ContentManagement.feature
  src/lib/Behat/BrowserContext/ContentViewContext.php
  src/lib/Behat/Page/ContentViewPage.php
Labels: Ready for MERGE

#1722 IBX-10659: Added verification if headerBottomRowNode is not null
  src/bundle/Resources/public/js/scripts/edit.header.js
Labels: Bug, QA approved
