Repository ibexa/admin-ui, pull requests merged in 2025-01, with the labels that each got.

#1399 IBX-8973: Discounts - initial frontend create wizard
  src/bundle/Resources/public/img/background-gray.svg
  src/bundle/Resources/views/themes/admin/ui/layout.html.twig
Labels: Ready for review

#1407 IBX-9022: price tab validation issues
  src/bundle/Resources/public/js/scripts/helpers/form.validation.helper.js
Labels: Bug, QA approved

#1414 IBX-9313: Fix fetching ContentInfo on select
  src/bundle/ui-dev/src/modules/universal-discovery/services/universal.discovery.service.js
  src/bundle/ui-dev/src/modules/universal-discovery/universal.discovery.module.js
Labels: QA approved, Ready for review

#1372 IBX-9002: Added endpoint for list users with permission info
  src/bundle/Controller/Permission/UsersWithPermissionInfoController.php
  src/bundle/Resources/config/routing.yaml
  src/bundle/Resources/config/services.yaml
  src/bundle/Resources/config/services/controllers.yaml
  src/bundle/Resources/config/services/permissions.yaml
  src/bundle/Resources/config/services/query_types.yaml
  src/contracts/Permission/PermissionCheckContextProviderInterface.php
  src/contracts/Values/PermissionCheckContext.php
  src/lib/Permission/ContextProvider/ContentItemContextProvider.php
  src/lib/Permission/Mapper/UsersWithPermissionInfoMapper.php
  src/lib/Permission/PermissionCheckContextResolver.php
  src/lib/Permission/PermissionCheckContextResolverInterface.php
  src/lib/QueryType/UserQueryType.php
  tests/integration/REST/GetUsersWithPermissionInfoTest.php
  tests/integration/Resources/ibexa.yaml
  tests/integration/Resources/routing.yaml
Labels: Feature, QA approved

#1404 IBX-9274: Context menu does not show up in 'Location' folder
  src/bundle/Resources/public/scss/ui/modules/common/_spinner.scss
  src/bundle/ui-dev/src/modules/common/spinner/spinner.js
  src/lib/REST/Output/ValueObjectVisitor/UniversalDiscovery/LocationListDataVisitor.php
Labels: Bug, QA approved

#1428 IBX-7484: unified display of hidden locations in UDW
  src/bundle/Resources/public/scss/_grid-view-item.scss
  src/bundle/Resources/public/scss/ui/modules/content-tree/_list.item.scss
  src/bundle/Resources/public/scss/ui/modules/universal-discovery/_finder.leaf.scss
  src/bundle/ui-dev/src/modules/content-tree/components/list-item/list.item.component.js
  src/bundle/ui-dev/src/modules/universal-discovery/components/finder/finder.leaf.js
  src/bundle/ui-dev/src/modules/universal-discovery/components/grid-view/grid.view.item.js
Labels: Bug, QA approved

#1409 IBX-9322: ezobjectrelationlist field allows selecting the same content multiple times
  src/bundle/Resources/public/js/scripts/fieldType/ezobjectrelationlist.js
  src/bundle/Resources/public/scss/ui/modules/universal-discovery/_grid.scss
  src/bundle/Resources/public/scss/ui/modules/universal-discovery/_selected.locations.item.scss
  src/bundle/Resources/public/scss/ui/modules/universal-discovery/_tab.scss
  src/bundle/Resources/translations/ibexa_universal_discovery_widget.en.xliff
  src/bundle/Resources/views/themes/admin/ui/field_type/edit/relation_base.html.twig
  src/bundle/ui-dev/src/modules/universal-discovery/components/content-table/content.table.item.js
  src/bundle/ui-dev/src/modules/universal-discovery/components/finder/finder.leaf.js
  src/bundle/ui-dev/src/modules/universal-discovery/components/grid-view/grid.view.item.js
  src/bundle/ui-dev/src/modules/universal-discovery/components/selected-locations/selected.locations.item.js
  src/bundle/ui-dev/src/modules/universal-discovery/components/selected-locations/selected.locations.js
  src/bundle/ui-dev/src/modules/universal-discovery/components/tab/tab.js
  src/bundle/ui-dev/src/modules/universal-discovery/components/tree-item-toggle-selection/tree.item.toggle.selection.js
  src/bundle/ui-dev/src/modules/universal-discovery/hooks/useSelectedLocationsHelpers.js
  src/bundle/ui-dev/src/modules/universal-discovery/universal.discovery.module.js
Labels: Bug, QA approved

#1430 IBX-9428: Changed margin-bottom to 0
  src/bundle/Resources/public/scss/_tabs.scss
Labels: Bug, QA approved

#1423 IBX-8945: Improved display of geolocation errors
  src/bundle/Resources/public/js/scripts/fieldType/ezgmaplocation.js
Labels: Bug, QA approved

#1424 IBX-9347: Set with to max-content and added margin-right
  src/bundle/Resources/public/scss/_user-mode-badge.scss
Labels: Bug, QA approved

#1422 IBX-9370: Aligned UDW-searchterm with main search
  src/bundle/ui-dev/src/modules/universal-discovery/hooks/useSearchByQueryFetch.js
Labels: QA approved, Ready for review
