Repository ibexa/admin-ui, pull requests merged in 2025-05, with the labels that each got.

#1535 IBX-9060: Added expand-right icon
  src/bundle/Resources/public/img/ibexa-icons.svg
  src/bundle/Resources/public/img/icons/expand-right.svg
Labels: Ready for QA

#1530 IBX-9836: Fix form help icon shrinking
  src/bundle/Resources/public/scss/_forms.scss
Labels: QA approved, Ready for review

#1537 IBX-9935: Added extensibility point for new views in subitems
  src/bundle/ui-dev/src/modules/sub-items/components/sub-items-list/sub.items.list.component.js
  src/bundle/ui-dev/src/modules/sub-items/components/view-switcher/view.switcher.component.js
  src/bundle/ui-dev/src/modules/sub-items/constants.js
  src/bundle/ui-dev/src/modules/sub-items/services/view.registry.js
  src/bundle/ui-dev/src/modules/sub-items/sub.items.module.js
Labels: Doc needed, QA approved

#1531 IBX-9926: [Collaboration] Users list for CKEditor
  src/bundle/Resources/public/scss/fieldType/edit/_base-field.scss
  src/bundle/Resources/views/themes/admin/ui/edit_header.html.twig
  src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
Labels: QA approved

#1540 IBX-9847: Fixed ezobjectrelation selection limit
  src/bundle/Resources/public/js/scripts/fieldType/ezobjectrelationlist.js
Labels: QA approved

#1489 IBX-8471: Upgraded codebase to Symfony 7
  composer.json
  phpstan-baseline.neon
  src/lib/Form/DataTransformer/ContentTypeTransformer.php
  src/lib/Form/DataTransformer/DateIntervalTransformer.php
  src/lib/Form/DataTransformer/DateTimePickerTransformer.php
  src/lib/Form/DataTransformer/FieldType/AuthorValueTransformer.php
  src/lib/Form/DataTransformer/FieldType/BinaryFileValueTransformer.php
  src/lib/Form/DataTransformer/FieldType/DateTimeValueTransformer.php
  src/lib/Form/DataTransformer/FieldType/DateValueTransformer.php
  src/lib/Form/DataTransformer/FieldType/FieldValueTransformer.php
  src/lib/Form/DataTransformer/FieldType/ImageValueTransformer.php
  src/lib/Form/DataTransformer/FieldType/KeywordValueTransformer.php
  src/lib/Form/DataTransformer/FieldType/MediaValueTransformer.php
  src/lib/Form/DataTransformer/FieldType/RelationListValueTransformer.php
  src/lib/Form/DataTransformer/FieldType/RelationValueTransformer.php
  src/lib/Form/DataTransformer/FieldType/TimeValueTransformer.php
  src/lib/Form/DataTransformer/LanguageTransformer.php
  src/lib/Form/DataTransformer/MultilingualSelectionTransformer.php
  src/lib/Form/DataTransformer/ObjectStateGroupTransformer.php
  src/lib/Form/DataTransformer/ObjectStateTransformer.php
  src/lib/Form/DataTransformer/RoleAssignmentTransformer.php
  src/lib/Form/DataTransformer/RoleTransformer.php
  src/lib/Form/DataTransformer/TranslatablePropertyTransformer.php
  src/lib/Form/DataTransformer/UDWBasedValueViewTransformer.php
  src/lib/Form/DataTransformer/UserCollectionTransformer.php
  src/lib/Form/DataTransformer/UserGroupCollectionTransformer.php
  src/lib/Form/DataTransformer/UserTransformer.php
  src/lib/Form/Type/Extension/EventSubscriber/ModifyFieldDefinitionFieldsSubscriber.php
  src/lib/Form/Type/Policy/PolicyChoiceType.php
  src/lib/Validator/Constraints/LocationIsNotSubLocation.php
  tests/bundle/Templating/Twig/FieldEditRenderingExtensionTest.php
  tests/bundle/Templating/Twig/LimitationValueRenderingExtensionTest.php
  tests/lib/Form/DataTransformer/DateTimePickerTransformerTest.php
  tests/lib/Form/DataTransformer/RoleAssignmentTransformerTest.php
  tests/lib/Form/DataTransformer/RoleTransformerTest.php
  tests/lib/Form/DataTransformer/UDWBasedValueViewTransformerTest.php
  tests/lib/Form/DataTransformer/UserTransformerTest.php
  tests/lib/Form/Processor/ContentTypeFormProcessorTest.php
  tests/lib/Form/Type/Extension/EventSubscriber/ModifyFieldDefinitionFieldsSubscriberTest.php
Labels: Ready for SF7

#1532 [Behat] IBX-9859: Adjustments for discounts behat tests
  src/lib/Behat/Component/CreateNewPopup.php
  src/lib/Behat/Component/Dialog.php
Labels: Ready for review

#1547 IBX-8471: Fixed 'Send to trash' confirmation modal after Symfony 7 upgrade
  phpstan-baseline.neon
  src/bundle/Resources/views/themes/admin/content/modal/location_trash.html.twig
  src/lib/Form/Type/Location/LocationTrashType.php
Labels: QA approved

#1536 [Behat] IBX-9915: AI richtext coverage
  src/lib/Behat/Component/Fields/RichText.php
Labels: Ready for review

#1520 IBX-9697: Refactored components to align with new twig-components package
  composer.json
  phpstan-baseline.neon
  src/bundle/DependencyInjection/Compiler/ComponentPass.php
  src/bundle/Resources/config/services/components.yaml
  src/bundle/Resources/config/services/components/content/edit.yaml
  src/bundle/Resources/config/services/components/content_type/edit.yaml
  src/bundle/Resources/config/services/components/layout.yaml
  src/bundle/Resources/config/services/dashboard.yaml
  src/bundle/Resources/config/services/tabs/content_type.yaml
  src/bundle/Resources/config/services/tabs/locationview.yaml
  src/bundle/Resources/config/services/tabs/url_management.yaml
  src/bundle/Resources/views/themes/admin/account/login/index.html.twig
  src/bundle/Resources/views/themes/admin/account/profile/view.html.twig
  src/bundle/Resources/views/themes/admin/content/create/create.html.twig
  src/bundle/Resources/views/themes/admin/content/edit/edit.html.twig
  src/bundle/Resources/views/themes/admin/content/location_view.html.twig
  src/bundle/Resources/views/themes/admin/content/modal/add_translation.html.twig
  src/bundle/Resources/views/themes/admin/content_type/edit.html.twig
  src/bundle/Resources/views/themes/admin/content_type/index.html.twig
  src/bundle/Resources/views/themes/admin/ui/dashboard/block/all.html.twig
  src/bundle/Resources/views/themes/admin/ui/dashboard/block/me.html.twig
  src/bundle/Resources/views/themes/admin/ui/dashboard/dashboard.html.twig
  src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezimage.html.twig
  src/bundle/Resources/views/themes/admin/ui/field_type/edit/ezimageasset.html.twig
  src/bundle/Resources/views/themes/admin/ui/global_search.html.twig
  src/bundle/Resources/views/themes/admin/ui/layout.html.twig
  src/bundle/Resources/views/themes/admin/ui/layout_error.html.twig
  src/bundle/Resources/views/themes/admin/ui/menu/user.html.twig
  src/bundle/Resources/views/themes/admin/ui/on_the_fly/create_on_the_fly.html.twig
  src/bundle/Resources/views/themes/admin/ui/on_the_fly/edit_on_the_fly.html.twig
  src/bundle/Resources/views/themes/admin/ui/tab/location_view.html.twig
  src/bundle/Resources/views/themes/admin/url_management/url_management.html.twig
  src/bundle/Resources/views/themes/admin/user/create.html.twig
  src/bundle/Resources/views/themes/admin/user/edit.html.twig
  src/bundle/Templating/Twig/ComponentExtension.php
  src/contracts/Component/Renderable.php
  src/contracts/Component/Renderer/RendererInterface.php
  src/lib/Component/Content/ContentEditMetaFieldsComponent.php
  src/lib/Component/Content/PreviewUnavailableTwigComponent.php
  src/lib/Component/ContentType/ContentTypeEditMetaFieldsComponent.php
  src/lib/Component/Event/RenderGroupEvent.php
  src/lib/Component/Event/RenderSingleEvent.php
  src/lib/Component/EventSubscriber/RenderEventSubscriber.php
  src/lib/Component/LinkComponent.php
  src/lib/Component/Registry.php
  src/lib/Component/Renderer/DefaultRenderer.php
  src/lib/Component/ScriptComponent.php
  src/lib/Component/Search/GlobalSearchTwigComponent.php
  src/lib/Component/TabsComponent.php
  src/lib/Component/TwigComponent.php
  src/lib/Form/Data/ContentTypeData.php
  tests/bundle/DependencyInjection/Compiler/ComponentPassTest.php
  tests/integration/AdminUiIbexaTestKernel.php
Labels: QA approved

#1542 IBX-8223: Refactored limitation value blocks to use 'ibexa_' prefix
  src/bundle/Resources/views/themes/admin/content/tab/policies/limitation_values.html.twig
  src/bundle/Resources/views/themes/admin/content/tab/roles/limitation_values.html.twig
  src/bundle/Resources/views/themes/admin/limitation/limitation_values.html.twig
  src/lib/Limitation/Templating/LimitationBlockRenderer.php
  tests/bundle/Templating/Twig/_fixtures/render_limitation_value/templates/limitation_value_1.html.twig
  tests/bundle/Templating/Twig/_fixtures/render_limitation_value/templates/limitation_value_2.html.twig
  tests/bundle/Templating/Twig/_fixtures/render_limitation_value/templates/limitation_value_3.html.twig
  tests/bundle/Templating/Twig/_fixtures/render_limitation_value/templates/limitation_value_overriden.html.twig
Labels: Ready for review

#1541 IBX-9918: Added parameter is_link in twig user component
  src/bundle/Resources/views/themes/admin/ui/component/user/user.html.twig
Labels: Bug, QA approved

#1534 IBX-9916: Upgrade frontend dependencies
  src/bundle/Resources/encore/ibexa.webpack.custom.config.js
  src/bundle/Resources/public/js/scripts/admin.content.tree.js
  src/bundle/Resources/public/js/scripts/admin.contenttype.relation.default.location.js
  src/bundle/Resources/public/js/scripts/admin.limitation.pick.js
  src/bundle/Resources/public/js/scripts/admin.location.view.js
  src/bundle/Resources/public/js/scripts/admin.role_assignment.add.js
  src/bundle/Resources/public/js/scripts/admin.search.filters.js
  src/bundle/Resources/public/js/scripts/admin.section.list.js
  src/bundle/Resources/public/js/scripts/admin.section.view.js
  src/bundle/Resources/public/js/scripts/admin.trash.list.js
  src/bundle/Resources/public/js/scripts/fieldType/ezimageasset.js
  src/bundle/Resources/public/js/scripts/fieldType/ezobjectrelationlist.js
  src/bundle/Resources/public/js/scripts/fieldType/ezrichtext.js
  src/bundle/Resources/public/js/scripts/helpers/react.helper.js
  src/bundle/Resources/public/js/scripts/react.dom.load.js
  src/bundle/Resources/public/js/scripts/react.load.js
  src/bundle/Resources/public/js/scripts/udw/browse.js
  src/bundle/Resources/public/js/scripts/udw/copy.js
  src/bundle/Resources/public/js/scripts/udw/copy_subtree.js
  src/bundle/Resources/public/js/scripts/udw/locations.tab.js
  src/bundle/Resources/public/js/scripts/udw/move.js
  src/bundle/Resources/public/js/scripts/udw/select.location.js
  src/bundle/Resources/public/js/scripts/udw/swap.js
  src/bundle/Resources/views/themes/admin/ui/layout.html.twig
Labels: QA approved

#1549 IBX-8304: Fixed dropdown multi selection display
  src/bundle/Resources/public/scss/_dropdown.scss
Labels: QA approved

#1552 IBX-8688: Fixed switcher helper text
  src/bundle/Resources/public/scss/_custom-url-form.scss
  src/bundle/Resources/views/themes/admin/url_wildcard/modal_create.html.twig
  src/bundle/Resources/views/themes/admin/url_wildcard/update.html.twig
Labels: Ready for QA

#1546 IBX-9973: Only 10 editors are displayed on users list
  src/bundle/Resources/public/js/scripts/core/suggestion.taggify.js
  src/bundle/Resources/public/scss/_taggify.scss
Labels: Bug, QA approved

#1565 IBX-9759: Fixed disabled fields styles
  src/bundle/Resources/public/scss/_tag-view-select.scss
  src/bundle/Resources/views/themes/admin/ui/component/tag_view_select/tag_view_select.html.twig
Labels: Ready for review

#1556 IBX-9944: Add support for stateless CSRF protection in admin-ui
  src/bundle/Resources/config/services/ui_config/common.yaml
  src/bundle/Resources/views/themes/admin/ui/layout.html.twig
  src/bundle/Templating/Twig/SecurityExtension.php
  tests/bundle/Templating/Twig/SecurityExtensionTest.php
  tests/bundle/Templating/Twig/_fixtures/security/ibexa_get_rest_csrf_token_intention.test
Labels: Ready for QA

#1567 Added missing return types
  phpstan-baseline.neon
  src/bundle/Templating/Twig/ComponentExtension.php
  src/bundle/Templating/Twig/FormatIntervalExtension.php
  src/bundle/Templating/Twig/TimeDiffExtension.php
  src/lib/Translation/Extractor/NotificationTranslationExtractor.php
  src/lib/Validator/Constraints/LocationHasChildren.php
  src/lib/Validator/Constraints/LocationHaveUniqueAssetRelation.php
  src/lib/Validator/Constraints/LocationIsContainer.php
  src/lib/Validator/Constraints/LocationIsNotRoot.php
  src/lib/Validator/Constraints/LocationIsNotSubLocation.php
  src/lib/Validator/Constraints/LocationIsWithinCopySubtreeLimit.php
Labels: Ready for review
