Repository ibexa/admin-ui, pull requests merged in 2025-07, with the labels that each got.

#1611 IBX-9895: Encoded location search query identifier
  src/bundle/ui-dev/src/modules/common/services/content.service.js
  src/bundle/ui-dev/src/modules/universal-discovery/services/universal.discovery.service.js
Labels: Bug, QA approved

#1607 IBX-9894: Prevented invitation form submission with the enter key
  src/bundle/Resources/public/js/scripts/user.invitation.modal.js
Labels: Bug, QA approved

#1616 IBX-9727: Aligned codebase after core content VO type hints changes
  phpstan-baseline.neon
  src/lib/Form/Data/Section/SectionUpdateData.php
  src/lib/Form/DataMapper/LanguageCreateMapper.php
  src/lib/Form/DataMapper/SectionUpdateMapper.php
  tests/lib/EventListener/SetViewParametersListenerTest.php
  tests/lib/Form/DataMapper/SelectionUpdateMapperTest.php
  tests/lib/Form/Processor/PreviewFormProcessorTest.php
  tests/lib/Pagination/Pagerfanta/TrashItemAdapterTest.php
Labels: Rebase required

#1608 IBX-8638: Ensured last ancestor is valid before comparing paths in TrashItemData
  phpstan-baseline.neon
  src/lib/Form/Data/TrashItemData.php
  tests/lib/Form/Data/TrashItemDataTest.php
Labels: Ready for QA

#1603 IBX-10170: Refactored access check to use new contract interface
  src/bundle/EventSubscriber/PerformAccessCheckSubscriber.php
  src/bundle/Resources/config/services/events.yaml
  src/contracts/Controller/Controller.php
Labels: QA approved

#1609 IBX-10125: Handled image upload failed request
  src/bundle/Controller/AssetController.php
  src/bundle/Resources/public/js/scripts/helpers/request.helper.js
Labels: Bug, QA approved

#1625 IBX-10221: Fixed 500 error when removing Site skeletons by improving location root checks
  composer.json
  phpstan.neon
  src/lib/Menu/ContentRightSidebarBuilder.php
  src/lib/Specification/Location/IsContentStructureRoot.php
  src/lib/Specification/Location/IsInContextualTreeRootIds.php
  src/lib/Specification/Location/IsRoot.php
  tests/lib/Specification/Location/IsContentStructureRootTest.php
  tests/lib/Specification/Location/IsInContextualTreeRootIdsTest.php
  tests/lib/Specification/Location/IsRootTest.php
  tests/lib/Validator/Constraint/LocationIsNotRootValidatorTest.php
Labels: QA approved, Ready for review

#1628 IBX-6657: Fixed margin in ezauthor field
  src/bundle/Resources/public/scss/fieldType/edit/_ezauthor.scss
Labels: Ready for QA

#1627 IBX-10240: Fixed font color in trash creator filter
  src/bundle/Resources/public/scss/_trash-search-form.scss
Labels: Ready for QA

#1635 IBX-6770: "All functions" policy spelling fix
  src/bundle/Resources/views/themes/admin/user/policy/list.html.twig
Labels: Ready for QA

#1637 IBX-10207: Fixed dropdown empty state image
  src/bundle/Resources/public/scss/_dropdown.scss
Labels: Ready for QA

#1640 IBX-8754: Fixed label spacing for content type fields options
  src/bundle/Resources/public/scss/_content-type-edit.scss
Labels: Ready for QA

#1648 Replaced `ibexa_render_component_group` with `ibexa_twig_component_group` in form fields template.
  src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
Labels: Ready for review

#1653 IBX-10358: Close icon in AI Assistant is barely visible
  src/bundle/Resources/public/scss/ui/modules/common/_draggable.dialog.scss
Labels: Ready for QA

#1639 IBX-9978: Fixed media field checkboxes alignment
  src/bundle/Resources/public/scss/fieldType/edit/_ezmedia.scss
  src/bundle/Resources/views/themes/admin/ui/field_type/edit/binary_base_fields.html.twig
Labels: Ready for QA

#1623 IBX-8167: creators list covered by chevron
  src/bundle/Resources/public/scss/_filters.scss
Labels: Ready for QA, Ready for review

#1597 IBX-10064: Fix notification close removes focus from dropdown
  src/bundle/Resources/public/js/scripts/admin.notifications.js
Labels: Ready for QA, Ready for review

#1600 IBX-10145: Fix ibexa-toggle clickable area
  src/bundle/Resources/public/scss/_inputs.scss
Labels: QA approved, Ready for review

#1599 IBX-10117: Errors thrown in the console when uploading more files
  src/bundle/ui-dev/src/modules/multi-file-upload/components/upload-list/upload.list.component.js
Labels: Bug, QA approved

#1646 Adapted to deprecated `null` value for content structs in `BaseContentType`
  src/bundle/Controller/User/ProfileEditController.php
  src/bundle/Controller/UserOnTheFlyController.php
Labels: Bug, Ready for review

#1657 Fixed editing content from UDW after dropping non-nullable `struct` parameter from parent form
  phpstan-baseline.neon
  src/bundle/Controller/ContentOnTheFlyController.php
  src/lib/EventListener/UserProfileListener.php
  src/lib/FieldType/Mapper/AuthorFormMapper.php
  src/lib/Form/Data/ContentTranslationData.php
  src/lib/Form/Processor/PreviewFormProcessor.php
  src/lib/Form/Processor/TranslationFormProcessor.php
Labels: Bug, Ready for review

#1630 IBX-10204: Updated create/edit content header
  src/bundle/Resources/public/img/ibexa-icons.svg
  src/bundle/Resources/public/img/icons/translate.svg
  src/bundle/Resources/public/js/scripts/edit.header.js
  src/bundle/Resources/public/scss/_edit-header.scss
  src/bundle/Resources/translations/ibexa_content_create.en.xliff
  src/bundle/Resources/translations/ibexa_content_edit.en.xliff
  src/bundle/Resources/views/themes/admin/content/create/create.html.twig
  src/bundle/Resources/views/themes/admin/content/edit/edit.html.twig
  src/bundle/Resources/views/themes/admin/ui/edit_header.html.twig
  src/bundle/Resources/views/themes/admin/ui/edit_header_tooltip.html.twig
Labels: QA approved
