Repository ibexa/admin-ui, pull requests merged in 2025-06, with the labels that each got.

#1572 IBX-10102: [...] button is shorter than other buttons in content menu
  src/bundle/Resources/public/scss/_context-menu.scss
Labels: Bug, Ready for QA

#1573 IBX-7940: Fixed clearing email input field
  src/bundle/Resources/views/themes/admin/account/forgot_password/index.html.twig
Labels: Ready for review

#1570 IBX-9759: Fixed id_disabled value and styles condition
  src/bundle/Resources/views/themes/admin/ui/component/tag_view_select/tag_view_select.html.twig
Labels: Ready for QA

#1585 IBX-10130: [Twig] Added admin-ui-versions-table-before component group
  src/bundle/Resources/views/themes/admin/content/tab/versions/table.html.twig
Labels: Improvement, Ready for review

#1578 IBX-10100: Collaborator's icons should be displayed above field's label
  src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
Labels: Bug, QA approved

#1586 IBX-10134: Remove depracated JS/twig code
  src/bundle/Resources/views/themes/admin/ui/form_fields.html.twig
Labels: Ready for review

#1577 IBX-10122: Fix misspelled includedIcon filename
  src/bundle/ui-dev/src/modules/common/icon/icon.js
  src/bundle/ui-dev/src/modules/common/icon/includedIcon.js
  src/bundle/ui-dev/src/modules/common/icon/inculdedIcon.js
Labels: Ready for QA

#1594 IBX-8561: Fixed relation list when trying to display unauthorized content
  src/bundle/Resources/views/themes/admin/ui/field_type/edit/relation_base.html.twig
Labels: QA approved

#1517 IBX-6554: Prevent Twig errors when location is not defined in Location View
  phpstan-baseline.neon
  src/bundle/Controller/ContentViewController.php
  src/bundle/Resources/views/themes/admin/content/location_view.html.twig
  src/lib/Menu/Voter/LocationVoter.php
Labels: Bug, QA approved, Ready for review
